### ISSUE TITLE
rclone serve - serve a remote over http

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1007]
...in such a way rclone could use it with an "rclone" remote.

Perhaps allow it to be served over ssh or some other socket too.

**Comment by calisro** [comment]
This is actually a very very interesting idea.  I saw someone mention 'rclone serve' in the forum.  If this was available, I can see a very basic app created on the android platform, for example, where it would keep rclone serve http/ftp/whatever up and running in the background and we could then stream/access our files via http.  Imagine being able to modify the http css as well via the app and we have a inbuilt application now to via/access all our rclone data whether it be via crypt or noncrypt.

Right now, im forced to not crypt some content so that I can use Amazon's app to access those files remotely (surveillance videos).  With something like this, I can crypt everything.

**Comment by cal2195** [comment]
This would also allow for any browser (Android and iOS) to browse to a machine hosting the rclone serve! Which would hopefully work better than rclone mount over sshfs! :)

**Comment by ncw** [comment]
This has now been done... You can use `rclone server webdav` and use the webdav backend to read files from it.
