### ISSUE TITLE
rclone mount handling incorrect remote path

### ISSUE THREAD

**Issue by kcwu** [ncw/rclone#1048]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.35-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
FreeBSD

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone mount foo bar`

IIUC, the correct syntax should be `rclone mount foo: bar`. rclone didn't reject my incorrect remote name. 
Instead, rclone still try to mount it (according to `mount` and `df` command) but the `bar` folder is still empty.

**Comment by ncw** [comment]
If you don't have a : in your remote name, it refers to a local path

    rclone mount foo bar

This will cause rclone to mount the directory in the current directory called "foo" onto the directory "bar".  Due to the way rclone works, if "foo" doesn't exist, then it doesn't matter - it will be created if you copy files into the mount.

So that is expected behaviour. 

However I could make rclone mount check the directory exists which might make more sense - it would then exit with an error "directory not found".

**Comment by kcwu** [comment]
Ah, this makes sense. I am okay to keep current behavior. Feel free to close this issue if you don't plan to change the behavior.

**Comment by ncw** [comment]
OK I'll leave rclone how it is until I get more requests!

Thanks
