### ISSUE TITLE
Feature request: virtual remote to shorten path

### ISSUE THREAD

**Issue by kcwu** [ncw/rclone#1049]
Currently, most remotes reference to the root of the remote storage. However, sometimes I only want to access one subfolder. I feel it's handy if rclone has a mechanism to shorten the path. 

My suggestion is adding a new type of remote, which can act as alias to the other remotes. The config might look like:
```
[foo]
type = alias
remote = bar:the/path/to/my/folder
```
Then access `foo:baz/hello` is actually to access `bar:the/path/to/my/folder/baz/hello` transparently.

Actually, `crypt` remote already has this kind of functionality. In some sense, `alias` remote acts like `crypt` remote without encryption ;)

**Comment by ncw** [comment]
This is a similar, but slightly different idea to #1014

My plan there was for each remote to grow a "root" parameter rather than make an alias type of remote.

**Comment by kcwu** [comment]
One small advantage of alias remote is avoiding to duplicate authentication tokens of the same underlying remote.

**Comment by ncw** [comment]
Creating aliases would be useful for rclone's internals too sometimes (eg `--backup-dir` takes two remotes, where it should only really be one).

**Comment by ncw** [comment]
@B4dM4n wrote:
> How could a alias help simplify --backup-dir?

My not completely thought through plan was to make `drive:folder` an alias of a root `drive:`.  And implement the aliases with a kind of chroot for a remote, so keep the underlying `drive:` hidden from the user and only give them the chroots `drive:backup` and `drive:sub/folder`

At the moment when you do

    rclone copy --backup-dir remote2:backup remote1:sub/folder remote2:sub/folder

rclone makes two remotes, one for the backup-dir and one for the dest, where it should only really make one `drive:` and use the `backup` and the `sub/folder` directories in it.

This decision caused a lot of untidiness in the remotes around the Copy, Move and MoveDir optional methods.

> The folder has to be specified nonetheless. A way to simplify --backup-dir could be making it relative to the destination remote:

That would still need rclone to make a `drive:` remote then do the syncing to "sub/folder" rather than making a "drive:sub/folder" remote and syncing to "" which is what it does at the moment.

> I created a simple alias backend as an example, which is fully functional.

Anyway, I think the two ideas are orthogonal and the alias backend is simple and useful so looks like a good idea to me :-)

**Comment by saviodsouza** [comment]
https://forum.rclone.org/t/local-back-end-path/4673

**Comment by ncw** [comment]
Please find the alias remote here (thanks @B4dM4n )

https://beta.rclone.org/v1.39-124-gb183bd7f/ (uploaded in 15-30 mins)

The docs [are here](https://github.com/ncw/rclone/blob/master/docs/content/alias.md).
