### ISSUE TITLE
[ Feature request ] buffer the whole file on disk ( for streaming ) 

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#1050]
Could we get a rclone mount flag that would allow us to buffer the whole file on disk. 
The idea is if you set this flag the file you are playing would be buffering on disk until its complete.

So on seek rclone would need to check if seek position is already in buffer before trying to access it on cloud. 

This would solve a lot of problem with streaming. 
Its important that it would be done on disk as on multiple streams you could soon be out of ram.

**Comment by endiz** [comment]
I would also love this feature! 

Another great option for buffering would be to keep the buffer for X amount of days, and total buffer size in case multiple files are buffered.

**Comment by flixajki** [comment]
It would be nice endiz but lets not over complicate as keeping for x days would mean rclone needs local db to track it and that would just add complexity eg would take some time to make.

While buffering file completely on disk is not such a big feature as ncw already had buffering. 
Maybe we could get basic flag first and then go from there.

**Comment by ncw** [comment]
It is certainly an easier feature to implement if rclone doesn't have to persist a db.  However rclone would have to do some of that work as I guess you don't want rclone dropping the cache if you restart your video player for instance so the file gets closed and then opened again.

**Comment by flixajki** [comment]
Just drop the cache.
Maybe at one point when rclone have local DB for file and folder structure, this could be updated.

But for now to really get best performance a simple flag that would allow us to buffer whole file on disk would be tremendous improvement for streaming.

**Comment by endiz** [comment]
I agree with flixajki, some type of cache is better then nothing.  if you implement as an opt-in flag, it gives the user the choice between buffer & poor seek vs non buffer & good seek performance.

**Comment by flixajki** [comment]
For an average Plex user the seek would be much better as you seek only couple of seconds in advance.
The only time you seek at middle of end of video is when you close the video and continue to watch later on.

**Comment by flixajki** [comment]
@ncw what did you change to improve seeks and how did that influence on existing buffering ?

**Comment by ncw** [comment]
@flixajki wrote
> what did you change to improve seeks and how did that influence on existing buffering ?

There have been lots of incremental improvements to seek.  One of the main ones was getting it to work under crypt without opening the file twice for each seek.

There is discussion of more buffering here: #1043 this wouldn't buffer the whole file though, just do read-ahead.

**Comment by flixajki** [comment]
> One of the main ones was getting it to work under crypt without opening the file twice for each seek.

This would still stay be same even with buffering the whole file on disk.

**Comment by gordan-bobic** [comment]
You could achieve this by using a combination of lsyncd (uses inotify to monitor file access, and triggers a command) and mergerfs. When it detects an access, it starts fetching the file down into the local cache that is earlier in the mount list for mergerfs than the rclone mount. What you would probably need to do is fetch to a temporary location on the same fs as the local cache, then mv the file to the cache path.

However, this isn't going to work well transparently because it will fundentally break things like scanning. Or rather, it won't break it, but every time your media server does a library refresh, it will fetch down the entire file, rather than just the header where the MOOV atom is (and that should be at the front for streaming optimized files).

I don't see an easy way to distinguish whether the file is opened for a scan (only get the first few MB) or playing (whole file will be needed).

I light of that, a good prefetch feature such as what is proposed by the following two:
https://github.com/ncw/rclone/issues/995
https://github.com/ncw/rclone/issues/1043
would almost certainly be a better and more universally applicable solution. If you really want the whole file buffered down, you can still implement it using lsyncd+mergerfs (and live with the side effects of it trying to pull the entire library down to the local cache). You would also likely need a cron job to prune the local cache every few hours.

**Comment by flixajki** [comment]
> but every time your media server does a library refresh, it will fetch down the entire file
 It would not as soon as the header is read Plex would not have that file open anymore eg the buffering would stop. 

the lsyncd+mergefs is not really the good solution as then on every file access you would be fetching the whole file, it needs to be done within rclone to make it work.

And since ncw already had buffering working its not something that would require a lot of coding. .

As I said it should be optional flag so those who needed use it.

**Comment by gordan-bobic** [comment]
You can script exactly what you want lsyncd to do, e.g. fetch to staging area if file is in neither in staging or caching area, and when done move from staging to cache. It would only refetch the file if it is accessed again after the cache cleanup cron job removed it. You would still get the upstream accesses for requests made while the file is spooling up into staging.

For bridging the gap and saner use cases I still thing that the more classical approach of large deadhead with caching as described in the other two tickets is more appropriate, and this specific functiomality then gets covered by the additional lsyncd+mergerfs stack.

**Comment by Merckle** [comment]
I wish i knew enough to help contribute bit would be an awesome idea for sure

**Comment by flixajki** [comment]
> You can script exactly what you want lsyncd to do, e.g. fetch to staging area if file

I know what you mean but then again you could choose to script a lot of functionality that you already have in rclone. 

Since explosion of Plex & Amazon Drive popularity in last few months the rclone is becoming the all in one tool for most of the users and since a lot of users are utilizing cheap VPS's the ram could be the issue. 

More or less we are talking about the same issue we have while those two suggestions want to keep "buffer" in ram and my suggestion is to save it to disk. For best performance I would definitely like to set max-readahead 20GB but thats not really viable due ram limitation, since we are always talking about multiple streams. 

Atm the default values rclone uses are already good and having the option to tweak for 100MB to 500MB would not really change anything beside probably breaking seek functionality. 

We get a lot more "spare" bandwith then ram.

**Comment by gordan-bobic** [comment]
> I know what you mean but then again you could choose to script a lot of functionality that you already have in rclone.

Not that much, and while some things cannot easily be added in externally, this can. Also consider that @ncw's time time to work on rclone is much more limited than the combined time of rclone's users available to come up with stackable solutions based on it.

Perhaps we should start adding wiki entries with recipes for add-ons. I already wrote a mount wrapper script that can be used from fstab for a different ticket. This could be treated similarly.

**Comment by flixajki** [comment]
> start adding wiki entries
Great idea

> big reason for ACD's increased popularity recently has been Plex Cloud

Yea the Plex Cloud made the bang and since they dropped ACD most are looking for hosting solutions. 

> Cheap VPS also lacks disk space for file caching unless you pay extra for it, and you'll need quite a lot. You mention 10 streams. 10x 1080p movies at 10Mbps (8-10GB each) is up to 100GB just for caching

Yes my point exactly and that same vps will have 512MB to 8GB ram in average eg ram buffering wont do much.  For example:
![mstsc_2017-01-20_08-56-44](https://cloud.githubusercontent.com/assets/23003132/22140748/a98a3cac-deee-11e6-84d5-4fb8697f1afb.png)
It would still be much easier to store all cache you need on 200GB compared to 8GB ram :)

On top of it you have 200MBit connection that could transfer that 8GB in 6 to 10 minutes and then user can seek all over the place without any slowdown.

> Also consider that @ncw's time time to work on rclone is much more limited
My point exactly tweaking the current prebuffer ram setting wont do much difference, having the whole file prebuffered within first 10 minutes its already solution.

Personally i dont really see any advantage of tweaking current buffer to use couple of MB's more what will that improve ? If the whole movie is not buffered we do not get anything, the only good thing about allowing that flag would be for users to test what would be best amount so ncw can set it as default.

**Comment by gordan-bobic** [comment]
Actually, a small amount of RAM buffering will make a substantial difference. IIRC, the (AFAICT undocumented) throttling limit is 2,000 requests per hour from ACD. BluRays are encoded at about 30Mbpa (3.75MB/s). That's 13,500MB/hour. That means you'll stay under the limit if your request size averages at least 6.75MB.

Let's say you have 10 friends streaming simultaneously, that bumps up the request size requirement to 67.5MB, and there are 10 of those going on simultaneously, so you need 675MB of RAM to cache those effectively in a way that prevents stutter. Let's double that just to be sure: 1350MB. Let's then assume that AWS might throttle at half that many requests per hour, so double it again: 2700MB. This is very much a worst case scenario. In reality you won't be using raw BR extracts because 1) some aren't H.264, some are AVC1 encoded, and 2) Chromecasts and most similar devices are only specced for streams up to 12Mbit/s including audio. So in reality the 2700MB requirement for the worst case scenario is overspecified by at least a factor of 3x. And that is still 1/3 of the RAM in the VM you have listed above.

The obvious upshot of not buffering up the entire file is that you specifically **don't** want to do that when you rescan a library, as that will end up fetching the entire file just to read the MOOV atom from the beginning of the file.

I was toying with using mergerfs **without** lsyncd, because my viewing pattern is largely predictable (to me at least), e.g. I know which series I'm watching at the moment so I might as well prefetch the whole season manually, which sorts me out for the next few weeks of viewing time.

But just having prefetching work up to a configured size by over-reading would largely remove the throttling impact while still being able to use a $3.50 VM from OVH with a single core and 1GB of RAM, and just enough disk space to fit the media server's metadata database if it's on a compressed file system.

But the key point is that the average request size is tiny, probably in the 2-3MB range. If we can bump this up by a factor of 10, the entire problem goes away while still only using an amount of RAM small enough that a more complex full file prefetch solution isn't needed.

**Comment by flixajki** [comment]
Great post with detail description,  but you are assuming that every file that is accessed would be prefetched completely ( that would be the case with mergerfs ) but thats not the case as rclone would drop connection as soon as file is not accessed anymore ( the only real difference is where the buffer is stored eg disk vs ram ) so the worse case scenario Plex would need to read only header of the file (for scan) and during that time you server would download more data then needed. 

Let me ask you differently, if the flag with buffering is added ( like in both of us want ) eg -prebuffer = NUM (max ammount ) would be better that its stored on disk so you can either do 2GB or 20GB ?

We both agree that prebuffer is needed to tweak and I agree even in the case Iam suggesting it would be better if the flag supported NUM on how much you want to buffer and not automatically prebuffer whole file. 

What @ncw could do is add new flag -prefetch NUM(size) HDD/RAM or prefetch-hdd, prefetch-ram whatever makes more sense. ( we could also add start time for it eg do not start prebuffer until file is open for at least 10 seconds eg and quick scans that do not need any preftech would not cause more download then needed )

**Comment by gordan-bobic** [comment]
Right, I think I finally understand fully. What you are effectively proposing is something very similar to ZFS' L2ARC. The difference being that just using regular prefetch and caching in memory is relatively straightforward to do, while implementing a L2ARC is much more complex. If the caching would be to happen in rclone memory rather than kernel memory, this could perhaps be addressed with simply providing swap (and rclone's cache pages would get swapped out when they no longer fit into RAM. @ncw already stated that rclone doesn't use libfuse, which means that any assumptions we make based on prior experience with FS-es that use libfuse may well be invalid. Either way it sounds like an **extra** feature on top of prefetch buffering as discussed in the other two related tickets mentioned above.

**Comment by flixajki** [comment]
@ncw what are your thoughts  on the subject.

**Comment by ncw** [comment]
@gordan-bobic wrote
> Actually, a small amount of RAM buffering will make a substantial difference. IIRC, the (AFAICT undocumented) throttling limit is 2,000 requests per hour from ACD. 

Interesting info!

I'll just note that if you are streaming from ACD, then rclone only makes one request, then one request for each seek - it doesn't need to keep making requests as long as you access the data sequentially, ACD just streams the data.

> But the key point is that the average request size is tiny, probably in the 2-3MB range. If we can bump this up by a factor of 10, the entire problem goes away while still only using an amount of RAM small enough that a more complex full file prefetch solution isn't needed.

So this isn't the case - the average request will be for the entire size of the file.

I'll add the buffering in  #1043 first - then we can take a view on how much difference a more complicated scheme buffering to disk would make.

**Comment by jrwr** [comment]
Even just a block based LRU cache and some read ahead would be nice, if 20-30% of the file has been read, start working on the rest of the blocks of the file, allowing for tuning and shouldn't be too bad to do overall, mostly just selecting a good data index store would be important

**Comment by ajkis** [comment]
Closing the issue and remaking similar one based on current buffier-size here: https://github.com/ncw/rclone/issues/1172
