### ISSUE TITLE
Implement binary diffing

### ISSUE THREAD

**Issue by mrschyte** [ncw/rclone#113]
Implement a binary diffing scheme to allow efficient updates for large files.

**Comment by ncw** [comment]
I don't think this is possible with any of the cloud storage providers, unless you've got a cunning idea I haven't thought of? 

Unless perhaps you lost the idea that your are just uploading objects and you upload and store diffs. Rclone would then put the diffs back together for you on download. 

That would be a big change in philosophy though as eg you wouldn't be able to see your docs on google drive.

**Comment by mrschyte** [comment]
Some providers support partial uploads (dropbox does) which would allow you to modify the binaries in place. You could store a bunch of hashes e.g. a Merkle tree as metadata and then use it to find the chunk that has to be updated. This would allow fast uploads and downloads.

Even if the provider doesn't support partial uploads, this technique would be useful to speed up downloads.

**Comment by klauspost** [comment]
I think you are looking for a different product than rclone, but @ncw is probably the one to ask.

There are no index/metadata files - it is a raw file storage, rclone doesn't add any "secret" files. 

Even if partial upload is possible, it will only be a gain if the end of the file is modified. AFAICT Dropbox only supports [partial uploads as part of a complete upload](https://www.dropbox.com/developers/core/docs#chunked-upload), so you cannot use it to change an existing file. It seems as if the binary diff function in Dropbox isn't available for developers.

For download you are right, you can use [http range requests](https://www.dropbox.com/developers/core/docs#files-GET) to get partial file content, but that would still require some metadata on individual file chunks.

**Comment by ncw** [comment]
I'm going to write this up in a new FAQ entry, something like this

### Why doesn't rclone support partial transfers / binary diffs like rsync? ###

Rclone stores each file you transfer as a native object on the remote
cloud storage system.  This means that you can see the files you
upload as expected using alternative access methods (eg using the
Google Drive web interface).  There is a 1:1 mapping between files on
your hard disk and objects created in the cloud storage system.

Cloud storage systems (at least none I've come across yet) don't
support partially uploading an object. You can't take an existing
object, and change some bytes in the middle of it.

It would be possible to make a sync system which stored binary diffs
instead of whole objects like rclone does, but that would break the
1:1 mapping of files on your hard disk to objects in the remote cloud
storage system.

All the cloud storage systems support partial downloads of content, so
it would be possible to make partial downloads work.  However to make
this work efficiently this would require storing a significant amount
of metadata, which breaks the desired 1:1 mapping of files to objects.

**Comment by ncw** [comment]
@mrschyte Thanks for the report - I've put the FAQ item live now
