### ISSUE TITLE
Preserve symlinks - implement `-l`, `--links`

### ISSUE THREAD

**Issue by joeytwiddle** [ncw/rclone#1152]
Thanks for the `-L` option. In this issue I am looking for something different.

I want to be able to remember symlinks but *without* copying the file or folder that they are pointing to.

> (I am a Linux user who makes heavy use of symlinks. Sometimes I even have broken links I want to preserve, even though the target does not exist!)

My cloud storage system is B2, which does not support symlinks. However I think rclone could workaround this.

If it sees a symlink, and `--fake-symlinks` is enabled, then it should upload a small file to the remote with the same name but a custom extension, for example `original_node_name.rclone_symlink`. That file would simply contain the path that the symlink was pointing to (as given by `readlink`).

When reading with the same option, any files encountered with that extension should be converted back into symlinks on the local.

> (This option would probably only be applicable on UNIX-like systems, since I understand Windows has trouble managing links without being administrator.  Windows shortcut files are a possible alternative. For example, Cygwin treats Windows shortcuts as symlinks.)

Steps to reproduce problem:

```bash
# Create a symlink (broken or not, doesn't matter)
ln -s /path/to/target ./test-symlink
# Just a quick verify where it is pointing to
readlink ./test-symlink
# Try to clone it
rsync clone -vv -n ...
```

Output indicating that the symlink was not stored on the remote:

    2017/02/19 14:16:09 test-symlink: Can't transfer non file/directory

**Comment by ncw** [comment]
What you are after is this flag from rsync

```
        -l, --links                 copy symlinks as symlinks
```

rclone has all the bits and bobs to implement that now using its MimeType calls.

A bit of research indicates that the correct type should be `inode/symlink`.

I thought there was a ticket about this, but apparently not!

**Comment by majutsushi** [comment]
Has there been any progress on this? Without this option it's essentially impossible to do a lossless backup-and-restore of a typical home directory, so it would be really great if it could be implemented. Thanks!

**Comment by baip** [comment]
This would be really nice! I think placeholder files are also how Cygwin handles symbolic links.

**Comment by mesca** [comment]
Any chance this can be added to the next milestone? With directory handling scheduled for v1.39, this is the last feature needed for lossless backup.

In any case, thank you @ncw for the amazing work.

**Comment by rawtaz** [comment]
I needed this too right now. Had to sync a ~ on a macOS machine, but as there was a lot of symlinks I couldn't use rclone as I had intended, had to use rsync instead :)

**Comment by fancnsnyuedu** [comment]
This feature, preserving symlinks, is extremely needed to do backups
of home directory.  Hope it gets to be implemented sooon.

Thanks much for all your work!!

**Comment by JasonZX12R** [comment]
This would be a great feature to add.  Improving rclone's usefulness in my use case quite a bit, as well as making certain system backups easier.

**Comment by mstgrv** [comment]
Bump on this feature - my use case is using Carbon Copy Cloner to clone my (macOS) system to a local drive, then using rclone to copy/sync the clone to Google Drive.

macOS uses symlinks extensively so unless/until rclone supports them, this isn't possible,

**Comment by yairm** [comment]
I would like to help implement symlink support for rclone.
The main idea:
Create a zero-length remote file for each symlink, the filename will encode the source+destination, and rclone will be able to "copy" this file back from the remote as a symlink.
I suggest the remote files will be named something like ".rclone-symlink-src-dst"

I see two ways to go about it:
1/ Add this is a feature to rclone (I.E., the requested -l option) 
2/ Add this is a new remote "remote-symlink" that will wrap a remote adding this layer of symlinks.

I've implemented a variant of the above proposal as a wrapper around rclone. I would like to help out, and implement it in rclone itself.
Any thoughts please?

**Comment by yairm** [comment]
@dbeckwith Thanks. Putting the destination as the file's contents is fine.

**Comment by DurvalMenezes** [comment]
@dbeckwith > I think a more robust implementation would be to write the destination as the contents of the file.
I agree. It would also have the advantage of avoiding issues with filename length limits, which can be pretty severe in some cloud storage systems. 

Perhaps the fact itself that the file is a symlink could be coded in the file name (therefore precluding the need to set/read 'file attributes'  in the cloud storage system, which I understand is a major problem for this implementation of this feature), and putting the symlink destination in the file contents, would be the best approach? 

Cheers, -- Durval.

**Comment by yairm** [comment]
@DurvalMenezes: Seems fine.

Any comments re. whether this should be directly supported vs. a 'remote wrapper'?

**Comment by ncw** [comment]
I agree that putting the symlink destination into the file is probably the sensible thing to do.  Note that symlinks need to be made relative before being stored.

My original idea was that we would use `inode/symlink` as the mime type.  This would limit the feature to remotes which support R/W of mime type (see [overview features](https://rclone.org/overview/#features) table).  Using a special extension would work universally though - I'd suggest somthing unusual like `.🔗` if we go that way.

This could be implemented as a remote I think, but no reason why the `-l` flag couldn't automatically add it on for the user.

Maybe the best/implest implementation is to just change the local remote. So with the `-l` flag the local remote wouldn't skip or follow the link but generate a file called `path/to/link.🔗` with its contents, and if it was asked to write such a file then it would write a symlink instead.

This would mean that the links would be clearly visible on remotes and that you could copy them between remotes without any special support (eg backup s3 to dropbox).

I guess this could be generalized to the other "special" files unix uses like devices etc.

**Comment by jcollie** [comment]
> Note that symlinks need to be made relative before being stored.

I'd prefer it if symlinks weren't modified before being stored. They should be stored as-is because on disk symlinks can be either relative or absolute and modifying them before storing would lose that information.

Instead I would store the symlink as-is and then on restore I would require a special flag (``--restore insecure-symlinks`` maybe?) or I would skip restoring absolute symlinks or relative symlinks that pointed outside of the restore directory.

**Comment by cowwoc** [comment]
I'm not a fan of encoding metadata into the path of the file, or spreading metadata like butter across the entire filesystem.

I'd like to propose creating a file with the source file path, having its contents be the path of the target path, and store all metadata in `/.rclone`.

The metadata would describe the type of files so you could differentiate between normal files and symlinks. This would also reduce the probability of name collisions because you'd control what files exist under `/.rclone`.

**Comment by yairm** [comment]
> I agree that putting the symlink destination into the file is probably the sensible thing to do. Note that symlinks need to be made relative before being stored.
> 
> My original idea was that we would use `inode/symlink` as the mime type. This would limit the feature to remotes which support R/W of mime type (see [overview features](https://rclone.org/overview/#features) table). Using a special extension would work universally though - I'd suggest somthing unusual like `.🔗` if we go that way.
> 
> This could be implemented as a remote I think, but no reason why the `-l` flag couldn't automatically add it on for the user.
> 
> Maybe the best/implest implementation is to just change the local remote. So with the `-l` flag the local remote wouldn't skip or follow the link but generate a file called `path/to/link.🔗` with its contents, and if it was asked to write such a file then it would write a symlink instead.
> 
> This would mean that the links would be clearly visible on remotes and that you could copy them between remotes without any special support (eg backup s3 to dropbox).
> 
> I guess this could be generalized to the other "special" files unix uses like devices etc.

Never thought of updating the local remote.. Seems like an interesting idea :)

Thinking about this a bit, I guess this means that, correct me if I'm wrong, that a symlink is a regular file object with a special name (.🔗) and its contents is the destination of the symlink. 
When it gets to a remote that support symlinks ('local' for example) it gets interpreted as a symlink, and is handled accordingly. If a symlink is read from a remote that supports symlinks, it generates the above 'normal' file object.

In short, symlink-aware remotes communicate this information via the special file name (.🔗).

What about listing a directory?
Will it show filename or filename.🔗?
For non-symlink-aware remotes, it's obviously, filename.🔗.
For symlink-aware remotes, will it also be filename.🔗?


In addition, the fuse mount will probably implement 'readlink() and symlink()'
symlink() will create a file object with the filename.🔗 extension and write to it. It will be handled accordingly by the different remotes (both symlink-aware and not).
readlink() will also need to understand the special semantics, and generate a read for filename.🔗, reading its contents and returning it to fuse.

The listing of directories with fuse also needs some attention.
We want the listing to show a filename without .🔗, of course.

I think this means, that symlinks will work normally, even if mounted over a remote that is not symlink-aware (!)

This behaviour will only be available if -l is specified.

If -l is not specified, symlink-aware remotes will behave exactly as remotes that are not symlink-aware, if they are handed a (symlink) special named file object, or if they happen to read such a file from the file system. 
also, symlink() and readlink(), will not be registered to fuse.

**Comment by cowwoc** [comment]
Can't wait to have to type these special characters on command-line. Better hope we have a GUI or path-completion where this gets used otherwise it'll be a pain in the rear.

**Comment by yairm** [comment]
@cowwoc Perhaps the selection of the suffix should be a configuration option. That way, one could choose a suffix to his liking (I would personally prefer something like '.rclonelink')

**Comment by ncw** [comment]
@cowwoc 
> Can't wait to have to type these special characters on command-line. Better hope we have a GUI or path-completion where this gets used otherwise it'll be a pain in the rear.

Yes that is a very good point!

@yairm wrote:
> Perhaps the selection of the suffix should be a configuration option. That way, one could choose a suffix to his liking (I would personally prefer something like '.rclonelink')

Making it configurable would be easy enough.  I'd rather find a suffix everyone likes if possible :-)

**Comment by yairm** [comment]
@ncw I've pushed the updates to yairm:TranslateSymlinks - so you can have a look.

I had another look (debug prints, etc..:), and as far as I can tell, the root cause of the problem is in these lines of code (from `Copy()`)
```
        // We try to pass the original object if possible
	if src.Remote() != remote {
		wrappedSrc = &overrideRemoteObject{Object: src, remote: remote}
	}

```
In the case of `link` being transformed to `link.rclonelink`, src.Remote() returns `link.rclonelink` while 'remote' is the original `link` filename.
The code above, prefers the original name, as stated in the comment.

2/ Go question [a]
The Metadata for a link, can't be fully taken from  `lstat()`, since, the `Size` should be the size of the `.rclonelink` file containing the destination (and not the size that `lstat()` returned for the symlink itself).
However, `Object.SetMetadata(info os.FileInfo)` receives an immutable object, (which was returned from `os.lstat()`) 
The caller wants to 
```
    info, err = os.lstat(..)
    -- update info if needed --
    o.SetMetadata(info)
```
Subclassing os.Fileinfo seems a bit of an overkill, and passing an additional parameter to `SetMetadata` such as `size_override` seems unclean (I temporary did that)
If it were me, I'd just redefine SetMetadata, such that it doesn't receive an immutable object.. for example:
`func(o *Object) setMetadata(size int64, mode os.FileMode, modTime time.Time )`
Your input is appreciated :)

3/ Go question [b]
I've defined the `.rclonelink` constant in local.go, since that's where I think it belongs for the time being.
However, once the fuse change is implemented, where should the constant reside?

4/ Testing question
I ran the tests as written in 'Contributing' and many  of the tests failed on the `master` branch, probably, because I don't have the test remotes correctly set up. 
Can I use CI instead of setting up a test environment locally?

**Comment by ncw** [comment]
@yairm wrote:
> @ncw I've pushed the updates to yairm:TranslateSymlinks - so you can have a look.

Thanks. (https://github.com/yairm/rclone/commits/TranslateSymlinks)

> 1/
> I had another look (debug prints, etc..:), and as far as I can tell, the root cause of the problem is in these lines of code (from `Copy()`)
> 
> ```
>         // We try to pass the original object if possible
> 	if src.Remote() != remote {
> 		wrappedSrc = &overrideRemoteObject{Object: src, remote: remote}
> 	}
> ```
> In the case of `link` being transformed to `link.rclonelink`, src.Remote() returns `link.rclonelink` while 'remote' is the original `link` filename.
> The code above, prefers the original name, as stated in the comment.

Oh,I see what you mean... The user is typing in `link` on the command line, whereas rclone knows it as `link.rclonelink` everywhere else.

Hmm, not 100% sure what to do about that ...  Perhaps something like this which normalises the name of the file from the remote when copying a single file.  That is bound to have consequences I haven't thought of though!

```diff
diff --git a/fs/operations/operations.go b/fs/operations/operations.go
index 4ef8f4b7..62866aa1 100644
--- a/fs/operations/operations.go
+++ b/fs/operations/operations.go
@@ -1374,6 +1374,7 @@ func moveOrCopyFile(fdst fs.Fs, fsrc fs.Fs, dstFileName string, srcFileName stri
 	if err != nil {
 		return err
 	}
+	srcFileName = srcObj.Remote()
 
 	// Find dst object if it exists
 	dstObj, err := fdst.NewObject(dstFileName)
@@ -1381,6 +1382,8 @@ func moveOrCopyFile(fdst fs.Fs, fsrc fs.Fs, dstFileName string, srcFileName stri
 		dstObj = nil
 	} else if err != nil {
 		return err
+	} else {
+		dstFileName = dstObj.Remote()
 	}
 
 	if NeedTransfer(dstObj, srcObj) {
```

> 2/ Go question
> I've defined the `.rclonelink` constant in local.go, since that's where I think it belongs for the time being.
> However, once the fuse change is implemented, where should the constant reside?

It would go in `fs/fs.go` probably.

**Comment by yairm** [comment]
@ncw In your example above, shouldn't `dstFileName = dstObj.Remote()` happen _before_ the creation of the new object at `dstObj, err := fdst.NewObject(dstFileName)`?
The reason I think it should happen before, is that the creation of the desitnation object is when the new file is checked for existence.
I think we want to check if `link.rclonelink` exists, and not `link`. `link` will never exist (if -l is used) on the destination remote.

I think the reason the current code prefers the original name, is that a 'remote' might 'clean()' the name, in ways, that other remotes don't want to see. Am I right?

if so, we would be breaking functionality by modifying the name according to the source remote.

Thoughts..

**Comment by ncw** [comment]
> @ncw In your example above, shouldn't `dstFileName = dstObj.Remote()` happen _before_ the creation of the new object at `dstObj, err := fdst.NewObject(dstFileName)`?
> The reason I think it should happen before, is that the creation of the desitnation object is when the new file is checked for existence.
> I think we want to check if `link.rclonelink` exists, and not `link`. `link` will never exist (if -l is used) on the destination remote.

I think we need to think what we might expect from various commands.

So are we expecting all these to work?

    rclone copyto -l src/link dst/link
    rclone copyto -l src/link remote:link
    rclone copyto -l remote:link dst/link

I think not... the last one must surely be

    rclone copyto -l remote:link.rclonelink dst/link

which makes me think that this might be the best solution

    rclone copyto -l src/link.rclonelink dst/link.rclonelink
    rclone copyto -l src/link.rclonelink remote:link.rclonelink
    rclone copyto -l remote:link.rclonelink dst/link.rclonelink

And maybe this should give "error not found"

    rclone copyto -l src/link dst/link

?

This will be completely consistent then with `rclone ls -l` etc which will show the file names as `link.rclonelink` always.

> I think the reason the current code prefers the original name, is that a 'remote' might 'clean()' the name, in ways, that other remotes don't want to see. Am I right?

In general if backends clean the name, Remote() will still return the original name and internally will be the cleaned name.

**Comment by yairm** [comment]
1/ I've updated my fork according to your suggestion above.

This is what I understood :) :

`rclone copyto -l src/link.rclonelink dst/link.rclonelink`
Will copy a symlink called `src/link` to `dst/link` - The destination will also be a symlink, since the 'local' remote supports symbolic links.

`rclone copyto -l src/link remote:dst/`
Will return an 'error not found'. It would be nice if we could give a hint such as `The symbolic link 'src/link' can be referenced by src/link.rclonelink`, but not a blocker, imho.

rclone copyto -l remote:link dst/link
Will return 'error not found', obviously

`rclone copyto -l remote:link.rclonelink dst/link`
Both commands will create a symbolic link named `dst/link`

`rclone copyto -l remote:link.rclonelink dst/mynewlink`
Will create a symblic link named `dst/mynewlink`

------------------------------------------------------------------
2/ The tests all passed
    However, I didn't see where I can add tests with '-l', I'd be happy if you could direct me to the correct file.

3/ The manual needs updating as well - should I do it?

4/ I think I'm getting ready for a pull request, what is still left to do?

**Comment by ncw** [comment]
> 1/ I've updated my fork according to your suggestion above.
> 
> This is what I understood :) :
> 
> `rclone copyto -l src/link.rclonelink dst/link.rclonelink`
> Will copy a symlink called `src/link` to `dst/link` - The destination will also be a symlink, since the 'local' remote supports symbolic links.
> 
> `rclone copyto -l src/link remote:dst/`
> Will return an 'error not found'. It would be nice if we could give a hint such as `The symbolic link 'src/link' can be referenced by src/link.rclonelink`, but not a blocker, imho.
> 
> rclone copyto -l remote:link dst/link
> Will return 'error not found', obviously
> 
> `rclone copyto -l remote:link.rclonelink dst/link`
> Both commands will create a symbolic link named `dst/link`
> 
> `rclone copyto -l remote:link.rclonelink dst/mynewlink`
> Will create a symblic link named `dst/mynewlink`

I think that sounds OK.... Will need some experimenting with I think :-)

> 2/ The tests all passed
> However, I didn't see where I can add tests with '-l', I'd be happy if you could direct me to the correct file.

What you want to do is write some internal tests.  The local backend has its own framework for doing this at `backend/local/local_internal_test.go` so that is the thing to do (see `TestUpdatingCheck`).  I'm not sure what your experience with writing tests - let me know if you need help!
 
> 3/ The manual needs updating as well - should I do it?

Yes please.  `docs/content/local.md` is the place
 
> 4/ I think I'm getting ready for a pull request, what is still left to do?

code, docs, tests that is the PR trio!  I can't think of anything else - we can iterate the PR as necessary.  Looking forward to seeing it :-)

**Comment by yairm** [comment]
> What you want to do is write some internal tests. The local backend has its own framework for doing this at `backend/local/local_internal_test.go` so that is the thing to do (see `TestUpdatingCheck`). I'm not sure what your experience with writing tests - let me know if you need help!

I need help :)
`TestUpdatingCheck` seems to avoid creating a full `fs()` (I may be wrong)
I need a full fs() (I think!), since part of what I'm testing has to do with the `fs.List()` functionality.
Also, the `fs.NewObject()` flow should be tested with '.rclonelink' making sure that an `Object` is created that has the correct symlink configuration.

**Comment by archon810** [comment]
Restic can back up symlinks. How do they do it? https://restic.readthedocs.io/en/stable/040_backup.html?highlight=symlink.

> Backing up special items and metadata
> Symlinks are archived as symlinks, restic does not follow them. When you restore, you get the same symlink again, with the same link target and the same timestamps.

**Comment by splitice** [comment]
This looks very interesting. I know I'm interested in using this in a Plex setup.

Rough method:
1. I've patched sonarr to symlink instead of hardlink
2. another script goes solidifies the symlinks (up to 700GB per day)

Ensuring I don't exceed the 750GB Google Drive limit, and makes sonarr much more responsive (currently struggles during the move operation).

**Comment by ncw** [comment]
@yairm how are you doing with this?

**Comment by ncw** [comment]
> @ncw Sorry, I got preoccupied with other things.
> 
> I'm happy to complete the change, if it still has value for rclone.

Yes that would be great, or if you haven't got time someone else could pick it up.

**Comment by pilchat** [comment]
hi, i'm very interested in this too. thanks!

**Comment by yairm** [comment]
@ncw Status:  code changes to 'local.go' and updated the documentation to reflect it, works pretty well on my desk, however, I think I need help with writing tests.

Also, circleci failed with an build error, regarding 'strings.Builder', which apparently, was added in v1.10, and the CI is running v1.8.3. 
I used strings.Builder to construct a writerCloser.

**Comment by ncw** [comment]
> @ncw Status: code changes to 'local.go' and updated the documentation to reflect it, works pretty well on my desk, however, I think I need help with writing tests.

Great :-)

Happy to help with writing the tests.





> Also, circleci failed with a build error complaining about 'strings.Builder', that apparently was added in v1.10, while the CI is running v1.8.3.

I've just updated circleci to build with go1.11.1

However rclone supports go1.8 so you'll need to change that code not to use strings.Builder

How did you run the build - I don't see a pull request?

**Comment by yairm** [comment]
> > Also, circleci failed with a build error complaining about 'strings.Builder', that apparently was added in v1.10, while the CI is running v1.8.3.

I tried keeping with the current flow so that symlinks get their hash calculated, as any other file.
Defining a writerCloser seemed like the right thing to do (- Please note, I'm very new to Go).
Now, with changes upstream, (the new file type) this is becoming a bit more challenging.
Help appreciated :)

> How did you run the build - I don't see a pull request?
I ran it through logging in to circleCI - I've created a pull request.

**Comment by yairm** [comment]
@ncw Continuing the conversation re. pull request, on the pull request itself (I has a question regarding the rebase, please see the pull request)

**Comment by ncw** [comment]
Here is the first beta with the `-l` flag:

https://beta.rclone.org/branch/v1.45-113-g8c86a211-fix-1152-links-beta/ (uploaded in 15-30 mins)

**Comment by fancnsnyuedu** [comment]
Hi Nick,

Sorry, I missed how  --links  will address the symlink issue.
I don't mean how it was coded, just what it will do when
encountering a symlink.

Thanks,
Paul

**Comment by archon810** [comment]
So how does this work with destinations that don't natively support symlinks, like Box?

**Comment by hamiltont** [comment]
For folks asking how this was done, here's a sentence from the PR: 

```
If you supply this flag then rclone will copy symblic links from the local storage,
and store them as text files, with a '.rclonelink' suffix in the remote storage.
```

**Comment by nbzy1995** [comment]
this does not work in my case. can anyone help me?

I was trying to sync from my MacBook Pro (2021 M1) to an external hard drive. I run 
`rclone sync -vvl ~/Desktop /Volumes/WDExternalDrive/USER/Desktop`
and there is no errors. 

There are several alias in my 'Desktop' pointing to other files. But in the external drive, the alias become plain documents with no extension containing unrecognizable characters. And if I try to run `rclone sync -vvl` from the external drive to my laptop, the file is still a plain documents....

Anything wrong with my usage?

Thanks

**Comment by DurvalMenezes** [comment]
> this does not work in my case. can anyone help me?

The proper place for requesting help is [the rclone forum](https://forum.rclone.org/), to be more precise in the "Help and Support" category. Please post any follow-up questions there. 

> *snip* 
> Anything wrong with my usage?

AFAIK, the `-l` / `--links` option supports this functionality between a local and a remote file system, not between two local filesystems. But I might be wrong as I've not used that option myself yet.

**Comment by rulatir** [comment]
We absolutely need a "dumb" symlink copy feature, one that copies symlinks AS symlinks without caring what they point to. We need to be able to rclone from linux to linux (even local to local, except the source is really a sshfs mount, but it's "local" for all rclone can know) and have the destination directory in usable form without further processing (converting .rclonelink files to real symlinks).

**Comment by sdturne** [comment]
I wholeheartedly second this request.  I'm just learning about rclone and I'm both amazed and impressed about how powerful it is but also aghast that it doesn't support this simple behavior.  PLEASE, we just need an option to replicate symbolic links on the destination exactly as they exist in the source.  If the resulting links are dangling or broken, then so be it.

**Comment by sdturne** [comment]
@ncw I can see that the `--links` option does work when the source and destination are local directories.  However, `--links` does nothing when the source is a sftp remote; symbolic links to directories are simply followed and copied, creating a duplicate copy on the destination of the source directory to which they point.   Bug!

Not using any "links" related option behaves the same way, which is also a bug because it should detect symlinks on the source, complain that I'm not using `--copy-links`, then ignore them.

The only other option I can find that somewhat mitigates these behaviors is `--sftp-skip-links`, which simply ignores symlinks on the source (thus avoiding duplicate copies), but then I have no way of creating the links on the destination.  That option seems like a stop-gap that never got removed in favor of proper symlink support in the sftp back-end.

**Comment by yairm** [comment]
The implementation of --links was actually done on the 'local' backend (@ncw that is what you recommended I do).
While this was by-far the _easiest_ implementation, it was probably not the most _correct_ implementation, since other backends, such as sftp support symbolic links as well. 

So the 'bug!' that you encountered @sdturne, is actually an architectural issue.

I recall that while implementing "--links", I was wondering whether anyone will miss the more general solution and I guess that question has been answered by @sdturne et al :)

**Comment by ncw** [comment]
If you want to see `--links` on the sftp backend then this is the issue you want https://github.com/rclone/rclone/issues/5011

**Comment by musjj** [comment]
> this works fine for me

Wow, this took me a while to find. The documentation might have some room for improvements:

https://rclone.org/local/#local-links-links-l

> If you supply this flag then rclone will copy symbolic links from the local storage, and store them as text files, with a `.rclonelink` suffix in the remote storage.

It's not really wrong per-se, but kind of incomplete and a bit misleading. It should also describe what would happen in a local->local scenario.
