### ISSUE TITLE
Make --stats without -v show in output

### ISSUE THREAD

**Issue by Stonedestroyer** [ncw/rclone#1180]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    http://beta.rclone.org/
    http://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.35-146-g6bad0adβ
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 2016, 64 bits
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy D:\ secret:drive --transfers 14 --stats 5s
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Works on -vv and I see output but not normal.

Issue is I see no output and it is just blank but the command runs in background.

**Comment by ncw** [comment]
I've changed the defautls of rclone to be less verbose, like rsync.

So by default rclone won't output very much at all - only if stuff goes wrong.

With -v it will just show the transfers

With -vv it will show the full debug

**Comment by Stonedestroyer** [comment]
Thank you didn't know that, as I typed --stats 5s as I expect the stats to work. Is it possible to have when typing --stats timer, to make the stats show even without -v. It would be a great addition.

**Comment by doonze** [comment]
Hey Nick, can you turn it back on with --stats (default 60s) and --stats x acting accordingly? I understand some people might not like it, but I like to see it. So can it be an option? Please? Pretty please with sugar on top?? -v is too much, and -vv is far too much. I like the updates every 60 to see what kind of bandwidth I'm getting. Maybe even just an option to do like --stats-bw that outputs total bandwidth every x seconds????? I just like to see it's doing something!

**Comment by doonze** [comment]
OK, using it today, I gotta say the usefulness to me without stats is severely limited. I didn't realize how much to now. I have a total per month limit, and but being able to see how much I've sent is a major issue. More or less a deal breaker (not that I have any other real choices). But I'm gonna have to go back to an older version. 

The old stats were useful, so I knew if there was a big upload it was working on before I killed it, so I didn't lose hours of upload work, but I'd live with just total so far and average speed. Like rsync -info=progress2. I could live with that.

I get what you were trying to do, but give is options to have it the old way, or give us something better.  A display like the info=progress2 with what the threads are doing would be killer. And a -stats like rsync too, for our logs when using scripts!!!!! 

I was happy with the way it was, but if you want it to act more like rclone, give us some of the rclone monitoring. ;)

Please please pretty please?

**Comment by ncw** [comment]
@doonze I hear your impassioned plea!  I'll think about how I could make --stats appear without -v..

**Comment by doonze** [comment]
@ncw ok, I didn't realize -v still gave the stat window. I hadn't let it run long enough. So that's something! I can use that.... BUT!!!!! Here's something that I would like so see if you can figure out a way, you have all the info, so the only thing left is HOW. So currently we have this: 

**Transferred:**   42.317 MBytes (119.671 kBytes/s)
**Errors:**                 4
**Checks:**             28252
**Transferred:**          296
**Elapsed time:**        6m2s
**Transferring:**
 *  var/lib/dpkg/info/libssh-4:armhf.list: 100% done, 522 Bytes/s, ETA: 0s
 *  var/lib/dpkg/info/libssh-4:armhf.postrm: 100% done, 132 Bytes/s, ETA: 0s
 *  var/lib/dpkg/info/libssh-4:armhf.md5sums: 100% done, 425 Bytes/s, ETA: 0s
 *  var/lib/dpkg/info/libssh-4:armhf.postinst:  0% done, 0 Bytes/s, ETA: -
**Last Error:** List last error here.

I say print out this format as a static block if someone uses -stats, then update the stats in place (like --info=progress2 in rync). Adding the last error that was received at the bottom. Write off all errors to a file, then list them once the transfer is done. 

Then once the transfer is done, the last block of stats and the errors are written off to output for peoples logs that use them.

This way you can get an update on what's going on at a glance, but you don't have a scrolling wall of text both onscreen on in your logs.

Or does the new beta write a stats block when done anyway?

Ya know, something simple like that *insert guy hiding behind the wall emoji here*

**Comment by ncw** [comment]
@doonze wrote
> Or does the new beta write a stats block when done anyway?

should do yes.

I like the idea about the auto updating stats block - fancy making a different issue about that?  I'll use this one to track changing --stats to show without -v if possible.

**Comment by animosity22** [comment]
+1 for having --stats work without the -v. I like to be able to see the progress if I want to toggle it on but the -v adds too much extra info.

**Comment by balazer** [comment]
I'd also like to see stats work without -v.  For my use case, the only output I like to see is a single printing of the stats when the run finishes, summarizing the entire run.  That might even be a sensible default behavior.

**Comment by Valdaun** [comment]
+1 for --stats without -v!  I think that seems cleanest to let it be mostly silent by default, yet give those of us that relied on --stats output.   I personally used it to send to a log file and then email myself status updates a few times a day.  Knowing that it was always exactly 13 lines long (with 4 transfers) let things "just work".  But -v is way too verbose and fills my log with information I don't require.    It's also helpful to be able to test a command and see it's doing what you want, and getting the speed expected by letting --stats 10s run for a while.

**Comment by peterberbec** [comment]
I throw my approval behind both --stats without -v and @doonze 's idea of stealing rsync's info=progress2.

**Comment by jxer** [comment]
For those of you that want the functionality now without waiting for ncw. You can use the below to get the same old stat output as before

rclone copy -v --stats 5s /home/jxer/files Gdrive:/media |& grep -v 'INFO'

**Comment by ncw** [comment]
I've fixed this by adding a new flag, use `--stats-log-level NOTICE` to see the stats without using `-v`

https://beta.rclone.org/v1.36-219-gaa204864/ (uploaded in 15-30 mins)

**Comment by sparrowjack63** [comment]
Thank you very much ! 
I tested it and it works as expected :)
For S3 users, by adjusting the chunk size, we can now have better transfer rate (x2 for me). 
It would be great to integrate it into the stable version at the next step.

**Comment by qpwo** [comment]
Hey google when people search for "rclone stats 1s doesnt work" or "how to rclone stats single line" they should probably see this issue. I looked a few times over the last few months and you never showed me.

Thanks for fix @ncw ! Below command works for me.

`rclone sync --stats=5s --stats-one-line --stats-log-level=NOTICE ~/dir1/ ~/dir2/`
