### ISSUE TITLE
Problems uploading to Amazon Drive after uploading more than 7 TB

### ISSUE THREAD

**Issue by dvdzgz** [ncw/rclone#1203]
Running rclone v1.35-DEV on Linux servername 4.4.0-65-generic #86-Ubuntu SMP
 
I downloaded and compile the last branch after having the same problem with 1.35 release (didn't find the beta downloads until now :) 

go version go1.8 linux/amd64

I have been using rclone for more than one week syncing my NAS data to Amazon Cloud using a crypt remote on it. 

For one week I was able to upload the files. I had some problems and usually after several hours the process consume too much CPU, so I stopped and started again and everything works nice. I was able to upload more than 7 Tb, but since yesterday I realised that something is happening and now the files bigger than a few kbytes are not been uploaded correctly. rclone starts to upload the files, but when it finish the error exception is produced and after a pause, it starts to upload the file from the beginning. 

Are there any limitation on Amazon about how much can a user upload in a day/week? One day it looked like slowly, but then, few hours later the usual speed returns back  (up to  20.000 Mb, I have a 300 Mbit connection). 

The Log is huge and contains confidential information, so I will copy here the first lines and the lines after uploading the first file and failing.   I used the --bw option to see if it can help, but it didn't. 

2017/03/03 19:25:10 INFO  : Starting bandwidth limiter at 900kBytes/s
2017/03/03 19:25:10 DEBUG : rclone: Version "v1.35-DEV" starting with parameters ["rclone" "-vvvv" "--stats=10s" "--bwlimit" "900k" "--exclude" ".*" "--exclude" "Incoming" "sync" "/path" "SA2:/IX/path"]
2017/03/03 19:25:13 INFO  : Encrypted amazon drive root 'SA2/rmo72ep8i4d41bpvl221f1edbg/g3c5blekrm11uh0f63shhi9vt4': Modify window not supported
2017/03/03 19:25:13 DEBUG : amazon drive root 'SA2/rmo72ep8i4d41bpvl221f1edbg/g3c5blekrm11uh0f63shhi9vt4': Reading ""

2017/03/03 19:25:58 DEBUG : Scan/Scan_001487.pdf: Upload error detected but didn't finish upload: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" ("400 Bad Request")
2017/03/03 19:25:58 DEBUG : pacer: Rate limited, sleeping for 138.149956ms (1 consecutive low level retries)
2017/03/03 19:25:58 DEBUG : pacer: low level retry 1/1 (error HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}")
2017/03/03 19:25:58 DEBUG : Scan/Scan_001487.pdf: Received error: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" - low level retry 2/10
2017/03/03 19:25:58 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/03/03 19:25:58 DEBUG : other/Lynda - MS (MicroSoft) Project 2013 Essential Training/1. Working with Project/115433_01_02_SC11_backstage.mp4: Upload error detected but didn't finish upload: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" ("400 Bad Request")
2017/03/03 19:25:58 DEBUG : pacer: Rate limited, sleeping for 693.774911ms (1 consecutive low level retries)
2017/03/03 19:25:58 DEBUG : pacer: low level retry 1/1 (error HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}")
2017/03/03 19:25:58 DEBUG : file.ext: Received error: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" - low level retry 1/10
2017/03/03 19:25:58 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/03/03 19:25:58 DEBUG : Scan/Scan_001487.pdf: Upload error detected but didn't finish upload: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"d915181e-003e-11e7-9a8b-49ea9eea9982\",\"message\":\"Rate exceeded\",\"code\":\"\"}" ("429 Too Many Requests")
2017/03/03 19:25:58 DEBUG : pacer: Rate limited, sleeping for 183.515637ms (1 consecutive low level retries)
2017/03/03 19:25:58 DEBUG : pacer: low level retry 1/1 (error HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"d915181e-003e-11e7-9a8b-49ea9eea9982\",\"message\":\"Rate exceeded\",\"code\":\"\"}")
2017/03/03 19:25:59 DEBUG : Scan/Scan_001487.pdf: Received error: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"d915181e-003e-11e7-9a8b-49ea9eea9982\",\"message\":\"Rate exceeded\",\"code\":\"\"}" - low level retry 3/10
2017/03/03 19:25:59 DEBUG : pacer: Resetting sleep to minimum 20ms on success
  2017/03/03 19:26:03 INFO  :

**Comment by ThemeSurgeon** [comment]
I suspect your hitting the ceiling on workflow limits given your current allocated resources. Talk with your rep about provisioning for those kinds of data transfers. They may have a solution that can help prevent that.

**Comment by ncw** [comment]
I don't think this is an rclone problem.  It is possible you've hit some sort of quota and giving it a rest and trying again later might help.  Or it might just be ACD going through one of its unreliable phases.

**Comment by dvdzgz** [comment]
After the first phase of limit speed I though that I have reached a new limitation, I wait a full day without uploading, just trying and stop a couple of times to see if it was solved, two after days waiting it is still not working. Probably I will have to wait util the end of the week :)

Curious thing is that I tried to upload the same files was failing using the web and it works. Maybe they will have different quotas for each "channel". I will try to make a new OAUTH, maybe having a different auth token will give a new quota. 

Thanks for your help, and congratulations for the great tool.

**Comment by Powerbless** [comment]
i think i have the same problem. because rclone say me "object not found - waiting xxx/xxx)
after the wait time the upload begin from new...

is there a solution?

**Comment by madcatsu** [comment]
+1 on seeing the same issue with ACD. I'm also seeing files being rejected with error message `400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" ("400 Bad Request")`

This is followed by a random number of retry messages reporting "Object not found", after which the upload restarts the file transfer from scratch. This only appears to have come up recently. It seems now that all files fail to upload on first pass and then succeed on the 2nd attempt, effectively doubling the amount of data transferred.

**Comment by Powerbless** [comment]
+100 the problem is NOT solved.

for troubleshooting:
-Did you upload/download with 2 different IP´s? (home computer and Root server)
-did you use the move command?

i have found that when i refresh manualy the token, it works for 2-3 hours but the the error comes back

here my error-log:
`2017/03/23 08:43:40 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (138/146)
2017/03/23 08:43:46 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (139/146)
2017/03/23 08:43:51 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (140/146)
2017/03/23 08:43:56 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (141/146)
2017/03/23 08:44:01 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (142/146)
2017/03/23 08:44:06 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (143/146)
2017/03/23 08:44:11 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (144/146)
2017/03/23 08:44:16 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (145/146)
2017/03/23 08:44:22 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (146/146)
2017/03/23 08:44:27 DEBUG : pathtocontent\S01E01.mkv: Giving up waiting for object - returning original error: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" ("400 Bad Request")
2017/03/23 08:44:27 DEBUG : pacer: Rate limited, sleeping for 884.491574ms (1 consecutive low level retries)
2017/03/23 08:44:27 DEBUG : pacer: low level retry 1/1 (error HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}")
2017/03/23 08:44:27 DEBUG : pathtocontent\S01E01.mkv: Received error: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" - low level retry 2/10
2017/03/23 08:44:27 DEBUG : pacer: Resetting sleep to minimum 20ms on success`

**Comment by dvdzgz** [comment]
I suspected from the beginning that the problems was related to some kind of limit that I have reached (I was doing a full backup of several TB), so I decided to wait for a while before keep trying. Today I have checked (after 21 days) and it is working again.

Probably in your case it is happening the same, so you will have to be patients for a while before try again.

**Comment by dvdzgz** [comment]
NEW UPDATE. I am gonna re-open the case. 


I found that the problem is not related to ACD. Today it worked because I was syncing a different folder. When I tried the affected folder I had exactly the same problems. This folder is a remote samba mounted on a Linux Machine and shared from HOME NAS , so I tried directly from the NAS server using the ARM version and it worked. 

I am having some issues with this Samba export, because I had a problem trying to save a file on it due to the file name length was longer that 31 chars :S
