### ISSUE TITLE
[Feature Request] OpenDirectIO

### ISSUE THREAD

**Issue by jaketame** [ncw/rclone#1214]
This is a feature request to test / implement OpenDirectIO, which may have a performance improvement for read/writes as it bypasses the kernel caching.

Some test samples can be found here: https://github.com/jmmv/bazil-fuse/blob/master/fs/serve_test.go

**Comment by trapexit** [comment]
It's unlikely to lead to any performance increases given the slowness is not the local caching (which in fact would help subsequent reads) but the network. Doesn't mean it couldn't be a useful option to reduce caching on readonce use cases.

**Comment by ncw** [comment]
I'm unclear exactly what OpenDirectIO does for fuse - can you find some docs?  I don't know whether it has the same limitations as O_DIRECT for instance.

It would be relatively easy to implement as an option -just another flag for Open.

**Comment by trapexit** [comment]
It's similar. The documentation from the FUSE project is not too descriptive but in effect it limits the caching by the kernel. I describe it a bit better in the mergerfs docs.

As I mention above though... unless rclone is caching data itself it seems unlikely that enabling this would actually lead to any performance increases. The opposite is more likely. In mergerfs' case it makes sense to enable since otherwise the kernel will cache the original copy of the file and the version passed through by mergerfs.
