### ISSUE TITLE
Amazon Cloud Drive and rclone problem

### ISSUE THREAD

**Issue by GoneD** [ncw/rclone#1353]
Hi,

I have a problem with rclone and Amazon Cloud Drive

> What is your rclone version (eg output from `rclone -V`)

rclone v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian 8.7 x64

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

I use rclone copy and just rclone lsd for verify is working

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

The problem is, when i use rclone lsd, it's take very long time before return the result.

The problem has just happened, since 1 week everything worked normally I managed to copy to Amazon 4.2 To but now nothing works and I do not understand why.

When I run rclone copy, it tries to make a check that takes time.

I do not understand why it's so long ....

##LOG for rclone lsd
017/04/19 07:57:34 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "-vv" "lsd" "folderdir:"]
2017/04/19 07:57:34 DEBUG : pacer: Rate limited, sleeping for 666.145821ms (1 consecutive low level retries)
2017/04/19 07:57:34 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:34 DEBUG : pacer: Rate limited, sleeping for 235.010051ms (2 consecutive low level retries)
2017/04/19 07:57:34 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:35 DEBUG : pacer: Rate limited, sleeping for 287.113937ms (3 consecutive low level retries)
2017/04/19 07:57:35 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:35 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/19 07:57:35 DEBUG : pacer: Rate limited, sleeping for 331.776148ms (1 consecutive low level retries)
2017/04/19 07:57:35 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:36 DEBUG : pacer: Rate limited, sleeping for 1.183117216s (2 consecutive low level retries)
2017/04/19 07:57:36 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:36 DEBUG : pacer: Rate limited, sleeping for 480.279449ms (3 consecutive low level retries)
2017/04/19 07:57:36 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:37 DEBUG : pacer: Rate limited, sleeping for 6.760398084s (4 consecutive low level retries)
2017/04/19 07:57:37 DEBUG : pacer: low level retry 4/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:38 DEBUG : pacer: Rate limited, sleeping for 263.669287ms (5 consecutive low level retries)
2017/04/19 07:57:38 DEBUG : pacer: low level retry 5/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:44 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/19 07:57:45 DEBUG : pacer: Rate limited, sleeping for 884.491574ms (1 consecutive low level retries)
2017/04/19 07:57:45 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:45 DEBUG : pacer: Rate limited, sleeping for 1.414458836s (2 consecutive low level retries)
2017/04/19 07:57:45 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:45 DEBUG : pacer: Rate limited, sleeping for 3.211445515s (3 consecutive low level retries)
2017/04/19 07:57:45 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:47 DEBUG : pacer: Rate limited, sleeping for 3.838182873s (4 consecutive low level retries)
2017/04/19 07:57:47 DEBUG : pacer: low level retry 4/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:50 DEBUG : pacer: Rate limited, sleeping for 11.472644968s (5 consecutive low level retries)
2017/04/19 07:57:50 DEBUG : pacer: low level retry 5/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:57:54 DEBUG : pacer: Rate limited, sleeping for 18.910584091s (6 consecutive low level retries)
2017/04/19 07:57:54 DEBUG : pacer: low level retry 6/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:58:05 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/19 07:58:05 DEBUG : pacer: Rate limited, sleeping for 539.11079ms (1 consecutive low level retries)
2017/04/19 07:58:05 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:58:05 DEBUG : pacer: Rate limited, sleeping for 1.853353331s (2 consecutive low level retries)
2017/04/19 07:58:05 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:58:06 DEBUG : pacer: Rate limited, sleeping for 324.778273ms (3 consecutive low level retries)
2017/04/19 07:58:06 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:58:08 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/19 07:58:08 DEBUG : pacer: Rate limited, sleeping for 138.149956ms (1 consecutive low level retries)
2017/04/19 07:58:08 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:58:08 DEBUG : pacer: Rate limited, sleeping for 693.774911ms (2 consecutive low level retries)
2017/04/19 07:58:08 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:58:08 DEBUG : pacer: Rate limited, sleeping for 2.183515637s (3 consecutive low level retries)
2017/04/19 07:58:08 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 07:58:09 DEBUG : pacer: Rate limited, sleeping for 6.821866378s (4 consecutive low level retries)

**Comment by Seimann** [comment]
I have the same problem since last night...
Tested on Ubuntu 16.04.2 x64 and Windows 7 x64 and rClone v1.36
No command works anymore
rclone ls / size / mount / copy / sync .....
Windows 7 tested also with rclone.exe
Every action print the message:
`root@ubuntu:~# rclone ls -vv acd:/Mediathek
2017/04/19 14:01:46 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "ls" "-vv" "acd:/Mediathek"]
2017/04/19 14:01:47 DEBUG : pacer: Rate limited, sleeping for 287.113937ms (1 consecutive low level retries)
2017/04/19 14:01:47 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:01:47 DEBUG : pacer: Rate limited, sleeping for 549.16732ms (2 consecutive low level retries)
2017/04/19 14:01:47 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:01:47 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/19 14:01:47 DEBUG : pacer: Rate limited, sleeping for 632.969758ms (1 consecutive low level retries)
2017/04/19 14:01:47 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:01:48 DEBUG : pacer: Rate limited, sleeping for 1.331776148s (2 consecutive low level retries)
2017/04/19 14:01:48 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:01:48 DEBUG : pacer: Rate limited, sleeping for 1.183117216s (3 consecutive low level retries)
2017/04/19 14:01:48 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:01:49 DEBUG : pacer: Rate limited, sleeping for 480.279449ms (4 consecutive low level retries)
2017/04/19 14:01:49 DEBUG : pacer: low level retry 4/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:01:51 DEBUG : pacer: Rate limited, sleeping for 6.760398084s (5 consecutive low level retries)
2017/04/19 14:01:51 DEBUG : pacer: low level retry 5/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:01:51 DEBUG : pacer: Rate limited, sleeping for 263.669287ms (6 consecutive low level retries)
2017/04/19 14:01:51 DEBUG : pacer: low level retry 6/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:01:58 DEBUG : pacer: Rate limited, sleeping for 18.884491574s (7 consecutive low level retries)
2017/04/19 14:01:58 DEBUG : pacer: low level retry 7/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:01:58 DEBUG : pacer: Rate limited, sleeping for 27.414458836s (8 consecutive low level retries)
2017/04/19 14:01:58 DEBUG : pacer: low level retry 8/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:02:17 DEBUG : pacer: Rate limited, sleeping for 1m43.211445515s (9 consecutive low level retries)
2017/04/19 14:02:17 DEBUG : pacer: low level retry 9/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:02:44 DEBUG : pacer: Rate limited, sleeping for 11.838182873s (10 consecutive low level retries)
2017/04/19 14:02:44 DEBUG : pacer: low level retry 10/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:04:28 DEBUG : pacer: Rate limited, sleeping for 4m2.53911079s (11 consecutive low level retries)
2017/04/19 14:04:28 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:04:40 DEBUG : pacer: Rate limited, sleeping for 2m25.853353331s (12 consecutive low level retries)
2017/04/19 14:04:40 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/19 14:08:42 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/19 14:08:42 Failed to create file system for "acd:/Mediathek": Node 'Mediathek' is not a file`

But it works fine last night / days, no restart this night and i installed acd_cli now and all works normal on acd_cli ?? :(
What can i do? Where is the problem?

**Comment by GoneD** [comment]
Same thing for me, works fine last night / days....

**Comment by Seimann** [comment]
Now i tested also v1.36-22 on VMware Ubuntu 16.04 and it does not work anymore
GSuite Google Drive works normal

**Comment by Seimann** [comment]
@GoneD where are you from? Do you have a europe Amazon account? 
Strange that it happens at the same time... and also strange is the rclone v1.36 worked last days and the account is not locked (acd_cli test)
Maybe a temporary problem from ACD...

**Comment by GoneD** [comment]
I have try with acd_cli and is working well,
I'm from Canada

**Comment by Enf0** [comment]
Same issue here. Amazon.com account.

**Comment by jheyneman** [comment]
https://forum.rclone.org/t/acd-429-too-many-requests/1792

**Comment by GoneD** [comment]
Thanks, so it's Amazon issue....

**Comment by jamesdb** [comment]
Amazon UK and rate limited here too.

**Comment by GoneD** [comment]
Amazon have resolve the issue, it's working good right now :D
