### ISSUE TITLE
SFTP only works with --transfers=1

### ISSUE THREAD

**Issue by qchusc** [ncw/rclone#1381]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
SMP Debian 3.16.39-1+deb8u2 (2017-03-07)
> Which cloud storage system are you using? (eg Google Drive)
SFTP
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy XX_SFTP:/ GS_XX:XX --include=XX* -vv --size-only --transfers=2
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2017/05/01 17:13:48 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "copy" "XX_SFTP:/ XX:XX" "GS_XX:XX" "--include=XX*" "-vv" "--size-only" "--transfers=2"]
2017/05/01 17:13:58 INFO  : Storage bucket XX path XX: Modify window is 1s
2017/05/01 17:13:58 DEBUG : YYFILE: Excluded from sync (and deletion)
2017/05/01 17:13:58 DEBUG : XXFILE: Sizes identical
2017/05/01 17:13:58 DEBUG : XXFILE: Unchanged skipping
2017/05/01 17:13:58 ERROR : XXFILE2: Failed to copy: failed to open source object: Open failed: sftp: "The requested operation cannot be performed because there is a file transfer in progress." (SSH_FX_PERMISSION_DENIED)

Only 1 transfer can be done successful. when "--transfers=1" everything works fine. I can transfer multiple files from/to that same SFTP using lftp. What is the logical difference here? rclone is not opening multiple connections? Maybe?

Thanks for all the help!

**Comment by ncw** [comment]
rclone does multiple transfers within the same ssh connection which is part of the sftp spec.

Which sftp server are you using?  This isn't a problem with any SFTP servers I've tried so far.

It might be that rclone needs to adapt to the server somehow...

**Comment by cookie223** [comment]
Yeah it seems to be the case. I have no full access to the sftp server though so I don't know what's going on.

Is there a simple fix to open multiple ssh connections? I just checked lftp does that.

**Comment by ncw** [comment]
I need to either know which sftp server it is, or have access to it for a bit to make progress with this!

**Comment by sjurtf** [comment]
Multiple ssh connections (like the Filezilla client does) would solve this problem, and some others related to rate limiting and TCP + latency issues.

This is a problem related to the sftp client rclone uses. @ncw has an open issue for this in the stfp go client git. (https://github.com/pkg/sftp/issues/158). 

I haven't looked at the code, but it might be a significant rewrite to support transfers over multiple connections, but since they have not yet closed the issue they might be open for it.

**Comment by ncw** [comment]
@sjurtf wrote
> Multiple ssh connections (like the Filezilla client does) would solve this problem, and some others related to rate limiting and TCP + latency issues.

So one ssh connection per transfer? Seems inefficient as the ssh handshake is quite expensive.  BTW How do you know the Filezilla client does this?

ssh is a transport which can have multiple streams within it.  By default rclone will do `--transfers` streams simultaneously within the ssh transport.  This works extremely well with the ssh servers I've tried, but obviously not with the server that is the subject of this ticket!

> This is a problem related to the sftp client rclone uses

I would say it is a problem with the server not accepting multiple transfers down the same ssh connection like it is supposed to.  As I said, there may be some adaption rclone should be doing though which it isn't at the moment.

> has an open issue for this in the stfp go client git. (pkg/sftp#158).

That issue is to do with speed of transfers and is related to rclone issue #1158 - it might well be that opening multiple ssh connections would fix that issue.

> I haven't looked at the code, but it might be a significant rewrite to support transfers over multiple connections, but since they have not yet closed the issue they might be open for it.

The place to do that would be in rclone I think.  rclone could have a pool of opened ssh connections it could use - it wouldn't be too tricky.

**Comment by sjurtf** [comment]
> So one ssh connection per transfer? Seems inefficient as the ssh handshake is quite expensive. 
BTW How do you know the Filezilla client does this?

I agree it is inefficient from a protocol aspect when one session is enough to support multiple transfers. But in real life scenarios with a large number of files and with one session not managing to fill the network pipe due to rate-limiting or TCP slowness due to latency it is in my opinion that the extra handshakes are worth it.

I know since I've been using the FileZilla client for some time. The `Maximum simultaneous transfers` setting under the transfer tab in preferences lets the user change how many connections to be used.

Each of these connections is spawning a new `sshd` process on the server with a new TCP port.
From the `auth.log` I can also see that my user was authenticated the same number of times as the `Maximum simultaneous transfers` variable inside FileZilla. When one of the transfers are done, the next file to be transferred acquires the free connection.

>I would say it is a problem with the server not accepting multiple transfers down the same ssh connection like it is supposed to.

I agree, for this particular issue, it seems like OP is using a sftp server not following specifications.

>The place to do that would be in rclone I think. rclone could have a pool of opened ssh connections it could use - it wouldn't be too tricky.

This seems like a good solution to the speed of transfer issue and would solve this issue as well. :)

**Comment by sjurtf** [comment]
This also might be fixed when #1561 is done.

**Comment by ncw** [comment]
This implements connection pooling for multiple ssh connections
    
    A connection may be opened for each `--transfers` and `--checkers`
    now.  Connections are checked when putting them in the pool and
    getting them out the pool so it should recover from network errors
    much better.

https://beta.rclone.org/v1.37-076-g5b6585f5/ (uploaded in 15-30 mins)

Please test and reopen the issue if you are still having a problem, or make a new issue with more info.

Thanks
