### ISSUE TITLE
B2 Storage - Time may be set wrong - Different Timezones

### ISSUE THREAD

**Issue by Flash619** [ncw/rclone#1392]
**RClone Version:** RClone v1.3.6
**OS Version:** FreeBSD 11.0-RELEASE
**Target Storage Platform:** Backblaze B2
**Command Used:** ./rclone sync /localdir/ cryptremote: --bwlimit 5000 --transfers 32

When I run the above command I get this:

> $ ./rclone sync /iocage/ b2-nas-tank-iocage-crypt: --bwlimit 5000 --transfers 32
> 2017/05/05 14:33:08 NOTICE: Time may be set wrong - time from "api.backblazeb2.com" is 4h59m41.895202442s different from this computer
> 2017/05/05 14:33:09 NOTICE: Time may be set wrong - time from "api001.backblazeb2.com" is 4h59m42.430773816s different from this computer

My timezone is CDT and Backblaze B2 is in California. I'm assuming this is what is causing this issue. Further down the log it eventually will print:

> 2017/05/05 14:40:16 NOTICE: Time may be set wrong - time from "pod-000-1029-14.backblaze.com" is 4h59m42.203894535s different from this computer
> 2017/05/05 14:40:16 NOTICE: Time may be set wrong - time from "pod-000-1001-06.backblaze.com" is 4h59m42.297726763s different from this computer
> 2017/05/05 14:40:16 NOTICE: Time may be set wrong - time from "pod-000-1033-01.backblaze.com" is 4h59m41.3710444s different from this computer

Output of the date command on my server is:

> Fri May  5 14:40:02 CDT 2017

Is there a way to set a time offsite or a way to add timezone compatibility when syncing to different time zones?

**Comment by ncw** [comment]
Firstly note that those are only warnings - likely things will still work.

This is the first report of this problem I've seen.

If your clock is badly out then the oauth protocol doesn't work very well.  I can't remember how long b2's initial grant is, but if it is 24hr then you won't notice until 24-5 hours time....

So firstly, is the time correct on your computer?  rclone is suggesting it is ~5h out.  Likely this is a timezone thing, so is the timezone set correctly on your computer?

The other explanation would be that FreeBSD treats timezones somehow differently.

What happens if you try setting your time from a remote server with rdate? (or ntp?)

**Comment by Flash619** [comment]
Local Time: CDT - May 6th - 9:20AM - 2017
Server Time: CDT - May 6th -  14:20:56 -  2017

It seems the server is a ways ahead for whatever reason. I'll try implementing NTP and go from there to see if it corrects this issue.

**Comment by Flash619** [comment]
After enabling ntpd and ntpdate on the FreeBSD installation in question, it was shown that ntp corrected an offset of -17980 seconds. This seems to have resolved this issue.

**Comment by ncw** [comment]
Well done for tracking it down and thanks for reporting back.

**Comment by sitemoods** [comment]
Would it be possible to Rclone mimic the server time, to make sure oath succeeds, even if the machine is in 1970 ?

**Comment by RhvsW** [comment]
No, because that's stupid.
