### ISSUE TITLE
Add option to disable unicode normalization

### ISSUE THREAD

**Issue by bpot** [ncw/rclone#1411]
It looks like the current behavior is to always normalize filenames and directories before storing objects in a storage systems. It sounds like this normalization is necessary in many (most?) cases.

However, this means that if a file is not in a normalized form its name will be different after a round-trip through a storage system. This can cause issues if you expect filenames to be match byte-for-byte.

Would it be possible to add a new flag (e.g. `--no-unicode-normalization`) to disable normalization?    I imagine the flag would cause issues in some situations but in others it seems like it would allow you to retain the original filenames. For example, if you are using a `crypt` remote (w/encrypted filenames) and a filesystem that stores filenames as a sequence bytes it seems like you could get away without normalization.

Are there other issues with skipping normalization that I'm not aware of?

**Comment by ncw** [comment]
What problem are you trying to solve?  And on which OS? I'm guessing OS X...

The normalization was added because OS X stores its file names an unormalized UTF-8 for some reason.  It probably isn't necessary for Windows / Linux.

I'm not sure whether the cloud providers store unnormalized UTF-8 - I know some do (eg S3/ACD) but I imagined when I put that feature in that some might not.

I think a flag to selectively disable is a good idea - it would work well when syncing to crypt.

This would need to be a flag in `local/local.go` in the `cleanRemote` function to stop the `	name = norm.NFC.String(name)` line running.

The flag should then be called `--local-no-unicode-normalization` or maybe `--local-no-unicode-nfc`.

Fancy having a go?

**Comment by bpot** [comment]
I'm actually seeing the problem under linux. I'm using an application which sometimes writes filenames with unnormalized utf8. I'm using rclone to store those files and ultimately replicate them to a different server. Once they get to the remote server the filenames are normalized and the application can't find them.

I should be able to put together a PR soon.

**Comment by ncw** [comment]
This should be built into

https://beta.rclone.org/v1.36-122-gbe5b8b8d/ (in 15-30 mins)
