### ISSUE TITLE
--bwlimit ignored for chunked uploads on b2 & drive (& others?)

### ISSUE THREAD

**Issue by xcjs** [ncw/rclone#1443]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04 x64

> Which cloud storage system are you using? (eg Google Drive)

Backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync -vv --bwlimit 350k --transfers 1 /path/to/files b2-crypt-remote:

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Transferred:   272.562 MBytes (258.207 kBytes/s)
Errors:                 0
Checks:               101
Transferred:            0
Elapsed time:     18m0.9s
Transferring:
 * ...large-file.ext:  1% done, 350.138 kBytes/s, ETA: 13h20m28s

2017/05/25 10:22:16 DEBUG : 405bo5jvqamhb26j3onqq0jj4k/io7s5pcc5bhbe7ag1dk09s5hpk/qt3tqkjokrm354a7vj755norv49hcb9215qe0o4jogsnbes50i2g/c52hpqov41uq2aehm0jg9tjm2pchh0bmfeia7bsgbg5lj7ppj8gg: Sending chunk 3 length 100663296
2017/05/25 10:22:16 DEBUG : 405bo5jvqamhb26j3onqq0jj4k/io7s5pcc5bhbe7ag1dk09s5hpk/qt3tqkjokrm354a7vj755norv49hcb9215qe0o4jogsnbes50i2g/c52hpqov41uq2aehm0jg9tjm2pchh0bmfeia7bsgbg5lj7ppj8gg: Didn't find object to account part transfer

Even though rclone says it's only using ~350k, several other bandwidth monitoring utilities show that it's maxing out my upload speed, harming connectivity for other devices and services on my network. (350k is roughly half my upload speed which worked fine with Amazon Cloud Drive)

It's also possible that it matches the bandwidth limit flag at some times, but not at others which may explain the discrepancy in the log. I tried to find an excerpt around the time I noticed issues,

**Comment by xcjs** [comment]
Update: This seems especially present with chunked file uploads.

**Comment by xcjs** [comment]
Sorry for spamming this issue, but is it related to #222?

**Comment by ncw** [comment]
Hmm, chunked files.

Can you paste a log with `-vv` of uploading a chunked file that you think might have a problem?

Are there retries involved?

Can you check with the latest beta that this is still a problem?

**Comment by xcjs** [comment]
@ncw Sure, please allow me a few days to experiment a little.

**Comment by ncw** [comment]
Your explanation sounds correct looking at the code.

Which means on average the transfer rate will be what you set, however it will burst to very high while it is sending the chunks.

I agree this isn't ideal especially since B2 chunks are 100MB.

I could put the bandwidth limit on the other side of the buffer, but then that will have the opposite problem if you are copying from a network remote to B2.

Having a bandwidth limiter on both sides of the buffer would work, but that will limit the bandwidth too much since both limiters will be taking from the same pool.

Perhaps two limiters at twice the bandwidth...

I'm sure there is a simple solution, it just hasn't come to me yet!

**Comment by xcjs** [comment]
It sounds like this would be a good argument for two pools - perhaps --read-bw-limit and --write-bw-limit? --src-bw-limit and --dest-bw-limit?

**Comment by xcjs** [comment]
Also, at least in my case I'm reading from a local filesystem. Would it make sense to move the bandwidth limiter on the opposite side of the buffer when the source is a local filesystem and the destination a remote?

**Comment by ncw** [comment]
Two pools is the conclusion I came to as well. I'd set them both to bwlimit. I like your idea of bypassing them for local  disk read or write.

I'll have a play with some of those ideas.

**Comment by xcjs** [comment]
Awesome! Thank you for looking into this - I really appreciate it.

**Comment by SirCrest** [comment]
Experiencing similar behavior with Google Drive. With the limiter, the average speed is set to the limiter, but I suppose each chunk runs full speed and then waits again. This causes occasional stutters in streams I'm watching.  Turning off the bandwidth limiter in general doesn't affect the max speed, just removes those pauses. On 1.36 and I experience this on Windows 10 Pro x64 and Windows Server 2016 if that matters.

![2017-05-30 17_16_52-2017-05-30 11_41_24-task manager png - photos](https://cloud.githubusercontent.com/assets/29075734/26606490/1ca426a8-4560-11e7-870c-99005d81fe02.png)
![2017-05-30 17_16_25-2017-05-30 17_02_05-task manager png - photos](https://cloud.githubusercontent.com/assets/29075734/26606491/1ca5a212-4560-11e7-880f-a3f13244cbde.png)

**Comment by ncw** [comment]
@SirCrest this is likely the same issue... I'll update the title of this issue accordingly!

**Comment by felixbuenemann** [comment]
I noticed that with drive the `--bwlimit` does not work well with slow uplinks (eg. 5 MBps) unless you also lower the chunk size. For example on a 5 MBps link I used a chunk size of 256 KB instead of the default 8 MB. After lowering the chunk size, rclone was staying very close to the 350 KByte/s bwlimit I had set, while it undershot a lot with the default chunk size.

I haven't had to use bwlimit since upgrading my upstream to 40 MBps and using QoS on my router, so I don't know if the above observation still applies to current rclone versions (I think it must have been on v1.32-v1.34).

**Comment by xcjs** [comment]
@felixbuenemann This is potentially very helpful. Thanks!

**Comment by psychoflame** [comment]
I'm also seeing some weird behavior with --bwlimit and --chunk-size and i'm unsure if this is normal or not. I have a limit of 2 transfer set on box and when it's uploading with 2 items at a chunk limit of 8M, it works fine, saturates all the way up to my --bwlimit of 2.3M. However when i have only 1 item transfer at a chunk size of just 8M it seems to struggle to get a transfer speed of 1.2M. If i try increasing the chunk size, up to 128M or 256M, it seems to work peaks above my --bwlimit sometimes, but once it appears to upload that chunk, the speeds drop to basically 64K for 2 to 3 minutes then they pick back up to the --bwlimit, then once that chunk is done uploading rinse and repeat as described aboved. I'm unsure if that's a consequence of using --chunk flag but i didn't see this issue when i used a vps with large chunk sizes without the --bwlimit flag.

**Comment by breunigs** [comment]
I am pretty sure the issue for Google Drive will be fixed with #970, #968. You can try the beta here:
https://www.breunig.xyz/share/rclone-beta/v1.36-232-gb2b5c629-drive-accounting%CE%B2/

consistent upload speed with patch:
![2017-07-02-104805_1920x1080_scrot](https://user-images.githubusercontent.com/307954/27768491-42dfa166-5f15-11e7-9fb7-41ab86206f4f.png)

full speed / pause pattern without patch:
![2017-07-02-105509_1920x1080_scrot](https://user-images.githubusercontent.com/307954/27768490-42decc0a-5f15-11e7-9621-ebc3128ca3a3.png)

**Comment by breunigs** [comment]
@ncw I am late to the party here, but it seems worthwhile to revisit 037a000cc81e87c7e77f4572a87e979bcac31913 and try the OneDrive approach from #1317 as well. I don't know the B2 code, but I can take a stab at it after the Google Drive patch lands.

**Comment by psychoflame** [comment]
That patch, fixed all the problems that i was having. --chunks with drive work correctly now with the --bwlimit on, don't see performance drops anymore. Thanks breunigs

**Comment by breunigs** [comment]
So, I've struggled with this for a while and seem to have hit a dead end. In order to implement a similar solution to the one in Drive, I believe three parts are needed:
1. stream the B2 chunk uploads – easy, because they allow appending the hash at the end instead of the headers
2. read ("download") and write ("upload") independently – tougher, because rclone can upload multiple chunks of one file at the same time (from #531). Since the input reader is sequential only, we need to finish reading a chunk before continuing. `fs.asyncReader` works for this purpose and essentially streams on both ends.
3. Report accurate numbers to the accounting layer – this is where I am stuck. `asyncReader` works akin to setting the chunk size to 1 MB, which gives me a saw tooth pattern. On the upside this allows setting a bigger B2 chunk size without affecting bwlimit too much, but I wouldn't consider this "good" or "done".

Without making `asyncReader` behave perfectly like a pipe (i.e. 1 byte buffers, or at least anything small enough so it doesn't matter for the chosen bwlimit), the reporting needs to be adjusted. I guess this would then be the "two bandwidth pools" idea suggested above. That might also fix the inaccurate speed reports on non-bwlimited uploads and probably make the approach I just described obsolete.

**Comment by ncw** [comment]
I have fixed this in d0d6b83a7a9837dcd21b397bf76e2a641d127c5f which allows the backends to take the accounting/limiting off the incoming stream and place it back on the output of the buffers.

In my tests with b2 multipart uploads this smooths the bandwidth very well.

The drive and onedrive uploads have been fixed already.

I also fixed a similar issue in box and azureblob (which no-one had reported yet!)

One of the problems the old system had is that it didn't work with crypt... This new one does!

https://beta.rclone.org/v1.39-120-g82418c30/ (uploaded in 15-30 mins)
