### ISSUE TITLE
Remove website documentation relating to Amazon Cloud Drive

### ISSUE THREAD

**Issue by marvinpinto** [ncw/rclone#1468]
I propose that the Amazon Cloud Drive (ACD) documentation be removed from the website so that new folks don't mistakenly assume that rclone works with ACD.

For reference, it appears Amazon [recently banned rclone][1] from using the ACD API and there does not appear to be any going back. More info also available in #1409.

[1]: https://forum.rclone.org/t/rclone-has-been-banned-from-amazon-drive/2314

**Comment by MeltedLux** [comment]
rclone works with acd.

**Comment by sjurtf** [comment]
Rclone does still work with ACD if you have the necessary developer credentials. The documentation should still be updated to reflect the prerequisites that are needed use Rclone with ACD at this time, and that Amazon is no longer giving out new developer credentials.

For the majority of users, it doesn't look like Rclone will work with ACD anytime soon.

**Comment by ncw** [comment]
What needs to be done is make the acd remote fail unless you have put in custom credentials and put a note in the docs about that.

**Comment by ajkis** [comment]
> What needs to be done is make the acd remote fail unless you have put in custom credentials and put a note in the docs about that.

Zenjaba have the credentials for you @ncw if you are willing to setup auth server so ACD would work again.

**Comment by calisro** [comment]
> Zenjaba have the credentials for you @ncw if you are willing to setup auth server so ACD would work again.
Wouldn't it just get banned again just like what happened with acdcli again?  I can certainly see rclone continuing with ACD for people that have their own credentials because of the low API hits but as soon as a auth server is officially put up, I just see it getting banned again.

**Comment by ajkis** [comment]
> Wouldn't it just get banned again just like what happened with acdcli again? I can certainly see rclone continuing to work with ACD for people that have their own credentials because of the low API hits but as soon as a auth server is officially put up, I just see it getting banned again.

Based on Amazon email, the credentials in open source software cant be publicly exposed, not sure what happened with acd_cli but the used unsecured auth server before that exposed files to different users. 

p.s. You may be right but since rclone is trying to support as many clouds as possible it would be a shame to let acd completely die out, especially since auth server is something that all other apps working with acd do.

**Comment by vampywiz17** [comment]
> What needs to be done is make the acd remote fail unless you have put in custom credentials and put a note in the docs about that.

Thats right. some of ones use ACD. Only need to change the doc, that need own oauth. Not need to delete all documentation and acd support.

**Comment by ncw** [comment]
> > Zenjaba have the credentials for you @ncw if you are willing to setup auth server so ACD would work again.
> 
> Wouldn't it just get banned again just like what happened with acdcli again?  I can certainly see rclone continuing to work with ACD for people that have their own credentials because of the low API hits but as soon as a auth server is officially put up, I just see it getting banned again.  

That is my concern.  Setting up an auth server is easy, I'm just not sure that I'm allowed by the TOS to use  any other credentials for rclone.

**Comment by calisro** [comment]
Perhaps rclone is setup to either accept custom API credentials and/or an auth server (in the config rather than in the code) and let people do what they want with their creds and there wouldn't be an official association with rclone until such time as Amazon official allowed it again. At least then it would be flexible enough to allow people to use it if they have access to one or the other.....

**Comment by yonjah** [comment]
Assuming communication with amazon has failed I can't see how this would make any harm (Unless who ever provides the credentials has other use for them).

The only thing we need to be sure is that who ever provides the credentials can be trusted ( This shouldn't be an issue with native app credentials but if we assume amazon actually had a good reason for blocking rclone for sharing its credentials we should also assume they have some security issue which allows compromising customer data with control of what should be publicly available credentials. I would have looked into this ACD security issue a bit more in depth but I have enough t-shirts)

Also I can't see how this in anyway violates amazon TOS the app credentials are there to be used for apps. But if there is any doubt the App can be a generic server allowing to fetch amazon tokens in a secure manner ( so not associated with rclone in any way ). 

I'm just not sure if this is worth the development time. I think it's pretty clear amazon can't be relied on and if there is one thing you want your backup provider to have is reliability. So the only use for it should be moving stuff out of amazon and I hope most users already found a solution for that.

The most important change to the logs should be making the amazon issues clear to any one who might be considering using using their services ( since I think many people actually check which tools available for them before setting on a cloud provider and not the other way around )

**Comment by SoftNotWork** [comment]
I could see donating to rclone/etc for access to something like that.

I mirror over to Amazon and getting rclone back up would be fantastic.

**Comment by ajkis** [comment]
Since amazon is not unlimited storage anymore and have some quite insane pricing now,  personally dont really care if support for it stay as it is eg ability to enter your own secret assuming you have it.

**Comment by ncw** [comment]
@calisro wrote:
> Perhaps rclone is setup to either accept custom API credentials and/or an auth server (in the config rather than in the code) and let people do what they want with their creds and there wouldn't be an official association with rclone until such time as Amazon official allowed it again. At least then it would be flexible enough to allow people to use it if they have access to one or the other.....

I like that idea.  Consequently I have made an oauth server for use with rclone here: https://github.com/ncw/oauthproxy

You'll need the latest beta https://beta.rclone.org/v1.36-165-g52e1bfae/ which has this patch 52e1bfae2a8b67b0056af81eac00a0c394915121 to use it.

I don't have any credentials I can put in the oauth server (I was hoping amazon would supply some) but if someone does have some production cleared credentials, then the oauth server above will work!

**Comment by ncw** [comment]
I have updated the docs in 10d5377ed8fe0136688f5d8fd4df03e73a3047b9

See the forum https://forum.rclone.org/t/proxy-for-amazon-cloud-drive for a working proxy.
