### ISSUE TITLE
SSH Key support for SFTP Remotes

### ISSUE THREAD

**Issue by diamondsw** [ncw/rclone#1494]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS 10.12.5, Synology DSM 6.1.2-15132
> Which cloud storage system are you using? (eg Google Drive)
SFTP to Debian-based colocation server
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
N/A
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
N/A

Splitting this off from #1218 ; please add SSH key support in addition to the current SSH password support and SSH Agent support. Password support requires storing sensitive credentials in the rclone.conf file, and password authentication is not always supported by SSH servers. Agent support is somewhat broken/difficult on macOS, and missing entirely from many embedded or NAS platforms (e.g. Synology). Agents also represent another piece of software that can be misconfigured, break, etc, despite their uses in certain contexts. Supporting a user-specified SSH key would allow a more secure connection than passwords, and an easier and more reliable setup than agents.

Please? :)

**Comment by diamondsw** [comment]
I just ran the Linux/AMD64 build on my Synology, and after updating the remote with a user name and keyfile, it connected with no problem and sync'ed perfectly. I'll test the same from macOS in a moment, but things look good so far!

**Comment by kubark42** [comment]
Neat, thanks!

**Comment by diamondsw** [comment]
Confirmed, works great on macOS Sierra as well. No more need for their "improved" ssh-agent.

**Comment by ncw** [comment]
Excellent, thanks for testing :-)

**Comment by carloshmm** [comment]
Hey, I think this is related:
How to deal with encrypted PEM SSH private keys? I mean, besides my key, I need to enter a password to decrypt it in order to access the server. There are currently three options on rclone:
Password authentication: Discarded for me because my server doesn't allow password authentication, only pub key auth.
Agent Authentication: It is not working on my system (Linux) even with a properly configured ssh-agent process running, ex: I already logged on my server typing my password and it gets stored during all the session, but rclone can't detect the ssh-agent, printing this message:
```
Failed to create file system for "remote:path": couldn't connect to ssh-agent: Error connecting to SSH_AUTH_SOCK: dial unix /ssh-agent.socket: connect: no such file or directory
```
I think that the rclone environment variable "SSH_AUTH_SOCK" is pointing to the wrong place, since the process ssh-agent on my system is storing the file 'ssh-agent.socket' on:
```
/usr/bin/ssh-agent -a /run/user/1000/ssh-agent.socket
```
Private Key authentication: Doesn't work since it needs the password for decrypt my private key. This message is appearing:
```
Failed to create file system for "remote:path:": failed to parse private key file: ssh: cannot decode encrypted private keys
```

**Comment by salmanwaseem007** [comment]
Any update on this? since i need support for this algorithm for key exchange

**Comment by ncw** [comment]
SFTP should work fine with an ssh-agent now on Linux and OSX.  What are you trying @salmanwaseem007 ?

**Comment by salmanwaseem007** [comment]
Sorry i commented on wrong page
