### ISSUE TITLE
rclone downloading massive ammounts of data during Plex scan

### ISSUE THREAD

**Issue by ajthemacboy** [ncw/rclone#1518]
Please see the forum post [here](https://forum.rclone.org/t/plexdrive-with-rclone-plex-downloading-massive-amounts-of-data-during-scan/3031).

- **What is your rclone version?** 1.3.6

- **Which OS you are using and how many bits?** 64-bit Ubuntu 16.04.1

- **Which cloud storage system are you using?** Google Drive

When Plex scans my rclone library, it downloads a massive amount of data from Google Drive, as if it is downloading entire media files to scan them. Here's a screenshot of my network activity: https://drive.google.com/a/eyestra.in/file/d/0B6AmcbVDdoMsUFptbXVHem9YcTA/view?usp=drivesdk

Naturally this is extremely slow. Leaving the library scan running for 10 or so minutes only scans a few of my shows. I have tried disabling "Generate video preview thumbnails" and "Generate chapter thumbnails" 
in Plex's library settings but it had no effect. 

This seems to be a fairly new issue that suddenly several people are reporting on the forum post above. I'm new to rclone and I just uploaded my library to Google Drive so I'm not sure what to do.

**Comment by breunigs** [comment]
>  it downloads a massive amount of data from Google Drive, as if it is downloading entire media files to scan them.

That is quite literally what Plex is doing – this is how it determines the quality, audio tracks, etc. Judging from their blog posts about their "Streaming Brain" technology, it seems like they need a running average bitrate over the whole length of a file, too. Maybe that makes it read a whole file, instead of just the beginning?

Anyway, you want to turn off at least:
* Library → Update my library automatically
* Library → Run a partial scan when changes are detected
* Library → Update my library periodically
* Scheduled Tasks → Perform extensive media analysis during maintenance
* Scheduled Tasks → Update all libraries during maintenance
* Scheduled Tasks → Upgrade media analysis during maintenance
You can use the Plex Media Scanner to manually index files. If you have your files available locally, I recommend to let Plex index them this way and then replace them with a symbolic link to google drive. Plex will keep its previous analysis in this case and not download the file again.

**Comment by ajthemacboy** [comment]
Plex _should_ only need to read metadata from media files, right? I can run `avprobe` on a file and get all the metadata Plex displays without reading the entire file. 

I'm positive Plex doesn't read entire media files when they are stored locally either. rclone can already stream files from the web without downloading the entire file, meaning it is possible for rclone to only read a segment of a media file (I.E, the part that contains the metadata.) It seems like this should something rclone should support.

**Comment by breunigs** [comment]
Yes, rclone supports only reading part of a file. Depending on the read ahead configuration it might read a bit more or a bit less. I checked `avprobe`: it uses roughly 5MB/file to output the metadata. A similar program `mediainfo` uses 40MB/file. Both using default rclone settings. I don't know how much Plex uses, but if you could check that would be great. I have a hunch it is closer to mediainfo than it is to avprobe which absolutely accounts for the traffic you're seeing.

**Comment by breunigs** [comment]
(for reference: people have been requesting a filename only scanner since at least March 2017, this is allegedly what they use for their "Plex Cloud" offering.)

**Comment by ajthemacboy** [comment]
You must be right. Now that I see how fast individual episodes are populating, I agree that it's only using maybe 40 MBs per file. Still, this seems like a lot, but it's something I should take up with Plex.

**Comment by breunigs** [comment]
And power to you. Looking at all the duplicated threads on the Plex Forum with exactly this issue, I wouldn't get my hopes up for a quick fix though.
