### ISSUE TITLE
View google drive trash folder

### ISSUE THREAD

**Issue by jscottdouglas** [ncw/rclone#1524]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
Latest
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian jessie
> Which cloud storage system are you using? (eg Google Drive)
google drive

https://forum.rclone.org/t/google-drive-trash/3044

is there anyway to mount the good drive trash bin? I use it to delete stuff but once in awhile i delete something by accident and then can't find the file cause all my files are encrypted, is there any way to mount the trash bin so i could have a trash bin unencrypted folder in my linux system?

not so sure i am using it right

/usr/bin/rclone mount Google:/NAS /diskpool/.trash/ --drive-trashed-only --allow-non-empty --allow-other --umask 22

Google:/NAS 
is the base folder before all my encrypted stuff

Now in the trash bin i have a few files none seem to show, now if I swap to the root one 1 out of the bunch shows.
Google:/

image.png1300x256 11.3 KB
image.png1090x218 10.6 KB

**Comment by ncw** [comment]
The problem with the approach so far is that for files in subdirectories, it relies on the parent being trashed too.

However that isn't necessarily the case when a file has been trashed but the directory it is in hasn't.  In this case the file won't appear in the listings whereas drive does show it in the trash.

Instead of `trashed=true` this maybe needs a more complicated boolean such as

    (mimeType='application/vnd.google-apps.folder' or trashed=true)

This means that all directories will show in the listing which is unfortunate.  This does work, but is rather clumsly compared to the drive trash listing. 

Showing the trash is likely to show duplicate directories also.

Drive shows any trashed files directly in the trash which are in a a non-trashed directory.

Can we do this with a query... Not easily...

Could maybe just list all files?

Could do a list with no parents and `trashed=true` and store it.?

**Comment by jscottdouglas** [comment]
Not sure if this should be re-opened, permanently delete gives me an Input/output error.

srv1@srv1:/diskpool/trash/media/movie$sudo rm -R Changing\ Lanes\ \(2002\)/
rm: cannot remove ‘Changing Lanes (2002)/’: Input/output error
srv1@srv1:/diskpool/trash/media/movie$ sudo rm -f Changing\ Lanes\ \(2002\)/
rm: cannot remove ‘Changing Lanes (2002)/’: Is a directory

That's an empty directory

srv1@srv1:/diskpool/trash/media$ cd movie/Waist\ Deep\ \(2006\)/
srv1@srv1:/diskpool/trash/media/movie/Waist Deep (2006)$ ls
Waist Deep.2006.tt0456020.mp4
srv1@srv1:/diskpool/trash/media/movie/Waist Deep (2006)$ rm -R Waist\ Deep.2006.tt0456020.mp4
srv1@srv1:/diskpool/trash/media/movie/Waist Deep (2006)$ ls
srv1@srv1:/diskpool/trash/media/movie/Waist Deep (2006)$

file removed fine

srv1@srv1:/diskpool/trash/media/movie$ rmdir Waist\ Deep\ \(2006\)/
rmdir: failed to remove ‘Waist Deep (2006)/’: Input/output error
srv1@srv1:/diskpool/trash/media/movie$

directory not moved fine

**Comment by ncw** [comment]
Empty directories may have non deleted files in which is probably why it failed.

What does the rclone log say?

**Comment by jscottdouglas** [comment]
Jul 24 23:44:21 srv1 rclone[6774]: 2017/07/24 23:44:21 ERROR : xDRZiPinr4MQRKmZkuog3SiF/3IBp6P7xvHL053gQ5YGAC,GP/m5NK7sgkHWB-l,LgSe7Pqhle8oPUOq6oDWMaLOeWEYCap1: Dir.Remove failed to remove directory: directory not empty

**Comment by jscottdouglas** [comment]
was a file in that folder, but I deleted it.
then went to delete the directory and bah error
