### ISSUE TITLE
Option --stats-log-level seems to be broken

### ISSUE THREAD

**Issue by darren12345** [ncw/rclone#1611]
Hi,

Don't have time to test the beta right now, will try to do so later.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.37

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux ARM 32-bit

> Which cloud storage system are you using? (eg Google Drive)

Dropbox

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`/usr/bin/rclone --stats 9999m --stats-log-level ERROR sync /home/user dropbox:Backups/user/`

As you can see, I'm running rclone with stats level set to ERROR (the one I assume should produce the least output). However, the output also contains NOTICE level messages:

> 2017/08/18 18:33:18 NOTICE: sieve/filters.sieve: Can't follow symlink without -L/--copy-links
> 2017/08/18 18:33:20 ERROR : 
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                30
> Transferred:            0
> Elapsed time:        4.4s

**Comment by breunigs** [comment]
If you just want rclone to be quiet, you can also just pass `--quiet`, which is the simplest option. This turns off almost all messages and stats.

If you want more fine-grained control, I think you will need to set `--log-level ERROR` instead. This flag controls what you expected – it sets the minimum log level a message needs to be printed. So, you are right that this will print only `ERROR` message, since `ERROR` is the highest level.

`--stats-log-level` sets the log level with which is stats are printed. This is a subtle difference! You set it to `ERROR` in your example, and that's why the stats at the end are preceeded by ` 2017/08/18 18:33:20 ERROR :`. If you would've set it to `NOTICE` then the printout would read ` 2017/08/18 18:33:20 NOTICE: Transferred…` instead. This can be used to reduce rclone's verboseness, while still getting the stats updates (e.g. `rclone --log-level ERROR --stats-log-level ERROR` would only print errors… and stats every once in a while).

Note that `--stats 0` will turn off stats reporting, regardless if log level.

**Comment by darren12345** [comment]
I’m going to need to read everything you’ve written again, but on first pass I think you’ve missed my point. 

I’ve set the log level to ERROR, which means I should only see messages of ERROR level and nothing else, but you will see from the output I’ve provided I  also seeing NOTICE level messages:

2017/08/18 18:33:18 NOTICE: sieve/filters.sieve: Can't follow symlink without -L/--copy-links

**Comment by breunigs** [comment]
Hm, I'm working off the assumption that this is your whole command: 
```
/usr/bin/rclone --stats 9999m --stats-log-level ERROR sync /home/user dropbox:Backups/user/
```
Is that correct so far? If it is, then you never set the log level. There's `--stats-log-level` *and* `--log-level` and I think you're looking for latter:

Normal output:
```
2017/08/18 18:33:18 NOTICE: sieve/filters.sieve: Can't follow symlink without -L/--copy-links
2017/08/18 18:33:20 INFO : Transferred: 0 Bytes (0 Bytes/s)
```

You specify `--stats-log-level ERROR`:
```
2017/08/18 18:33:18 NOTICE: sieve/filters.sieve: Can't follow symlink without -L/--copy-links
2017/08/18 18:33:20 ERROR : Transferred: 0 Bytes (0 Bytes/s)
                    ^^^^^ this is the *only* difference
```

You specify `--log-level ERROR`:
```
(no output)
```

You specify both`--stats-log-level ERROR --log-level ERROR`:
```
2017/08/18 18:33:20 ERROR : Transferred: 0 Bytes (0 Bytes/s)
```

**Comment by darren12345** [comment]
Ah, I see. Totally misunderstood the purpose of stats-log-level. Thanks. Closing now.
