### ISSUE TITLE
Implement --max-upload flag

### ISSUE THREAD

**Issue by danjames92** [ncw/rclone#1655]
With the new Google Drive 750GB limits, I would love a flag that would stop uploads after hitting a certain GB amount.

I'm aware --bwlimit exists but I want to upload all in one go quickly rather than spread it throughout the day if possible.

Thanks for considering and the great work you do @ncw!

**Comment by ncw** [comment]
Would a flag which limited the total data uploaded work for you?  So something which caused rclone to stop completely when it had reached the limit?  That would be much easier than worrying about data in 24 hour periods.

**Comment by l3uddz** [comment]
I think that would be great @ncw - also we have noticed that sometimes uploads will just stall on 0% for hours, even though its banned, never displaying the Error 403 rate limit, if some kind of check could be put in place to spit out that Error 403 when it sees its been on 0% for e,g. . 15 mins, that would also be of great help.

**Comment by desimaniac** [comment]
@ncw Yes Please!

Also, I have the same issue as @l3uddz r.e. it hanging on 0% for almost an hour before it gives Error 403.

**Comment by danjames92** [comment]
I echo the above comments and I'll take what I can get! 👍

**Comment by 4getit** [comment]
A flag with data upload limit would be very very welcome.
As mentioned here https://github.com/ncw/rclone/issues/1599 as well.
Thanks!

**Comment by dia3olik** [comment]
@ncw Hey Nick this would be great with the current limits...

Thanks!!!!!!!!!!!!

**Comment by ncw** [comment]
I think a --max-upload flag would be relatively easy to implement.

What we should do is just return Fatal errors from [accounting Read](https://github.com/ncw/rclone/blob/master/fs/accounting/accounting.go#L501) when the number of bytes transferred goes over the limit. This will cause the sync to come to a grinding halt.

**Comment by dia3olik** [comment]
I think the absolute ideal would be a a similar approach to the web interface of drive, which in the latest updates just wait until the limit is gone and then automagically resumes the upload. The upload seems stuck but just wait and then it re-start itself. Maybe it would be a solution to just try every 5 mins or so after receiving that error? ;)

**Comment by 4getit** [comment]
If you push it to the daily 750GB limit, isn't that the case already? It hangs until it can continue right?

I think it should just stop. If I want to copy 100GB out of my xTB, it starts copying what's not already there and when it hits my 100GB limit, it should just quit.

**Comment by evulhotdog** [comment]
I disagree that it should stop. The whole point is to max out the amount of data that you can upload to a given source. You still would like the action to continue, you don't want your data to randomly be incomplete because you hit some random limit. You moved those files for a reason.

**Comment by dia3olik** [comment]
exactly! Maybe just a cleaner process where the user get the info from rclone that is waiting for the limit to be reset, maybe in the google apis there is a countdown for as when the limit is resetted and the temp ban lifted which can be passed to the rclone command line output?

**Comment by danjames92** [comment]
Unionfs_cleaner already does most of that for you.

**Comment by 4getit** [comment]
Well, I respectfully disagree.
I know that most cases are because of the 750GB daily upload limit. If you don't care that rclone is running all day, then just use --bwlimit 8500

What if I want to upload 250GB now and in 2 days another 250GB?

In my opinion, with --max-upload xxxGB, it should just upload until it hits the maxmimum and then stop. If you want to do that every day, run a cronjob.

**Comment by dia3olik** [comment]
@4getit In that instance it would use the heads of the hdd for 24hours instead of less of 1hr then spin down and park the heads...(with my fiber)...
Really I think that the cleanest interface would be: uploading 750gb until the soft ban occur, then display a countdown as to when the uploads will be resumed. If the APIs tell you how much time the soft ban will be active for, then it could be really precise and work in harmony, and all of this is without messing around with thousands of checks the next time you restart the upload, it would simply gracefully pause and then automagically resume, but at least giving some feedbacks to the user.

**Comment by 4getit** [comment]
@dia3olik If you want to spin your hdd heads 24hrs, use --bwlimit 8500

As for the rest, the Gdrive API doesn't tell you that and there is not such thing as a magic time of the day your 'soft ban' resets back to 750GB.

The upload limit is a 24 hrs sliding window.

Assume it is 15:00 today and yesterday you finished uploading 10GB at 16:00 and another 10GB at 17:00.

Then at this moment (15:00), your upload limit is 730Gb. At 16:00 it increases with 10GB and at 17:00 it is back to 750GB.

With something like --max-upload 750GB, rclone would just upload 750GB (at either the max speed or the --bwlimit you set). When you setup a cronjob so it does that every day, you maxed things out with 0 checks.

**Comment by dia3olik** [comment]
We're saying the same thing basically...the point is that something like that doesn't actually exist right now inside rclone...and if you do that right now, the next day rclone does thousands of checks for the previous 750gb uploads which were only partial and incomplete...

**Comment by ncw** [comment]
@ishuah would you like to work on this?

I think we should implement a `--max-upload` - anything else is too complicated and requires rclone to understand undocumented stuff about drive.

What we should do is just return [Fatal errors](https://github.com/ncw/rclone/blob/master/fs/fserrors/error.go#L102) from [Accounting read](https://github.com/ncw/rclone/blob/master/fs/accounting/accounting.go#L133) when the number of bytes transferred goes over the limit. This will cause the sync to come to a grinding halt.

I wouldn't bother truncating the read or anything like that, just return the error if the bytes transferred are over the limit.

**Comment by soofuzz** [comment]
@ncw i think --max-upload then exit the process might just be cleaner. Then people who want to run a job everyday can already do so similarly to now using cron and set it to a specific hour everyday.

**Comment by dia3olik** [comment]
@ncw --max-upload would be perfect but I just suggest 2 options included with it.

1) just stop when the next file WOULD go after the limit so just not upload it instead of uploading like 57% of it then abruptly stop leading to an incomplete file, in essence to just round down the value so the limit would not cause to bandwidth wasted due to truncated files near the limit

2) Implement a way to resume the upload the next day from exactly where it was interrupted, 750GB is quite a bit so the next day bandwidth and time is wasted to do thousands of checks (and hdd and cpu power if done with checksums)...

what do you guys think?

**Comment by ncw** [comment]
I've done a first prototype of the --max-transfer flag.  Set it to the number of bytes to transfer, eg `--max-transfer 750GB`.  It doesn't do anything clever when it reaches the limit it just kills all the in progress transfers which isn't idea.  However I wanted to make something work for 1.41!

https://beta.rclone.org/v1.40-113-g6b808f5a-fix-1655-max-upload/ (uploaded in 15-30 mins)

**Comment by xyber411** [comment]
So then in its current state, --max-transfer is both upload and download or just upload?

**Comment by dia3olik** [comment]
@ncw Thanks Nick!!!

BTW What do you think about my 2 suggestions above?

**Comment by greenhelper** [comment]
I tested this prerelease and I have to report that it unfortunately crashes for me after ca. 10 minutes and ca. 10 GB transferred.
I tried this 3 times. No crash when leaving out the max transfer option. 

BTW. i had to use "G" instead of "GB" for some reason.

This is the command I am using: 
./rclone sync -v --transfers 20 --max-transfer 300G source gdrive:/target

The only problem is that I cannot tell what is happening. The output just stalls and I have to Ctrl+C it to get back to the terminal.

**Comment by ncw** [comment]
@xyber411 yes both upload and download

@dia3olik good suggestions, but not for the first iteration!

@greenhelper That sounds like a livelock or deadlock rather than a crash.  Can you press `CTRL-\` when it locks up and paste the output please?  There might be quite a lot of it!

> BTW. i had to use "G" instead of "GB" for some reason.

Err, yes `--max-transfer 750G` is the correct syntax!

**Comment by greenhelper** [comment]
Here is the output from CTRL-\:

https://cryptpad.fr/code/#/1/view/PXIj36Gd3xHXAY706bfPjQ/VmagW5OH+slBrJGN8gLlME2MqLeo4bDlpPwv1XSMo7I/

Here I ran it with --transfers 1 (but same thing happened with --transfers 20).

As I wrote earlier the sync works fine without the max-transfer parameter. Total data is around 1.5 TB of which around 600 GB are already synced to gdrive.  

HTH, although it does not look that useful too me at first glance.

I don't have root access on this server, so I am limited in what I can do in terms of further debugging/installing software.

**Comment by ncw** [comment]
@greenhelper looking at the log some more, the single transfer seems to be in progress.  Can you check with an external bandwidth monitor to see if it is still transferring data at the point everything goes to idle?

**Comment by ncw** [comment]
@xyber411 transfer is what rclone measures so that is what we limit.  Rclone doesn't really have a concept of upload or download - all storage backends are the same to it!

**Comment by xyber411** [comment]
Okay, so to skirt this limitation, I think what I'll do is put together two mounts, a read-write and read-only.  I'll put the limitation on the read-write, as such: 
unionfs -o cow,allow_other,direct_io,auto_cache,sync_read,nonempty,hide_meta_files rclonecachecryptro=RO:rclonecachecryptrw:RW

Any thoughts on trouble I'll have with this setup?

**Comment by ncw** [comment]
I stared at the code some more and have figured out where the deadlock is.. just need to fix it now!

**Comment by ncw** [comment]
OK here is some deadlock free (hopefully!) code

https://beta.rclone.org/v1.41-014-gcfacafca-fix-1655-max-upload/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
@greenhelper thanks for testing :-)

I've fixed another bug - it didn't exit when it should have done, but errored out all the transfers!

This should hopefully be the last beta before I merge it.

https://beta.rclone.org/v1.41-018-g59dbc08e-fix-1655-max-upload/ (uploaded in 15-30 mins)

> The only thing which could be improved imho is that it exited with an error ("Max transfer limit reached as set by --max-transfer"). Maybe a regular exit 0 would be better?

Hmm, I'm not sure about that.  rclone will have already peppered the logs with ERROR messages at that point and it didn't complete its primary mission to sync your files.

I made exit code 8 for --max-transfer exceeded - does that help? Then you can check for exit code 0 or 8 and know that rclone succeeded in uploading at least up to --max-transfer.

**Comment by evulhotdog** [comment]
I agree with @ncw, its not actually exiting successfully. It didn't process everything it was _supposed to_ due to the limitations on the app. 

An exit code thats outside of the norm should be used to designate that, and it looks like that was just done :)

**Comment by ncw** [comment]
I've merged this to master now

https://beta.rclone.org/v1.41-022-g21383877/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) from now on and in 1.41
