### ISSUE TITLE
Support a different Swift storage endpoint other than what is returned from auth request

### ISSUE THREAD

**Issue by treyd** [ncw/rclone#167]
In Swift, it is possible for a user to have access to accounts other than what is returned as the X-Storage-Url.  It would be helpful if you could optionally define this as part of the remote endpoint configuration in rclone.

**Comment by ncw** [comment]
That would be an unusual setup!  Can you tell me a bit more about it?  Why doesn't keystone return the correct storage URL?

**Comment by tduskin** [comment]
In this particular case, I'm not imagining a keystone auth setup, but rather a v1.0 auth.  It is possible to set ACLs on swift accounts which grant access to other users.  http://docs.openstack.org/developer/swift/overview_auth.html has more information.  It is also entirely possible to have a Swift account (which is really just a storage area) that is not associated with any particular user, but accessible by a service user or "super-user".

The use case I'm actually thinking of that this feature would help massively is migration from one Swift cluster to another.  Instead of having to configure rclone with user credentials for every individual user, we could just use the credentials from one super-user and create entries for every account we want to migrate.  We'd still have to configure .rclone.conf entry for each account, but this would save us from having to know the username and password for individual users.

**Comment by ncw** [comment]
I see what you are getting at.  One thing you should bear in mind is that rclone doesn't copy all the metadata at the moment - see #111

I think this feature is probably too specialised for rclone.  You could have a go with a quick and dirty patch like this which would set the storage url from something called `storage_url` in the config file.  If the token expires it will attempt to get another one from keystone though which will overwrite the storage url.

If this works I might consider putting it in as an undocumented feature (with a bit more error checking!).

```diff
--- a/swift/swift.go
+++ b/swift/swift.go
@@ -151,6 +151,7 @@ func swiftConnection(name string) (*swift.Connection, error) {
 	if err != nil {
 		return nil, err
 	}
+	c.StorageUrl = fs.ConfigFile.MustValue(name, "storage_url")
 	return c, nil
 }
 ```

**Comment by ncw** [comment]
Just wondering if you had any more thoughts on the above?

**Comment by xlucas** [comment]
:+1:  for this, it would allow usage of swift ACLs with rclone.

I've tested your patch and it works (5 lines shift since then).

```patch
--- a/swift/swift.go
+++ b/swift/swift.go
@@ -156,6 +156,7 @@ func swiftConnection(name string) (*swift.Connection, error) {
    if err != nil {
        return nil, err
    }
+   c.StorageUrl = fs.ConfigFile.MustValue(name, "storage_url")
    return c, nil
 }
```

Adding `storage_url = <url>` to a remote's configuration section does allow me to use an account using a different storage URL than the one retrieved from authentication.

**Comment by ncw** [comment]
@xlucas can you explain how adding a `storage_url` helps you use ACLs with rclone?  Maybe this should be better supported with rclone?

**Comment by xlucas** [comment]
Let's say I have two tenants `A` & `B`. In tenant `A` I have a container `cA` in `A` and a user `uB` in tenant `B`. With Swift you can set a read/write ACL for user `uB` on `cA`.

As `uB` isn't a member of tenant `A` then authentication gonna throw a storage URL referencing the account related to tenant `B` while `uB` actually needs to authenticate on `A`'s account to access `cA`.

**Comment by ncw** [comment]
OK I'll put the above patch in with a bit of docs - unless you want to do a PR?

I note that the patch needs to not override the StorageURL if the `storage_url` config parameter is empty, so it isn't quite right as-is!

**Comment by xlucas** [comment]
Sure, I can do a PR for that. You are right we need something a bit smarter that holds the storage URL after authentication if the one from the remote configuration section is empty.

**Comment by ncw** [comment]
Actually come to think of it, the StorageUrl will get overwritten on reauthentication.  So it really needs a fix like the one used in the Hubic remote: https://github.com/ncw/rclone/blob/master/hubic/auth.go which makes it a bit more complicated.

What you would do is do the auth then wrapped the returned Auth in one which just override the `StorageUrl` method.

**Comment by xlucas** [comment]
Sorry got quite busy in the past weeks. Here's the PR !

**Comment by 131** [comment]
I think there's  still an issue here
storage_url (overrided in rclone.conf) is not used 
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1
```

[thecube]
type = swift
env_auth = true
auth_version = 3
auth = https://auth.cloud.ovh.net/v3/
endpoint_type = public
storage_url = <redacted>
tenant_domain = default
tenant = <redacted>
domain = default
user = <redacted>
key = <redacted>
region = GRA3

```
Yet, using export OS_STORAGE_URL & OS_AUTH_TOKEN env vars from swift auth works fine.

Is there something i'm missing ?
