### ISSUE TITLE
passwords with trailing spaces are not correctly interpreted (SFTP)

### ISSUE THREAD

**Issue by sheepdestroyer** [ncw/rclone#1717]
Hi, 

I am on Fedora 26 and tried both 1.38 and last rev (with updated dependencies). I have the problem on both.

When setting up an SFTP remote for a user whose password ends with spaces, the connection to  the remote fails :
````
NewFs: couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
````

I made sure that this is the problem by changing the user's password to not have spaces at the end ; then the connection works as it should.

**Comment by ncw** [comment]
Hmm, this is caused by rclone's password entry code stripping spaces from the password!

As a workaround you can use rclone obscure "my password with a space on the end " and put the encrypted thing output into the config file.

I should probably remove this though and just warn the user there is a space on the end.

**Comment by ishuah** [comment]
Can I pick this up?

**Comment by ishuah** [comment]
I jumped the gun, sorry if I'm duplicating effort.

**Comment by ishuah** [comment]
Please find a beta with the fix in: https://beta.rclone.org/v1.38-093-gc65734ee/ (uploaded in 15-30 mins)
