### ISSUE TITLE
Warn the user if they use --include and --exclude together

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1764]
...as due to the command line parsing they probably won't do what the user wants.

Maybe

> Using --filter is recommended instead of both --include and --exclude as the order they are parsed in is indeterminate

Maybe any of the --include* and --exclude* used together?

**Comment by xerrni** [comment]
I`m going to work on it.

**Comment by parity3** [comment]
I have to ask the obvious question here because there's not enough info/refs in this issue:

Why can't passed in arguments be read in order?

```Note that all the options of the same type are processed together in the order above, regardless of what order they were placed on the command line.```

... why was this decision made? I'm fine if it's "because that's how we wrote it and we don't feel like changing it and/or scripts now depend on this legacy behavior".. but that reason should both be in the docs and this cli warning message.

**Comment by ncw** [comment]
> Why can't passed in arguments be read in order?

It is a limitation of the cli library rclone uses [spf13/pflag](https://github.com/spf13/pflag) - by the time rclone gets the flags they have been reduced to an array of strings sorted by flag type.
