### ISSUE TITLE
drive: Access Backup and Sync "Computers" Folders/Files

### ISSUE THREAD

**Issue by neocryptek** [ncw/rclone#1773]
Hi,

Similar to https://forum.rclone.org/t/rclone-how-to-access-google-drive-file-from-google-backup-and-sync-computer-folder/4000

The new official Google "Backup and Sync" client adds new folders to Google Drive under "Computers" in the web UI, which seem to be marked with these file properties in drive API:
```
"descendantOfRoot": false,
```

The top level folder ("My PC" or "My MacBook Pro" etc) has:
```
"folderFeatures": [
"machineRoot"
],
```

These top-level folders have no parents:
```
"parents": [],
```

and all subfolders underneath have:
```
"folderFeatures": [
"arbitrarySyncFolder"
],
```

Since they all have "descendantOfRoot": false, they don't seem to be accessible via any path-based command in this CLI (or I just don't know what root prefix to use).

Will these folder types be supported so I can create files/subfolders/etc in these "Computers" folders?

Thanks!

What is your rclone version (eg output from `rclone -V`)
```
rclone v1.38
os/arch: linux/386
go version: go1.9
```

Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 32bit

Which cloud storage system are you using? (eg Google Drive)
Google Drive

The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone lsd remote:

rclone ls remote:Computers
rclone ls remote:/Computers
rclone ls remote:Computers/name
rclone ls remote:/Computers/name
```

A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
lsd:
```
2017/10/26 09:20:10 INFO  : Google drive root '': Modify window is 1ms
          -1 2017-10-16 00:47:21        -1 [normal_drive_file, not in Computers subtree]
2017/10/26 09:20:10 DEBUG : Go routines at exit 4
```

ls (same for all paths):
```
2017/10/26 09:17:38 INFO  : Google drive root 'Computers/name': Modify window is 1ms
2017/10/26 09:17:38 ERROR : : error listing: directory not found
2017/10/26 09:17:38 Failed to ls: directory not found
```

**Comment by ncw** [comment]
Do you know the google IDs of the folders?  They look something like `0AJr73JyJrbHLPj2EQK`?  It would be easy to make rclone start from a folder like that?  That is essentially how I added team drive support.

If you add `team_drive = 0AJr73JyJrbHLPj2EQK` to your .rclone.conf drive then it might work.

Do you know if there is any API for viewing the backup and sync folders?  Given that then rclone could configure them in a similar way to team drives.

If they aren't linked from the root, then rclone won't be able to find them without a bit of help.

**Comment by neocryptek** [comment]
Yeah, I can find the google folder ids via the normal drive api (or even the web UI URL).

They look like this for me:
0B_5BBnuMQe9oAAAAAAAAAAAAAAA (top-level machine root for windows computer)
0B_5BBnuMQe9oBBBBBBBBBBBBBBB (top-level machine root for macbook computer)
0B_5BBnuMQe9oXXXXXXXXXXXXXXX (top-level machine root for ubuntu computer)
0B_5BBnuMQe9oYYYYYYYYYYYYYYY (folder underneath ubuntu computer)

Compared to the normal folder inside my normal drive:
0B_5BBnuMQe9oZZZZZZZZZZZZZZZ

They seem to all start with the same prefix and end with 15 random characters (probably some guid/hash). I guess that's different than team drives (I don't have a team drive)?

I can get at them with the normal drive api with the file ids (that's how I figured out the attributes mentioned in first post):
```
https://www.googleapis.com/drive/v2/files/$FILE_ID
```
And via the drive.google.com web UI:
```
https://drive.google.com/drive/folders/$FILE_ID
```

Though I'm not sure how to list all the machine roots without knowing their ids first (or knowing the id of a file under them and then walking the parent links up until the root folder has no parent links).
This is the URL in the web UI to list all computers:
```
https://drive.google.com/drive/computers
```

However, if I try to set either the machine root folder or a folder below it as a team_drive in rclone.conf I get this error:
```
2017/10/28 13:06:31 ERROR : : error listing: couldn't list directory: googleapi: Error 404: Team Drive not found: 0B_5BBnuMQe9oXXXXXXXXXXXXXX, notFound
```

**Comment by ncw** [comment]
It would be nice to allow rclone to start from a folder ID provided in the config file

This would help with #1799 too

This would be a relatively easy change if someone wants to have a go?

**Comment by xyzulu** [comment]
It is possible to add subfolders of the "My Computers" to "My Drive".. 
ie My Computers > My iMac > Files > right click on Documents and "add to my drive".. then rclone will sync the folders.

It's not possible with the top folder, ie in the example above the Files folder can't be added.. but the subfolder of that.. Documents .. can be added

**Comment by ncw** [comment]
@xyzulu yes that is the intended use of this feature - if you can get the folderID of the folder which you will find in the URL  eg `https://drive.google.com/drive/folders/0BzSwxxxxxxxxxxxxxxxxxxxxxxxxxxxx` then you can add that to rclone.

**Comment by ncw** [comment]
I have made a beta for this feature here:

https://pub.rclone.org/v1.39-072-g158f26b8-drive-scope%CE%B2/

Note that you will have to make a new drive remote in order to make it work (or edit an old one and run through the oauth process again).

Here are the extra docs. I haven't put the new config flow in - hopefully that will be obvious what is happening.

Any feedback much appreciated!

### Scopes ###

Rclone allows you to select which scope you would like for rclone to use.  This changes what type of token is granted to rclone.  [The scopes are defined here](https://developers.google.com/drive/v2/web/about-auth).

The scope are

#### drive ####

This is the default scope and allows full access to all files, except for the Application Data Folder (see below).

Choose this one if you aren't sure.

#### drive.readonly ####

This allows read only access to all files.  Files may be listed and downloaded but not uploaded, renamed or deleted.

#### drive.file ####

With this scope rclone can read/view/modify only those files and folders it creates.

So if you uploaded files to drive via the web interface (or any other means) they will not be visible to rclone.

This can be useful if you are using rclone to backup data and you want to be sure confidential data on your drive is not visible to rclone.

Files created with this scope are visible in the web interface.

#### drive.appfolder ####

This gives rclone its own private area to store files.  Rclone will not be able to see any other files on your drive and you won't be able to see rclone's files from the web interface either.

#### drive.metadata.readonly ####

This allows read only access to file names only.  It does not allow rclone to download or upload data, or rename or delete files or directories.

### Root folder ID ###

You can set the `root_folder_id` for rclone.  This is the directory that rclone considers to be a the root of your drive.  Normally you will leave this blank and rclone will determine the correct root to use itself.

However you can set this to restrict rclone to a specific folder or to access the Backup and Sync "Computers" Folders/Files.  In order to do this you will have to find the Folder ID of the folder you wish rclone to display.  This will be the last segment of the URL when you open the folder.  So if the folder/computer backup you want to show looks like `https://drive.google.com/drive/folders/1XyfxxxxxxxxxxxxxxxxxxxxxxxxxKHCh` in the browser, then you use `1XyfxxxxxxxxxxxxxxxxxxxxxxxxxKHCh` as the `root_folder_id` in the config.

There doesn't appear to be an API to discover the folder IDs of the "Computers" tab - please contact us if you know otherwise!

**Comment by chncpla** [comment]
@ncw it's a read-only file system?! can't upload to computer folders.

**Comment by ncw** [comment]
@chncpla it doesn't look like it.  I'll make a note of that in the docs.  I can't find any docs on any public API for the "computers" tab so we are in uncharted territory!

**Comment by ncw** [comment]
I have merged this to master now :-)  Find the docs [here](https://github.com/ncw/rclone/blob/master/docs/content/drive.md#scopes).

https://beta.rclone.org/v1.39-088-ga4fe2455/ (uploaded in 15-30 mins)

**Comment by ducktype** [comment]
Sorry i'm missing something or event with this method we cannot access the "Backups" section in Google Drive? i can't find a folder id of this "Backups"!

![gdrive_web](https://user-images.githubusercontent.com/122023/35532510-c685508a-053a-11e8-9996-e1d491c19831.png)

**Comment by ncw** [comment]
Click on "computers" and open one of the directories in there to get its ID

**Comment by ducktype** [comment]
Sorry but the url reamis the same for the "Backups" section:
![gdrive_web](https://user-images.githubusercontent.com/122023/35535445-e1df4dfa-0543-11e8-911e-1e439729c557.png)

**Comment by ducktype** [comment]
Seems that there is a way to access those backups folders by impersonating the "app" that have done the backup using its appid:

i'm not expert about gdrive api but here is a python script to do that:
https://github.com/EliteAndroidApps/WhatsApp-GD-Extractor/blob/master/WhatsAppGDExtract.py

it's possible to add some config in rclone to impersonate an app?

**Comment by ncw** [comment]
> Sorry, i want to access the "Backups" section not the "Computers"

Ah, so many features in drive - I hadn't realised Backups was different from "Computers".  Looking at it now I can see I have a Backups tab too and looking it it, it seems totally opaque.

I can't find any API docs for that - can you?

I'll make it clear in the docs that what we have now is for the "Computers" section

> it's possible to add some config in rclone to impersonate an app?

You can set the `client_id` and `client_secret` (if you know those) to impresonate an app.

**Comment by baxenko** [comment]
Excuse me.
1) Any news on accessing the Backups folder?
2) Is there a way to create a folder in "Computers"?

**Comment by ncw** [comment]
@baxenko this is what it says in the docs, so I think the answer is no

> NB folders under the “Computers” tab seem to be read only (drive gives a 500 error) when using rclone.
> 
> There doesn’t appear to be an API to discover the folder IDs of the “Computers” tab - please contact us if you know otherwise!
> 
> Note also that rclone can’t access any data under the “Backups” tab on the google drive web interface yet
>

**Comment by joshieecs** [comment]
> There doesn’t appear to be an API to discover the folder IDs of the “Computers” tab - please contact us if you know otherwise!

You can get the id for a "Computer" folder by finding all files with these properties:

mimeType 'application/vnd.google-apps.folder'
owners[].me = true _(or ownedByMe = true)_
parents[] = **_null_**
capabilities.canShare = false

If it is a folder, it is owned by the user, and it has no parents and cannot be shared -- then it is a "Computer" folder. No other kind of file meets each of these conditions, and no other folder meets _either_ condition of no parents or canShare=false.

I don't think the API will let you query for the null parents container or the canShare capability, but you can create a collection of all the folders you own, and filter them locally.
`q=(mimeType = 'application/vnd.google-apps.folder' and 'me' in owners)`

I think it would be okay unless someone had many thousands of folders.

However, a simple workaround is to use the new Google Drive shortcuts feature and create a shortcut to the "Computer" folder somewhere in "My Drive". 

> NB folders under the “Computers” tab seem to be read only (drive gives a 500 error) when using rclone.

You can't write to the "Computer" folder root, but you can write to any subfolders than exist in the "Computer" folder. That is not just a limitation of rclone, you can't create new files or folders in the root from the Google Drive web interface either. But rclone works fine writing to any subfolders that exist under the "Computer" folder.

It makes sense if you consider how Backup and Sync works. You can't pick loose files to sync, only folders. It's a lot like SMB shares, you can't write to the "server" root, only the "share" subfolders. 

Since "Computer" folders are an exclusive feature for Backup and Sync, I'm guessing whatever private API it's using blocks write access to the root because the client cannot handle loose files in there, or extra folders that don't map to a local folder on the client's disk.

**Comment by ncw** [comment]
Thank you for the explanation @joshieecs and the innovative way of finding the Computer folders.

> However, a simple workaround is to use the new Google Drive shortcuts feature and create a shortcut to the "Computer" folder somewhere in "My Drive".

I like this idea very much.

Do you fancy sending a PR to [update the docs](https://github.com/rclone/rclone/blob/master/docs/content/drive.md#root-folder-id) - you can edit them online by clicking the pen symbol in the top right.

> Since "Computer" folders are an exclusive feature for Backup and Sync, I'm guessing whatever private API it's using blocks write access to the root because the client cannot handle loose files in there, or extra folders that don't map to a local folder on the client's disk.

The root is clearly special not having any parents so yes I expect you are right...

**Comment by ncw** [comment]
@FilippoMuschera yes, please submit a PR to update the docs :-) You only need to edit this file https://github.com/rclone/rclone/blob/master/docs/content/drive.md and you can even do it in your browser if you want! (Click the pencil icon).

**Comment by FilippoMuschera** [comment]
I've submitted it. I hope it's well written, let me know if I need to change anything!
