### ISSUE TITLE
Feature Request: Gdrive AppData

### ISSUE THREAD

**Issue by pedrosimao** [ncw/rclone#1799]
It would be great if we could add Gdrive AppData Folders as our destinations while adding new remotes via "rclone config".
Gdrive AppData allow us to make data hidden from Gdrive WebUI interface, and completely inaccessible to any other app using Gdrive.
An example of an app using this feature:
http://hiddenfolder.flowsoft7.com/
Here we can find the documentation on AppData: https://developers.google.com/drive/v3/web/appdata

Thanks!

**Comment by ncw** [comment]
I have made a beta for this feature here:

https://pub.rclone.org/v1.39-072-g158f26b8-drive-scope%CE%B2/

Note that you will have to make a new drive remote in order to make it work (or edit an old one and run through the oauth process again).

Here are the extra docs. I haven't put the new config flow in - hopefully that will be obvious what is happening.

Any feedback much appreciated!

### Scopes ###

Rclone allows you to select which scope you would like for rclone to use.  This changes what type of token is granted to rclone.  [The scopes are defined here](https://developers.google.com/drive/v2/web/about-auth).

The scope are

#### drive ####

This is the default scope and allows full access to all files, except for the Application Data Folder (see below).

Choose this one if you aren't sure.

#### drive.readonly ####

This allows read only access to all files.  Files may be listed and downloaded but not uploaded, renamed or deleted.

#### drive.file ####

With this scope rclone can read/view/modify only those files and folders it creates.

So if you uploaded files to drive via the web interface (or any other means) they will not be visible to rclone.

This can be useful if you are using rclone to backup data and you want to be sure confidential data on your drive is not visible to rclone.

Files created with this scope are visible in the web interface.

#### drive.appfolder ####

This gives rclone its own private area to store files.  Rclone will not be able to see any other files on your drive and you won't be able to see rclone's files from the web interface either.

#### drive.metadata.readonly ####

This allows read only access to file names only.  It does not allow rclone to download or upload data, or rename or delete files or directories.

### Root folder ID ###

You can set the `root_folder_id` for rclone.  This is the directory that rclone considers to be a the root of your drive.  Normally you will leave this blank and rclone will determine the correct root to use itself.

However you can set this to restrict rclone to a specific folder or to access the Backup and Sync "Computers" Folders/Files.  In order to do this you will have to find the Folder ID of the folder you wish rclone to display.  This will be the last segment of the URL when you open the folder.  So if the folder/computer backup you want to show looks like `https://drive.google.com/drive/folders/1XyfxxxxxxxxxxxxxxxxxxxxxxxxxKHCh` in the browser, then you use `1XyfxxxxxxxxxxxxxxxxxxxxxxxxxKHCh` as the `root_folder_id` in the config.

There doesn't appear to be an API to discover the folder IDs of the "Computers" tab - please contact us if you know otherwise!

**Comment by pedrosimao** [comment]
@ncw This is brilliant. It worked perfectly for me!
I am sorry I ended up not having time enough to contribute to the project.
I hope I will be able to do so in the future.

**Comment by pedrosimao** [comment]
@ncw I have one comment though. I have tried to run the "moveto" command to copy a Folder from Gdrive (scope "drive", accessible via web interface) to a Folder inside "drive.appfolder" scope. And it seems rclone downloads the entire content to my computer and later copy it to the appfolder, unlike it does while moving from inside the same scope, where folder is simply renamed. Do you think it is possible to only use the "rename" strategy, instead of copying it all over again?

**Comment by ncw** [comment]
@pedrosimao thanks for testing

>  I have one comment though. I have tried to run the "moveto" command to copy a Folder from Gdrive (scope "drive", accessible via web interface) to a Folder inside "drive.appfolder" scope. And it seems rclone downloads the entire content to my computer and later copy it to the appfolder, unlike it does while moving from inside the same scope, where folder is simply renamed. Do you think it is possible to only use the "rename" strategy, instead of copying it all over again?

I don't know whether Google let you do this.  A bit of experimenting makes me beleive that it isn't possible.  You certainly can't do it with rclone because you need to have a remote which shows both the contents of the appdata folder and the files in drive and that isn't possible with the current drive APIs.  I suspect even if you did manage to do it somehow, the files wouldn't be readable by rclone as they would have the wrong permissions.

**Comment by ncw** [comment]
I have merged this to master now :-)  Find the docs [here](https://github.com/ncw/rclone/blob/master/docs/content/drive.md#scopes).

https://beta.rclone.org/v1.39-088-ga4fe2455/ (uploaded in 15-30 mins)
