### ISSUE TITLE
BUG:  fatal error: runtime: out of memory with v1.38-194-g639e8127β

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#1868]
rclone v1.38-194-g639e8127β

cmd:  /usr/bin/rclone copy gdrive: dropbox: -v --retries=5 --transfers=40 --checkers=40 --stats 60s --log-file=/root/logs/gsyncdropbox.log

Server have 4GB ram ( hetzner cloud ) and I was using same commands on multiple server and never encounter this error: 
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xfb1ff0, 0x16)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:605 +0x95
```

LOG:  https://pastebin.com/QJNHvgE6

**Comment by ajkis** [comment]
update: I changed transfers/checkers to 20 ( from 40 ) and so far so good. 

I just find it weird since i used 100 transfers/checkers on 4GB VM's before without a problem.

**Comment by ncw** [comment]
I see you are using dropbox.  In 6f61da5c75b6c112e6d832f8dde80a8549f164c8 I changed it to buffer chunks in memory so they could be retried which makes large file transfers much more reliable and in 8357a82eeeeae5b233df1218fcddc350d8fd8c6b I set the chunk size to 48MB.

You can change transfers to 20, or you could lower --dropbox-chunk-size to work around this.

I'm going to close this since this is an expected outcome, but thanks for reporting it.
