### ISSUE TITLE
Errors copying local to swift

### ISSUE THREAD

**Issue by xgiovio** [ncw/rclone#190]
Hello, I correctly configured swift. The name of remote service is hubic
When i launch the following command:
rclone copy "C:/myfolder" "hubic:default/myfolder"
I receive error: can't copy file due to limited fs

Why can't i copy a local path to a hubic folder?

**Comment by zeshanb** [comment]
Hello there,

Let's try to diagnose this by first doing ls to see if rclone can at least
list directories of container:

run this command:
rclone lsd hubic:

This should list directories in hubic service.

Regards,
Zeshan

**Comment by xgiovio** [comment]
yes, i can see them

**Comment by zeshanb** [comment]
If myfolder is one of the directories then you can try this:

rclone copy --dry-run C:/myfolder hubic:myfolder

if myfolder isn't one of the directories then:

rclone copy --dry-run C:/myfolder hubic:

--dry-run is just to test how this command will function.



On Sun, Nov 1, 2015 at 1:26 PM, Giovanni Di Grezia <notifications@github.com

**Comment by ncw** [comment]
This has the same cause as #172 I'm pretty sure.  It is because the hubic client creates 0 sized files for each directory that it makes. Rclone isn't ignoring  these as it should (hence the message about limited fs) so the fix in #172 (which I haven't done yet)  should fix this. 

You should find rclone works fine to a destination you didn't create with the hubic client though.

**Comment by xgiovio** [comment]
thank you for all your answers.

As ncw said:
>You should find rclone works fine to a destination you didn't create with the hubic client though.
This is true.

Do you have any eta for 0 files fix?

**Comment by ncw** [comment]
This should be all fixed with v1.24 - let me know if it isn't

Thanks for the report

Nick
