### ISSUE TITLE
What's the purpose and particular usage of the `rclone obscure` command?

### ISSUE THREAD

**Issue by mo-han** [ncw/rclone#1955]
I've already read the doc for that, but still can't understand when and how to use that sub-command.
By the command syntax I need to feed it a plaintext password, and then prompted to enter the password which encrypt the rclone config file, after that it spits an obscured string which I have no idea how or where to use.
---
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

> Which cloud storage system are you using? (eg Google Drive)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

**Comment by dpedu2** [comment]
When rclone needs to store a password or other secret token in your config file, it obscures (or encodes) the value instead of storing it in plaintext as-is, as a minimal line of security. 

I hadn't noticed that command before, though it seems like it provides quick access to the obscure function, in case you want to update a secret in the config file manually.

https://github.com/ncw/rclone/blob/master/fs/config.go#L168

**Comment by mo-han** [comment]
@dpedu2 thx for the explanation, which does make sense, though we still need some info from the official.

**Comment by ncw** [comment]
`rclone obscure` is for making config files from scripts @dpedu2 is 100% correct.

You can ignore it unless you are scripting the creating of config files.
