### ISSUE TITLE
Set GDrive access scope during rclone config [Feature Request]

### ISSUE THREAD

**Issue by smasover** [ncw/rclone#2000]
During the configuration process for GDrive, can a feature be added such that the user is prompted to choose a different scope than the default if s/he wishes?

The case I am particularly interested in as described in [rclone forum post 4627](https://forum.rclone.org/t/feature-request-set-gdrive-access-scope-during-rclone-config/4627) is to set the scope to _https://www.googleapis.com/auth/drive.file_. GDrive authorization scopes are described here: https://developers.google.com/drive/v2/web/about-auth

Note that [issue 337](https://github.com/ncw/rclone/issues/337) makes a similar request for readonly scope. Per NCW, note that [issue 1799](https://github.com/ncw/rclone/issues/1799) makes a similar request for drive.appdata scope. Thus, if this request is accepted it may made sense to allow the user to choose a selection of one of:

- drive
- drive.readonly
- drive.file
- drive.appfolder

**Comment by ncw** [comment]
I have made a beta for this feature here:

https://pub.rclone.org/v1.39-072-g158f26b8-drive-scope%CE%B2/

Note that you will have to make a new drive remote in order to make it work (or edit an old one and run through the oauth process again).

Here are the extra docs. I haven't put the new config flow in - hopefully that will be obvious what is happening.

Any feedback much appreciated!

### Scopes ###

Rclone allows you to select which scope you would like for rclone to use.  This changes what type of token is granted to rclone.  [The scopes are defined here](https://developers.google.com/drive/v2/web/about-auth).

The scope are

#### drive ####

This is the default scope and allows full access to all files, except for the Application Data Folder (see below).

Choose this one if you aren't sure.

#### drive.readonly ####

This allows read only access to all files.  Files may be listed and downloaded but not uploaded, renamed or deleted.

#### drive.file ####

With this scope rclone can read/view/modify only those files and folders it creates.

So if you uploaded files to drive via the web interface (or any other means) they will not be visible to rclone.

This can be useful if you are using rclone to backup data and you want to be sure confidential data on your drive is not visible to rclone.

Files created with this scope are visible in the web interface.

#### drive.appfolder ####

This gives rclone its own private area to store files.  Rclone will not be able to see any other files on your drive and you won't be able to see rclone's files from the web interface either.

#### drive.metadata.readonly ####

This allows read only access to file names only.  It does not allow rclone to download or upload data, or rename or delete files or directories.

### Root folder ID ###

You can set the `root_folder_id` for rclone.  This is the directory that rclone considers to be a the root of your drive.  Normally you will leave this blank and rclone will determine the correct root to use itself.

However you can set this to restrict rclone to a specific folder or to access the Backup and Sync "Computers" Folders/Files.  In order to do this you will have to find the Folder ID of the folder you wish rclone to display.  This will be the last segment of the URL when you open the folder.  So if the folder/computer backup you want to show looks like `https://drive.google.com/drive/folders/1XyfxxxxxxxxxxxxxxxxxxxxxxxxxKHCh` in the browser, then you use `1XyfxxxxxxxxxxxxxxxxxxxxxxxxxKHCh` as the `root_folder_id` in the config.

There doesn't appear to be an API to discover the folder IDs of the "Computers" tab - please contact us if you know otherwise!

**Comment by smasover** [comment]
I tested the MacOS 386 binary, configuring then using drive.file scope. Worked exactly as expected, thanks!

**Comment by ncw** [comment]
@smasover thanks for testing!  Will merge shortly into the regular beta channel.

**Comment by ncw** [comment]
I have merged this to master now :-)  Find the docs [here](https://github.com/ncw/rclone/blob/master/docs/content/drive.md#scopes).

https://beta.rclone.org/v1.39-088-ga4fe2455/ (uploaded in 15-30 mins)
