### ISSUE TITLE
Update OneDrive to Microsoft Graph

### ISSUE THREAD

**Issue by olihey** [ncw/rclone#2011]
I have been looking into the issues with OneDrive and came across Microsoft Graph which should make the OneDrive (Business) / SharePoint access much simpler. Basically it's an API that access OneDrive, OneDrive for Business and SharePoint sites the same way.

Good into talk: [https://www.youtube.com/watch?v=IntbgqDNeNU](https://youtu.be/IntbgqDNeNU?t=1072) (interesting parts starts at 17:52)
Another comprehensive intro: [https://www.youtube.com/watch?v=zw8AR3Sp7MU](https://www.youtube.com/watch?v=zw8AR3Sp7MU)

**Comment by olihey** [comment]
Okay, took the liberty of starting on this 😉
Got authentication working and tested so far against a OneDrive Personal, Office 365 Business Premium and even a company account (Office 365 Enterprise E3, I think they are called).

Commits are here: https://github.com/olihey/rclone/commits/onedrive_graph

**Comment by olihey** [comment]
Anyone who is interested [here](https://drive.google.com/drive/folders/1ojgVP0jliEsU7krsO8CKF2M5uUT69xez?usp=sharing) is a beta. Headless auth does not work yet

**Comment by ncw** [comment]
Well simplified auth sounds like a win to me :-)

Do you think Microsoft Graph is now the recommended way of doing this sort of auth?  It certainly simplifies the code which is a gread thing!

I see you made a new registration for rclone (well new client ID) is that a new registration with Microsoft Graph?

**Comment by olihey** [comment]
I think Microsoft Graph is the way to go to use Microsoft Services these days. I haven't found any word on that this will replace the OneDrive API though.

Overall, I have a finished implementation in this branch: [https://github.com/olihey/rclone/commits/onedrive_graph](https://github.com/olihey/rclone/commits/onedrive_graph) and it seems to give people access to sides that weren't possible before. Problem is, the setup is a bit more complicated 😄 as I present 5 different options to add a drive. I have talked to one person on this subject and he only seems to be able to access his PRIVATE team site when using the search API but not the normal "list all sites" API call. So, again, it's Microsoft and very big and messy.
I am currently a bit stuck, the Tests all ran successful but I haven't got much input from users about this change and I only have a simple OneDrive for Business to test.

So, should I just do a merge request?

**Comment by ncw** [comment]
> I am currently a bit stuck, the Tests all ran successful but I haven't got much input from users about this change and I only have a simple OneDrive for Business to

What you could do is post a link for testing in the relevant open issues to get more testers - that is normally what I do.

> So, should I just do a merge request?

Well we could do that too!  The normal onedrive and the simple onedrive for business are the most common cases I think so as long as those are working, why not!

**Comment by olihey** [comment]
I was spending a bit time with the Microsoft Graph implementation a bit over the weekend and it seems the API is quite a bit buggy 😄 and not 100% ready for prime time.
I would suggest wait out what happens with the #1716 from Microsoft's side and then do a beta test with help of some users from the forum. So, sit and wait for now :)

**Comment by antonl** [comment]
I have built @olihey's branch and can confirm that auth works, provided that you know the siteID for the particular drive you're interested in. I'm on a Office365 Enterprise account, and have created a sharepoint site. Although I couldn't use the "search" feature to find the drive I wanted (it reported a Malformed Request), I found the siteID manually using the [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) with this search
```https://graph.microsoft.com/v1.0/sites?search="{my site name}"```
and then copying the siteID field. Unfortunately, I don't think a list of the site drives will work on enterprise accounts because that requires special permissions.

I can now list the remote files and sync. I'd be happy to test things out for you guys to help this be merged in! Is there a way to use the siteID with the old API while the Graph API is stabilized?

**Comment by olihey** [comment]
@antonl Thanks for the feedback. I am planning on continuing on this within the next days. So, it might be very helpful if you can try out things along the way.

Unfortunately the old implementation is only using the OneDrive API which only knows about driveIDs and not siteIDs, sorry!

**Comment by txchen** [comment]
@olihey May I ask about the progress of this? The graph api is the way to go, looking forward to it.

**Comment by olihey** [comment]
@txchen I didn't have time but @just-ak seems to have continued the development based on my work

Please look at #1770

**Comment by yonjah** [comment]
@olihey I was looking into @just-ak pull request (https://github.com/ncw/rclone/pull/2321) 
It seem like the api for the personal one drive is still the same. 
is this correct ?

Any way great job. 
The old API is so outdated it's really hard to find any documentation for it, I was really struggling with implementing https://github.com/ncw/rclone/pull/2369  because of that. so looking forward for it as well :-)

**Comment by ncw** [comment]
Arg, I've dropped the ball on #2321 

@yonjah - would you like to work with @just-ak to #2321 merged?

**Comment by yonjah** [comment]
I'll try to have a look over the weekend but it might require more time than I currently have available.

**Comment by Cnly** [comment]
Maybe I can provide some help on the upgrade as well. I have just managed to merge https://github.com/olihey/rclone/commits/onedrive_graph into master https://github.com/cnly/rclone/tree/graph and pass all the tests with a OneDrive for Business backend.

**Comment by Cnly** [comment]
@ncw I've read the code in #2321, but I'm not completely sure if we need to merge that - olihey's code is already working for Sharepoint sites it seems. All tests are passing with a Sharepoint backend as well.
Since I'm not a frequent user of Sharepoint either, I would like to know more about what's distinguishing Sharepoint and OneDrive backends.

**Comment by ncw** [comment]
@Cnly - OK thanks. Looking forward to your PR!

**Comment by Cnly** [comment]
I think this can now be closed. Thank you all for your help! :D
