### ISSUE TITLE
running multiple copies of rclone may cause it to fail to update token in config (and abort)

### ISSUE THREAD

**Issue by ljr9600** [ncw/rclone#2060]
When running multiple instances of rclone to upload to google drive on Windows, I have seen the error (a few times):

drive_r_copy.txt:2018/02/07 05:38:56 Failed to move previous config to backup location: rename C:\Users\xyz\.config\rclone\rclone.conf C:\Users\xyz\.config\rclone\rclone.conf.old: Access is denied.

It looks like 2 or more instances of rclone is trying to update the config file when a new token is recieved, and gets access denied (because one of them has locked the file to write or rename it).  This causes the process getting access denied to fail, and abort the whole rclone copy.

I think there should be a retry attempt here or the last one in gets to make the change. It should be ok since both instances of rclone will have the new token in memory, just one will fail to update it.

**Comment by ncw** [comment]
> I  think there should be a retry attempt here or the last one in gets to make the change. It should be ok since both instances of rclone will have the new token in memory, just one will fail to update it.

That would seem sensible, a retry after a random sleep should fix the problem.

**Comment by TenGumis** [comment]
I want to do that. Please write more how I should do that

**Comment by ncw** [comment]
Thanks for the offer @TenGumis 

The function which needs changing is [SaveConfig](https://github.com/ncw/rclone/blob/master/fs/config/config.go#L353)

What I would do is
  * rename `SaveConfig` to `saveConfig`
    * make it return an error
    * replace all the calls to log.Fatalf(...) with `return errors.Errorf(...)`
     * some of these can be converted to `errors.Wrap(err, ...)`
  * write a new `SaveConfig` which
  * calls `saveConfig`
  * returns if no error
  * otherwise retries fs.Config.LowLevelRetries times on an error
  * Does a sleep for a random number of milliseconds between 0 and time.Second after each retry
  * if after trying that many times it then calls log.Fatalf() with the error.
  
I suggest you have a go and send a pull request which I'll comment on and we can iterate :-)
