### ISSUE TITLE
Support for Azure Archive Blob Storage

### ISSUE THREAD

**Issue by kflu** [ncw/rclone#2091]
Opening a feature request per @ncw suggestion. [Here's][2] the original discussion thread. 

I would like to use rclone to back up to Azure [**Archive** blob storage][1] (cheapest cold storage service as far as I know). Since Azure blob storage container cannot set default blob tier to Archive, the clients must explicitly set the tier for the uploaded blobs to Archive after or during the uploads. However, it appears that rclone's Azure Blob storage implementation doesn't support this as of now.

It would be great to allow a configuration that [sets the tier of the blob][3] when uploading it. 

As Azure Archive Blob Storage is [so cheap][4] (half of Glacier's pricing at the moment), this would be quite a popular use scenario for rclone.

I'm not a go-lang dev, but I think it's not too hard for someone fluent in Go :) ? I'd be happy to test it if someone implements it!

[1]: https://azure.microsoft.com/en-us/blog/announcing-the-public-preview-of-azure-archive-blob-storage-and-blob-level-tiering/
[2]: https://forum.rclone.org/t/support-for-azure-archive-blob-storage/4891
[3]: https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-tier
[4]: https://azure.microsoft.com/en-us/pricing/details/storage/blobs/

**Comment by ncw** [comment]
Unfortunately this isn't supported yet by the libary rclone uses to access the azure blob storage.  The relevant issue is here: https://github.com/Azure/azure-sdk-for-go/issues/808

Otherwise it would be quite easy to add!

**Comment by kflu** [comment]
If we don't want to wait for the SDK support, another option would be to call the [Set Blob Tier REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-tier):

The URL to call is `https://myaccount.blob.core.windows.net/mycontainer/myblob?comp=tier`, then set the desired tier as one of the HTTP header: `x-ms-access-tier`.

**Comment by kflu** [comment]
Or, is there a way to configure rclone to invoke a command for every file it had just uploaded. And I would write a small executable `set-blob-tier` and hook them up?

**Comment by kflu** [comment]
Hi Nick @ncw , looks like the SetTier is supported in the base library. Is this a good time to incorporate it? Refer to: https://github.com/Azure/azure-storage-blob-go/issues/1

**Comment by hashbackup** [comment]
Read operations cost $5 per 10K for archive storage vs the regular price of $0.004.  If you ever actually need to get your data back, restoring 100K files is going to cost $50; restoring 1M files will cost $500.  This assumes each file only needs one read operation.

There is a double asterisk footnote beside "Read Operations", but the corresponding footnote is missing.  The write footnote, describing what MS considers a write operation, is there:
```
*The following API calls are considered write operations: PutBlob, PutBlock, PutBlockList, AppendBlock, SnapshotBlob, CopyBlob, and SetBlobTier (when it moves a Blob from Hot to Cool, Cool to Archive, or Hot to Archive. Learn more).
```
It's not clear on the pricing page which API calls are considered a "Read Operation", but I did find it described on the MS Pricing Calculator page:
```
The following API calls are considered Read Operations: GetBlob, SetBlobTier (when it moves a Blob from Archive to Cool, Cool to Hot or Archive to Hot).
```
Their FAQ has an example for restoring from Archive storage:
```
A blob cannot be read directly from the Archive tier. To read a blob in Archive, a user must first change the tier to Hot or Cool. For example, to retrieve and read a 1,000-GB blob in Archive that has been in the Archive tier for 90 days, the following charges would incur:

Data retrieval (per GB) from Archive: $0.02/GB-month x 1,000 x 1 GB = $20

Rehydrate operation (SetBlobTier Archive to Hot): $5/10k x 1,000 = $0.50

Early deletion charge: (180 - 90 days) x $0.002/GB-month x 1,000 x 1 GB = $6

Read blob operation from Hot = $0.004/10k * 1,000 = $0.0004

Total = $20 + $0.50 + $6 + $0.0004 = $26.51
```
I don't understand this at all.  The example says it is a 1000-GB (1TB) blob - a single blob.  Yet they are charging for 1000 Rehydrate operations.  It seems to me that this should be only 1 Rehydrate operation.  Is Rehydrate per GB or per blob?  Or it could be both: a per-GB charge with a minimum of 1 per blob.

In this example, they neglect to include bandwidth pricing @ $0.087 per GB, so add another $87 to that $26.51 fee.

The other gotcha is that they are charging for a minimum of 6-months storage, so the only way you get the cheap storage rate of $0.002/GB/month is if you leave the data there for 6 months.  If you store data for a month and remove it, it'll cost you 6x the cheap rate, or $0.012/GB/month.  For an offsite copy of data that rarely changes, this might work fine.  But a real backup system has retention policies: data expires and needs to be removed.  With Azure, nothing can be removed for 6 months, so you may be paying for data you no longer need.

In contrast, Backblaze B2 does not have any of these early deletion penalties or retrieval fees, and storage cost is _always_$0.004/GB/month.  Their outbound data transfer cost is 1/9th Azure: $0.01/GB.  Downloading a 1TB blob from Backblaze would cost $10 vs $113.51 for Azure Archive storage.

I think Azure Archive storage pricing is really going to hurt is when there are a lot of small files and that Rehydrate operation occurs millions of times.  They should do an example of using rclone to clone the Linux kernel git repo to Azure Archive storage and then retrieving it.  That would be an eye opener.

**Comment by kflu** [comment]
For my scenario, I have far less than 100K files to restore. I have less than 2TB consisting of around 20K files. These are last resort backup for me. According to my research, Azure Archive is the best option for my scenario. 

I think few people will have the 1M **number** of files scenario to worry about. It's even less likely that even if someone is at that scale, that s/he wants to retrieve **all** of these files. Not to mention at that scale, I'm not sure if rclone is even a good fit for them.

But at any rate. I understand people have their own scenarios. So I'm not trying to speculate. But I just want to share my scenario and my point of view.

**Comment by hashbackup** [comment]
Since you work at Microsoft, maybe you can clarify about Azure's Read / Rehydate / SetBlobTier fee: it seems like it should be a per-blob cost, since it has units of $ per operations, but in the example of restoring a 1TB blob, it gets multiplied by 1000, implying it is a per-GB cost.  Is the pricing example wrong?  

The other possibility I can think of is that it is a per-blob cost, but if a 1TB blob was actually uploaded as 1000 1-GB blobs, then when the large blob is rehydrated, Azure charges the rehydrate fee for each sub-blob.

**Comment by hashbackup** [comment]
I tried using the Azure Pricing Calculator for blob storage, hot access tier, retrieving 1000GB, and it said the cost is $21.84, with a retrieval cost of $0.00 and no bandwidth charges listed.  However, their [bandwidth pricing page](https://azure.microsoft.com/en-us/pricing/details/bandwidth/) explains that bandwidth costs for data egress is $0.087/GB, so I believe the pricing calculator is not including bandwidth costs at all.

In Amazon Glacier, retrieval costs are completely separate from bandwidth costs.  I'm guessing the same applies to Azure Archive storage.

**Comment by hashbackup** [comment]
I goofed: that $21.84 is mainly storage costs, but still, bandwidth is not included in the pricing calculator, even for hot tier storage.

**Comment by sandeepkru** [comment]
You are right, bandwidth charges are included when you move data out of Azure Data Centers similar to Amazon Glacier.

**Comment by sandeepkru** [comment]
@ncw - I can add this functionality, let me know if you have any preferences in here. I can add a global flag `--azure-storage-class` which can be supplied in commands like `sync`, `copy`, `copyto`, `move`, `moveto`. This can support to tier all blobs in provided container to supplied storage class, ideally it would be nice to do this on specific blob name regex, instead of all blobs in a container. Please let me know if you have any suggestions before I start working on this.

**Comment by ncw** [comment]
@sandeepkru I don't think the SDK rclone is using at the momemt https://github.com/Azure/azure-sdk-for-go supports Tiering does it?  Wheras the new blob SDK https://github.com/Azure/azure-storage-blob-go does.

So to implement this might first mean porting rclone from the old SDK to the new one.  This is probably a reasonable amount of work.

Unless you had a different plan?

**Comment by sandeepkru** [comment]
@ncw , you are correct. I quickly realized soon after started working on this. Since https://github.com/Azure/azure-sdk-for-go this is getting deprecated it may be good idea to start porting rclone to use new blob SDK. I can work on this and will send out two separate PRs, one for moving to new SDK and other one on Tiering changes. Please let me know if you have another issue opened on on porting to new sdk or if anyone else already working on it.

**Comment by ncw** [comment]
@sandeepkru wrote:
> Since https://github.com/Azure/azure-sdk-for-go is getting deprecated it may be good idea to start porting rclone to use new blob SDK. I can work on this and will send out two separate PRs, one for moving to new SDK and other one on Tiering changes. 

That would be fantastic

> Please let me know if you have another issue opened on porting to new sdk or if anyone else already working on it.

I don't and I don't think anyone is working on it.  If you'd like to open a new issue for the port that would be great.

You'll want to run the integration tests as you go along - see the docs here: https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#testing

If you can make the backend/azureblob tests pass then it is likey that the others will pass too!

Note also that there are some pending azureblob changes in #2118 which I'm hoping to merge shortly.  The SAS URL bit of it doesn't work yet though :-(

**Comment by sandeepkru** [comment]
Thanks Nick, I opened new issue, please add/modify if you think any additional details are required. I'll start on this soon and send out PR against #2362 first. I've gone through contributing doc and will follow all guidelines.

**Comment by sandeepkru** [comment]
@ncw Apologies for delaying on this. Here is what I've now, let me know if I can proceed and send out pull request.
Azure Storage currently supports three access tiers on blobs `Hot`, `Cool` and `Archive`. I have added a new option to configuration called `access_tier`. By default, this value is set to `None` means, all blobs get tiered to default tier which set at the time of account creation. Currently Azure Storage supports this default tier as either `Hot` or `Cool`. It's mentioned here [Access Tier FAQs](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-storage-tiers)
> Can I set my default account access tier to archive?

> No. Only hot and cool storage tiers may be set as the default account access tier. Archive can only be set at the object level.

When user explicitly sets `access_tier` to `Hot` or `Cool` or `Archive` and if invoked data transfer operations `sync`, `move`, `copy` etc. with remote as `azure endpoint` , we can explicitly perform `SetBlobTier` on all those objects if object is not already in desired tier. 
I have changes up to this point, without unit and integration tests. I tested manually with azure endpoint.
****************
Open questions
To restore objects from archive, users should tier blob to `Hot` or `Cool` - This typically takes few hours as per [Azure Storage SLAs ](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-storage-tiers)
- What kind of feedback should we have in `rclone` to effectively convey this to users?
            
         -  `GetBlobProperties` shows provides status of restore, we can include this information in commands like ls

- Data Transfer operations will fail if source is `azure endpoint` and if all objects are in `archive` tier? How to handle this gracefully? Shall `rclone` throw error and continue ?
- If objects already exists in remote but not locally, how should be support setting tier? `sync` first to local and perform `sync` again with `access_tier` flag?
- Extended feature - If we can introduce a regular expression matching on blob names and change tier only for those matched ones instead of changing tier on all objects with in a container or directory? - This may be applicable to `copy` ,`move` type of operations as well. Not sure, there is already existing feature or ask on this already.
****************
Please let me know your thoughts on these and we can proceed accordingly.

**Comment by ncw** [comment]
> What kind of feedback should we have in rclone to effectively convey this to users?

Hmm a good question...

> Data Transfer operations will fail if source is azure endpoint and if all objects are in archive tier? How to handle this gracefully? Shall rclone throw error and continue ?

Returning an error is the correct thing to do .  Presumably we'll get an error back from Azure anyway.

> If objects already exists in remote but not locally, how should be support setting tier? sync first to local and perform sync again with access_tier flag?

This is the difficult question.  There are other backends that support this kind of thing (like S3 and the [OVH cloud archive](https://www.ovh.co.uk/public-cloud/storage/cloud-archive/)).  Can you have a look at the semantics of those.

Perhaps another rclone command `rclone set-tier` might be the thing, which iterated through Object~s and called an option `SetTier` method on the objects.  You'd be able to choose which blobs you changed with all the [rclone filters](https://rclone.org/filtering/)

Sorry if the above is a bit incoherent it was written in haste!

**Comment by sandeepkru** [comment]
> Returning an error is the correct thing to do . Presumably we'll get an error back from Azure anyway.

Will do, thanks. Yes, Azure returns error in that case.

> This is the difficult question. There are other backends that support this kind of thing (like S3 and the OVH cloud archive). Can you have a look at the semantics of those.

Will check, thanks for the pointers.

> Perhaps another rclone command rclone set-tier might be the thing, which iterated through Object~s and called an option SetTier method on the objects. You'd be able to choose which blobs you changed with all the rclone filters

Recently came across rclone filters, thanks. A separate rclone command will solve many problems, and same idea crossed my mind, but I didn't like idea of having separate command just to support one backend since this is very specific to Azure Storage, and currently rclone doesn't seem to have any such non generic command. Please let me know what do you think(?) If we want to move forward with separate command, I can implement those changes and send out in next iteration.

**Comment by ncw** [comment]
>  A separate rclone command will solve many problems, and same idea crossed my mind, but I didn't like idea of having separate command just to support one backend since this is very specific to Azure Storage, and currently rclone doesn't seem to have any such non generic command. Please let me know what do you think(?) If we want to move forward with separate command, I can implement those changes and send out in next iteration.

I think a separate command is the right thing to do.  Commands are easy to make and it would be great if it supported other cloud storage providers.

Let's get your basic tier support merged then we can have a go at a separate command.

**Comment by sandeepkru** [comment]
Sounds good, will send out new iteration soon.

**Comment by kflu** [comment]
OK just wanted to share out the way I addressed this problem. As my go-lang knowledge is limited to only fixing this problem and I don't have a lot of time doing bigger changes, I forked rclone, added a command line option `--on-synccopy`. What this option does is that it takes a path to a program as a callback. When a file is successfully "synced/copied", this program will be invoked by rclone, passing the file's remote path to it as the first argument. 

With this, I invoke rclone like so:

    rclone copy /data azure:data --on-synccopy "$BASEDIR/../fixtier/fixtier.sh"

Where `fixtier.sh` is a wrapper of my C# program that sets the tier for the file just synced by rclone.

I now like this approach better than adding any provider specific logic into core rclone because it's much flexible and can cater for many use scenarios that can't be foreseened by rclone devs. It's basically an automation extension point for rclone. And I'd love to see rclone having more extension points like this in the future to be more controllable by automation.

My change to this is in https://github.com/kflu/rclone/commit/4e05ae18a5e706c8c08dfc2b234a6f3b9b089683. Let me know if you guys feel like a PR but I basically hacked it up so it's better if someone can rewrite this in a "proper" way.

**Comment by ncw** [comment]
@kfu - very ingenious :-)  @sandeepkru 's changes will work exactly for your use case - they do effectively the `fixtier.sh` but in the backend.

The idea of an `--on-synccopy` flag is an interesting one and it isn't the first time this sort of thing has come up.  I think a general purpose set of hooks is an interesting idea (eg pre-copy, post copy, pre-delete, post-delete).  Fancy making a [new issue](https://github.com/ncw/rclone/issues/new) to discuss further?

**Comment by sandeepkru** [comment]
@kflu - Now, `rclone` has `--access-tier` flag and a new command `settier` to perform tier changes on azure blob storage. Can you please check if it addresses what you were expecting so that we can close issue?

**Comment by ncw** [comment]
I'm going to close this now as I think it is done.
