### ISSUE TITLE
Option “–s3-disable-checksum” 

### ISSUE THREAD

**Issue by sparrowjack63** [ncw/rclone#2213]
Hi,

Cheksum take a long time before uploading data. With bigs files, this time is really high.
Please could you add an option like “–s3-disable-checksum” to let the users make the choice of doing a checksum or not when uploading or downloading data ?

Thanks,

**Comment by ncw** [comment]
@sparrowjack63 do you want to have a go at this?

**Comment by sparrowjack63** [comment]
I'm not experienced enough to go, but I will look at the changes made to learn and try to do it alone next time.

**Comment by ncw** [comment]
@chris-redekop this is the, perhaps inevitable, consequence of your change 4dd1e507f4204bda949c12766bfe8012bf03dc16

Do you fancy putting in a flag to turn it off?

Here is some more background from the forum: https://forum.rclone.org/t/long-time-before-start-uploading-data/5278

Or another possibility is to add the metadata after the file has been transferred.  The local Fs will calculate the checksum as it goes along in that case so it won't cause a big up-front delay.

I'm not sure what consequences for billing updating metadata for S3 files has as it involves doing a COPY though.

**Comment by ncw** [comment]
...And if we calculate the hash when streaming through the s3 backend (rather than reading the source hash) then it will fix hashes missing when uploading to a crypt backend and hence to s3.  

See [forum thread](https://forum.rclone.org/t/how-to-identify-files-that-cant-be-cryptcheck/5206/12)

**Comment by sparrowjack63** [comment]
It could be a good way to calculate hash when streaming. If it could delete the delay before the upload, it will be interresting.

**Comment by chris-redekop** [comment]
Sure, I can take a look, @ncw.  Thanks for looping me in.

For my own context, I'll recap how we got here and where rclone has gone since #1926:

1. The original motivation for #1926 was to verify rclone large-file uploads, according to https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/ .  This article indicates that the MD5 must be calculated **before** the upload.  The work in #1926 is my take on this AWS article.

2. After we were some way toward #1926, @ncw  found that the AWS API *already* pre-hashes and verifies the upload.  This is discussed in #523 and in https://docs.aws.amazon.com/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html.

3. Note that 2) alleviates the need for 1), but we kept 1) for a different use case: verifying the MD5 some time after uploading.  Note that we don't need to **pre-**compute the MD5 for this use case, but there are other reasons to do so.  (I'll discuss these below.)

4. From the forum post, @ncw, I get the impression that rcrypt large-file checking is now relying on a fixed chunk size and the ETag.  Did I get that right, or what is `--s3-chunk-size` for?

>> So as of now running “rclone cryptcheck --fast-list --verbose /path/to/files encryptedremote:path/to/files” is expected to return “X hashes could not be checked” for any files over 5 MB?

>Yes. You can move that threshold with the latest beta using
> `--s3-chunk-size int                   Chunk size to use for uploading (default 5M)`


So now we have large files that have an MD5 sum, but it requires streaming a file twice--once for the MD5, and once to transfer--which isn't optimal.  What are our options?

1. Add a `–s3-disable-checksum` option to turn off the calculation altogether.  This seems heavy handed, but could be a good compromise if we decide to keep MD5 pre-calculations.

2. Calculate the MD5 during uploading and send it as S3 object *metadata* **after** the upload is complete.  A con of this one is the $$$ price: an S3 object and its metadata are considered an immutable pair and so a new (object + metadata) pair would need to be created when the MD5 is uploaded.  As @ncw mentions, this increases transaction costs:

> I'm not sure what consequences for billing updating metadata for S3 files has as it involves doing a COPY though.

Even more important for users like me, who use versioned S3 buckets as secondary backup, is the extra storage cost: uploading the MD5 after means another full (object + metadata) version is put in the history, thus **doubling** the storage cost of each object.

3.  Calculate the MD5 during uploading and send it as an S3 object *tag* **after** the upload is complete.  Tags are different from object metadata in that they can change separately from object.  This feature addresses the $$$ cons of 2).  The only con is minor: their intended more for categorization and less for arbitrary metadata.  See https://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html

4. I asked above, @ncw, is the latest beta you using fixed chunk size + ETag for verification?  The con here are ETag's now well understood limitations: rclone can't control the chunk size for any objects that it cannot create, and the ETag does not hold the object's MD5 when the object is KMS encrypted.  (Third parties may KMS encrypt a bucket that  we want to manage with rclone?)


What do you think?  Did I miss any?  What are your preferences?

My preference is 1), as it's complete, and most consistent with AWS's body of documentation.  I also think 3) is complete and workable.  I wouldn't use 2) as it would double my storage costs.  I don't think 4) is complete--it doesn't address third-party chunk size, nor KMS encryption.

**Comment by sparrowjack63** [comment]
Some users like me are using rclone with "on premise" S3 compatible solution (like ceph).
So for this case, we dont care about the $ of calculating MD5 during upload.

**Comment by ncw** [comment]
Thanks for taking a look at this @chris-redekop 

There are several related problems here:
  * long time before initial upload of large file
  * hashes missing for crypt uploads (making cryptcheck useless)
  * hashes missing for rcat/mount uploads

> From the forum post, @ncw, I get the impression that rcrypt large-file checking is now relying on a fixed chunk size and the ETag. Did I get that right, or what is --s3-chunk-size for?

No that isn't correct.  `--s3-chunk-size` allows the user to vary the size of the multpart upload chunks.  The Etag is done as metadata as before.

Maybe what we should do is option 1) to turn it off and...

A hybrid option 2) -  do exactly what we are doing now, so reading the MD5 from the source object and using that if available.  That is cheap and easy.  However if the MD5 hash isn't available at that point in time, then we could calculate it as we stream it and add it as metadata after with the COPY+update metadata.

According to [the pricing page](https://aws.amazon.com/s3/pricing/) a COPY costs the same as a PUT or a LIST operation `$0.005 per 1,000 requests` - I don't think there is a per byte cost.

I note that you can't copy an object bigger than 5GB without using the multipart upload so that is a bit of a nuisance! rclone already uses this to set the modtime of an object and I hadn't noticed that bit of the docs until now.

I don't know anything about S3 tags - it sounds like they added that feature to support Amazon Cloud Drive!  These seem to cost `$0.0004 per 1,000 requests` assuming they are in the Other category.  I wonder if all/any of the S3 compatiable offerings (CEPH/Digital Ocean/Wasabi) support tagging? That might be a good reason not to use tagging.

**Comment by ncw** [comment]
> Why would a user want to do this? (I could only think of it helping with ETag-based rclone checks.)

Bigger chunks means rclone goes faster.

> I'm trying to put the MD5 pre-calculation in this context. Does the MD5 pre-calc block hashes for rcat/mount, or (how) is the MD5 pre-calc related to rcat/mount?

rcat/mount don't have the file at the point that the current s3 backend code asks for the MD5SUM so they can't return it.

----

Option 1) is safe for definite.

Another idea: Maybe we should bring back the `--s3-upload-cutoff` which can use the old [single part upload](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) for small uploads (below that threshold).  I think this is good to 5GB.  This will always have an ETag which is a valid MD5SUM and rclone will check the MD5SUM when it is uploaded. That is how rclone used to work before I cut over to using the official SDK.

Uploading like this isn't as robust as the multpart upload, but it could be as quick or quicker as it gets to stream lots of TCP data.

You can optionally give it a Content-MD5 to check on upload too if you have it at the point of creating the request.

That might be a better solution, or an additional part anyway...

**Comment by chris-redekop** [comment]
> Bigger chunks means rclone goes faster.

👍 

> rcat/mount don't have the file at the point that the current s3 backend code asks for the MD5SUM so they can't return it.

Interesting...

---

OK, I will take a look at adding that flag.  I'll use `--s3-disable-checksum`, as suggested, for now.  Just let me know if you'd like a different name.

On the `--s3-upload-cutoff` option and relying on the ETag; during our earlier conversation I convinced myself that the ETag is not the way to go.  (It's dodgy at best and doesn't address some well-known cases.)  Using the ETag might help a bit in this case, but I don't think it can be a complete sol'n.
