### ISSUE TITLE
Can't copy files to different name

### ISSUE THREAD

**Issue by travisgroth** [ncw/rclone#227]
When I try to copy an individual file named 'foo' to a destination called 'ACD' (an Amazon Cloud Drive endpoint) and name the file 'bar', I get unexpected results.  Instead, I get the file 'foo' contained within the directory 'bar'.

```
$ rclone ls ACD:Testing/

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       500ms
$ touch foo
$ rclone copy foo ACD:Testing/bar
2015/11/19 01:00:22 Amazon cloud drive root 'Testing/bar': Building file list
2015/11/19 01:00:23 Amazon cloud drive root 'Testing/bar': Waiting for checks to finish
2015/11/19 01:00:23 Amazon cloud drive root 'Testing/bar': Waiting for transfers to finish

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        2.4s

$ rclone ls ACD:Testing/
        0 bar/foo

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       800ms
```

I would expect rclone to work like rsync for individual files and simply rename the file on the destination.

**Comment by ncw** [comment]
This is expected behaviour - I agree it is counter-intuitive.

I really need to rethink the way rclone handles files - at the moment it handles files as a directory with everything except that one file excluded.

I shall ponder!

**Comment by nioncode** [comment]
Hope to see this soon. I am using rclone in a script and currently have to do
```
cp real_file_name desired_file_name
rclone copy desired_file_name remote:folder
rm desired_file_name
```

**Comment by ncw** [comment]
Now that rclone is using cobra it is really easy to make another command copyfile

This could be used like

    rclone copyfile /path/to/file remote:dir/newfilename

I'd make movefile too for renaming files. 

What would you think you of that?

**Comment by ncw** [comment]
PS note you could improve your script by doing

    ln  real_file_name desired_file_name

Instead of cp

**Comment by nioncode** [comment]
I'd rather have the default `copy` command recognize that it is a file that is being copied, not a directory and thus treat the destination as file name, except when a `/` is the last character.

Example:
`rclone copy /path/to/file remote:dir/newfilename` puts file into dir, but renames it to _newfilename_.

`rclone copy /path/to/file remote:dir/` puts file into dir.

In general, this should also apply to directories. This would change current rcopy syntax, though (as it always assumes trailing `/`), so I don't know if this is feasable. But rather now than later :)
Otherwise, I'm also fine with a new command.

However, I think this should also be supported for directories, so that we can upload a directory as another name.
Maybe a flag for `copy` (and `sync` and all other commands) that treat the final path segment as destination name and not its parent folder might be better then? 

> PS note you could improve your script by doing `ln`

Sure, the script was just an example for the current limitation.

**Comment by ncw** [comment]
I'm going to make two new commands `cp` and `mv` which work exactly like their unix counterparts.

I've made a prototype but I'm running out of time for this release so I'm going to bump it into the next.

**Comment by ncw** [comment]
I changed my mind after some effort trying to implement the semantics of `cp` and `mv` which really don't fit a system that needs lots of retries (they aren't idempotent).

So I implemented `moveto` and `copyto` as originally planned.

Find a beta here http://beta.rclone.org/v1.34-43-gc265f45/ (will be uploaded in 15-30 mins).
