### ISSUE TITLE
dropbox error. failed to open source object: path/restricted_content/

### ISSUE THREAD

**Issue by tliderek** [ncw/rclone#2301]
#### What is the problem you are having with rclone?
Some files are giving the error:
Failed to copy: failed to open source object: path/restricted_content/..

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.40
- os/arch: linux/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
- os/arch: linux/amd64

####  Which cloud storage system are you using? (eg Google Drive)
Dropbox

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync -v Dropbox: Transfer:_fromdropbox/

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/05/09 00:18:01 ERROR : Fonts/Avenir LT/AvenirLTStd-Medium.otf: Failed to copy: failed to open source object: path/restricted_content/..

**Comment by ncw** [comment]
This error is caused by [dropbox's copyright detector](https://techcrunch.com/2014/03/30/how-dropbox-knows-when-youre-sharing-copyrighted-stuff-without-actually-looking-at-your-stuff/).  It thinks your file is copyright for some reason.

If you disagree, then I recommend you report on the dropbox forum - eg [see this example](https://www.dropboxforum.com/t5/API-Support-Feedback/409-restricted-content-being-returned-for-files-which-are-not/td-p/221892).

**Comment by tliderek** [comment]
Ah, so user error on our part. I searched the forums and the rclone documentation but didn't find an explanation for this.

**Comment by ncw** [comment]
@tliderek Do you fancy sending a pull request for the docs to explain more?

Perhaps add a paragraph in the [Limitations section](https://github.com/ncw/rclone/blob/master/docs/content/dropbox.md#limitations)?
