### ISSUE TITLE
OneDrive can't generate a token

### ISSUE THREAD

**Issue by 99junlin99** [ncw/rclone#2325]
#### What is the problem you are having with rclone?
I can't see token. It prompt me in this image.  
![qq 20180531124412](https://user-images.githubusercontent.com/35255028/40761965-c1c6a85a-64d0-11e8-864f-7f346f1a7a4f.png)

#### What is your rclone version (eg output from `rclone -V`)
1.41 from github

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64bit

####  Which cloud storage system are you using? (eg Google Drive)
onedrive business

**Comment by ncw** [comment]
In the title bar it says "using rclone is not supported because your organization is in an unmanaged state".

To fix this you need to persuade your administrators to get your organization into a managed state (unlikely) or switch to using [webdav which will work with unmanaged organizations](https://rclone.org/webdav/#sharepoint).

See also #1975 where this was originally discussed.

**Comment by ncw** [comment]
This has been made a lot more obvious by #2331 so I'm going to close this now.
