### ISSUE TITLE
headless installations need easier authentication

### ISSUE THREAD

**Issue by utdrmac** [ncw/rclone#233]
I've installed rclone on to my headless NAS. Bit of a pain to get Amazon Cloud Drive authentication working because the webserver used only binds to 127.0.0.1. First tried installing lynx and that got me all the way to the Amazon page to auth rclone but failed after that.

So I had to use curl --verbose to see how rclone was doing the 302 redirect, copy/paste that into my desktop browser, do the auth, which then redirects you to a 127.0.0.1 address again, which I had to copy/paste back in to lynx and finally auth is completed.

Needs to be an option to bind to another IP on the machine or give the URL on screen in an easy-to-copy way.

**Comment by ncw** [comment]
I'm sorry you are finding the process painful!

The webserver only binds to 127.0.0.1 because that is what I told amazon when setting up oauth for rclone.  I can't supply different addresses for the redirect URL unfortunately on a case by case basis.

I could show the actual URL instead of the rclone internal one - that would work fine for google drive (for example) which doesn't require the last redirect, but wouldn't work for amazon cloud drive which does require that last redirect.

What I normally suggest people do with NAS is configure it on their desktop machines and copy the config file - see the second question in the [FAQ](http://rclone.org/faq/).

I did manage to make it work with `w3m` a slightly more modern text based browser than `lynx` though.

Unfortunately the oauth2 protocol was really designed to be used in a web browser :-(

**Comment by danzig666** [comment]
I authenticate on my desktop, then copy .rclone.conf to the headless server/vps. Easy.

**Comment by dibu28** [comment]
same, created .rclone.conf once on my desktop and copied to as many vps/desktops as needed.

**Comment by ncw** [comment]
I'm going to close this as I think that copying the config file should be the best way to fix this.

Thanks for the report

Nick

**Comment by klauspost** [comment]
Since this is likely to pop up frequently, even if it is added as FAQ, I may look into making it slightly more smooth.
