### ISSUE TITLE
What are the default DropBox App permissions?

### ISSUE THREAD

**Issue by danishgoel** [ncw/rclone#239]
Thank you for making this wonderful utility :heart:

After some searching I was unable to determine what type of [App permissions](https://www.dropbox.com/developers/reference/developer-guide) are used by rclone's default Dropbox app, *'App Folder' or 'Full Dropbox'*?

I'll be using rclone to backup files from my web server to Dropbox and would like it to only have App Folder access.

Would I need to create my own App on Dropbox and use it's App key and secret during configuration of the new source?

**Comment by ncw** [comment]
rclone asks for Full dropbox permissions.

Note that it is only the rclone app you have on your computer that has these permissions - neither I nor rclone.org get to see or know anything about it.

You could create your own App on Dropbox and use its App key and secret and that should work for an app with only "App Folder" permissions.  I haven't tried it though so it might go wrong in unexpected ways!  If it does then file an issue :-)

**Comment by danishgoel** [comment]
Yes, I realize that the permission is only for the rclone app on my computer.
But, if my webserver is somehow compromised, I don't want the hacker to to gain access to the whole of my Dropbox.

I'll try rclone with App Folder permission and let you know how it goes.

Thank you :smile:

**Comment by danishgoel** [comment]
Reporting back the result of using rclone with custom app with "App Folder" only access.

**It is working great** :+1: 
The App folder is considered as the root by rclone and all seems to be working in order.

Thank you :)

**Comment by ncw** [comment]
Great! That is good to know - thanks for reporting back. Nick

**Comment by ahmadawais** [comment]
I confirm that it works.

1. Setup an app https://www.dropbox.com/developers/apps/
2. In your server you want to backup start the process of config again and use the `App key` in place of `Dropbox Client ID` and similar with secret and in your app at Dropbox put `http://localhost:53682/` as one of your redirect URIs
3. Then your machine will ask you to do `rclone authorize "dropbox" "key here" "secret_here"
4. Configure that and after allowing access to only it's own folder you can then paste that json into your machine :)

**Comment by hozza** [comment]
> Note that it is only the rclone app you have on your computer that has these permissions - neither I nor rclone.org get to see or know anything about it.

This is really good to hear @ncw, after a quick look at the rclone project I was not sure if you/authors, and/or your company, may technically have access to all users files via the rclone Dropbox app which gets authorised with full-permissions.

Super handy to know for someone unfamiliar with the Dropbox ecosystem - *it's permissions are limited to your local install*, rather than some system the rclone authors control.

I think it would be great to clarify this on the rclone/dropbox instruction page, especially as any searches for **rclone privacy** or **rclone security** turn up little results. 

Hopefully this reply will help others find this answer in search results!
