### ISSUE TITLE
Unable to copy a single file Google document from Google Drive - again

### ISSUE THREAD

**Issue by cjnaz** [ncw/rclone#2399]
It appears that this bug is back: https://github.com/ncw/rclone/issues/1772 

I tried on release 1.42 and the latest beta:

$ ./rclone -V
rclone v1.42-035-g99201f8b\u03b2

os/arch: linux/amd64
go version: go1.10.1
$ ./rclone lsl GDrive: --max-size 0
-1 2018-07-14 14:14:55.229000000 newsheet.xlsx
$ ./rclone copy GDrive:/newsheet.xlsx .
2018/07/14 16:39:32 ERROR : Attempt 1/3 failed with 0 errors and: object not found
2018/07/14 16:39:33 ERROR : Attempt 2/3 failed with 0 errors and: object not found
2018/07/14 16:39:33 ERROR : Attempt 3/3 failed with 0 errors and: object not found
2018/07/14 16:39:33 Failed to copy: object not found
[cjn@Shop tmp]$ ./rclone copy GDrive: . --include newsheet.xlsx
[cjn@Shop tmp]$ (success)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Centos 7 64bit

**Comment by cjnaz** [comment]
Reference [https://forum.rclone.org/t/unable-to-copy-a-single-file-from-google-drive-again/6164](https://forum.rclone.org/t/unable-to-copy-a-single-file-from-google-drive-again/6164)

**Comment by cjnaz** [comment]
Verified working correctly on
rclone v1.41
- os/arch: linux/amd64
- go version: go1.10

**Comment by ncw** [comment]
Thanks for making an issue about this.

A bit of git bisect shows that this is the problem commit

e42edc8e8c45a29d302dff9f36654910f070bf95

This commit causes the `copy` to run through a different part of the drive backend exposing this bug which has been there all along.

What needs to be done is that the code which mangles the google drive file names needs to be pushed into a lower level, so the code in `List` needs to be pushed into `list` so all callers of `list` get to know about google docs.

(Note also that if `NewFs` returned `Fs, Object, error` instead of `ErrorIsFile` then the code in `CopyFile` could use it directly instead of having to look it up again).

**Comment by ncw** [comment]
This should be fixed here - thanks @B4dM4n - let us know if you find a problem with it.

https://beta.rclone.org/v1.42-059-gdd670ad1/ (uploaded in 15-30 mins)
