### ISSUE TITLE
Server Side copy/sync between team drives

### ISSUE THREAD

**Issue by espiman** [ncw/rclone#2728]
Hi.

As you indicated in the following [thread](https://forum.rclone.org/t/server-side-copy-sync-between-team-drives/7128/6?u=espiman), I open a new case.

Is there any way to server side copy/synchronize 2 team drives or 1 team drive with 1 drive?

With 2 drive accounts it is possible using the same remote in source and target, with the target being a shared folder of the other drive account:

rclone copy drive1:/data drive1:/sharedFolderInDrive2 …

I currently use the Air Explorer tool and it allows to do it.

Thank you very much.

Regards,
Diego

**Comment by ncw** [comment]
For two teamdrives the problem with this is that even though `drive1` and `drive2` are pointing to the same drive account, rclone things they are different and won't sever side copy things between them.

For one drive with the `--drive-shared-with-me` flag, the flag applies to both instances of the drive backend so this fails too.

To fix this needs the constraint relaxing that remotes must be identical for server side copy.  However rclone needs to know that both drives belong to the same "account" otherwise the server side copy will fail (or maybe it won't - not sure!).

**Comment by espiman** [comment]
Perhaps, if when configuring the user account you see all the team drives that the user has access to instead of having to configure a team drive independently.

rclone copy drive1:/td1/folder drive1:/td2/folder

thank you

**Comment by alebupal** [comment]
Hello! this is very interesting. Is there any progress on this?
a greeting!

**Comment by ncw** [comment]
> Hello! this is very interesting. Is there any progress on this?

Not at the moment :-)  Would you like to help?

**Comment by ncw** [comment]
> Hi, how can I help you?
> 
> I have experience in python.

If you'd like to work on the code, then I suggest you check out the rclone code, get it building then take a look at the `backend/drive/drive.go` code.

Firstly I would experiment with relaxing this constraint

https://github.com/ncw/rclone/blob/a6c28a5faa076d829c2ed330bf994b665763def7/fs/operations/operations.go#L269

Comment out the `&& SameConfig(src.Fs(), f)` and see if you can make it work.
