### ISSUE TITLE
Rclone assumes passwords provided in environment variables are obfuscated

### ISSUE THREAD

**Issue by mholt** [ncw/rclone#2733]
First, thank you for rclone. It's immensely useful and your work is really incredible!

#### What is the problem you are having with rclone?

I can't seem to use Jottacloud backend with the correct password when configured via environment variables. It seems to try to decrypt the password, but since I'm not storing it on disk I don't need it encrypted. This also seems to be the only provider (of the several I've used so far?) that requires an encrypted password when configured via environment variables.

Is there a way to tell rclone to accept the password as plaintext? Or if it needs to be encrypted, how should that be done so rclone can decrypt it?

#### What is your rclone version (output from `rclone version`)

```
rclone v1.44-DEV
- os/arch: darwin/amd64
- go version: go1.11
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS - 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Jottacloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`RCLONE_CONFIG_JOTTACLOUD_TYPE=jottacloud RCLONE_CONFIG_JOTTACLOUD_MOUNTPOINT=Archive RCLONE_CONFIG_JOTTACLOUD_PASS=my-password-yes-its-correct RCLONE_CONFIG_JOTTACLOUD_USER=my-email@example.com rclone copy /foo jottacloud:foo`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/11/09 09:55:37 Failed to create file system for "jottacloud:foo": couldn't decrypt password: input too short when revealing password - is it obscured?
```

**Comment by mholt** [comment]
PS. I am willing to contribute code, like, today and now, if you can help me decide a good way to handle this. I can think of 2 options so far, maybe you know a better one:

1. If decryption fails, assume the password is already plaintext and just try it anyway. (easy)
2. Check whether config came from environment variables. If so, assume plaintext?

**Comment by mholt** [comment]
Actually, I found my answer: https://sourcegraph.com/github.com/ncw/rclone@9322f4baef55380a88d2a5d5ce2fa1c12f7e51f0/-/blob/fs/config/obscure/obscure.go#L48

I can use that function to obscure the password and set it in the environment variable. This works. :tada:

However, I don't like hard-coding this special case:

```go
if remoteType == "jottacloud" && key == "PASS" {
	val, err := obscure.Obscure(val)
	if err != nil {
		return err
	}
}
```

So my request still stands, if there's a way to accept plaintext passwords from env variables.

Also I wonder if I found another bug in Jottacloud. When the username has a `+` in it (my email address does), I get this fun error back:

```
2018/11/09 11:08:44 Failed to create file system for "jottacloud:foo": couldn't get account info: failed to get endpoint url: error 400: java.lang.IllegalArgumentException: Unable to validate decoded path: /my+email@example.com (Bad Request)
```

But using another email address without the `+` works.

I can open another issue about this if you wish... I'm not really sure if the problem is on the rclone side or their side given the java exception...

**Comment by ncw** [comment]
All the passwords in the config file are obscured to prevent "eyedropping" as one rclone user put it!

You can use the `rclone obscure` command to make obscured passwords, and in [the latest beta](https://beta.rclone.org) you'll find [a rest API to do it too](https://tip.rclone.org/rc/#core-obscure-obscures-a-string-passed-in).

Any backend variable which has `IsPassword: true` in `rclone config providers` will require being obscured.

You aren't the first person to ask for this BTW!

> 1. If decryption fails, assume the password is already plaintext and just try it anyway. (easy)
> 2. Check whether config came from environment variables. If so, assume plaintext?

The first of those options is quite attractive.  The second would be quite hard since by the time the parameter has made it to the backend it could have come from an env var, the config file or the command line - it doesn't know.

I missed a trick when I made the obscuring scheme - I should have made obscured strings a bit more recognizable that would have made option 1 easier.  The problem with option 1 is that some valid passwords could be valid base64 strings - any string of > 22 `[A-Za-z0-9]` will decrypt to something or other. Unfortunately this is exactly the form of password rclone generates when it is generating random passowrds!

So here are the options as I see them

1.We could do something like make a prefix for things we don't want Reveal to mess with, say `*NotObscured*theactualpassword` - this fails your special cases test though.
2. Or we could introduce a flag / env var `--plaintext-passwords` - this would make Reveal a no-op. Though this would need a bit of factoring as Reveal is used in the backends for app secrets so we'd need a PasswordReveal which checked the flag leaving Reveal alone.
3. or we could just go with the risk that not many users will use >22 letter alphanumeric passwords and allow Reveal to return the original string if the password decrypt failed.

Which is your favourite option?

**Comment by ncw** [comment]
> Also I wonder if I found another bug in Jottacloud. When the username has a `+` in it (my email address does), I get this fun error back:
> 
> ```
> 2018/11/09 11:08:44 Failed to create file system for "jottacloud:foo": couldn't get account info: failed to get endpoint url: error 400: java.lang.IllegalArgumentException: Unable to validate decoded path: /my+email@example.com (Bad Request)
> ```
> But using another email address without the `+` works.
> 
> I can open another issue about this if you wish... I'm not really sure if the problem is on the rclone side or their side given the java exception...

Sorry forgot to reply to this bit - yes please make another issue about this then I can get the jottacloud contributor to take a look!

**Comment by mholt** [comment]
Nick, I don't know how you do it, but you always have such thorough, well-reasoned, and polite responses. Even despite my incessant commenting noise. :) Thank you!

> All the passwords in the config file are obscured to prevent "eyedropping" as one rclone user put it!

Makes sense, we do the same thing with the [Relica](https://relicabackup.com) cache.

> You can use the rclone obscure command to make obscured passwords, and in the latest beta you'll find a rest API to do it too.

Actually this might be perfect. I didn't realize rclone was so self-documenting. This way, I have the option of running it and dynamically determining which fields to obscure (this handles changes automatically) OR I can run it once manually and just make a map of backend type to field name for those fields which need to be obscured (which I would need to maintain -- I presume it wouldn't change much).

So, given that I can reasonably work around this on my end, it's probably better to NOT introduce magic into the crypto-related operations in rclone. :)

> Sorry forgot to reply to this bit - yes please make another issue about this then I can get the jottacloud contributor to take a look!

Done! #2734.

Thank you again for your time and the very detailed/helpful answers!

**Comment by ncw** [comment]
Ah, option 4) :-)  If you are happy with that then it suits me too.

> Actually this might be perfect. I didn't realize rclone was so self-documenting

rclone should have all the tools for discovery of the backend config and configuration of the backends, check out `rclone config -h`.  There are rest APIs for all of those now too!

>  I presume it wouldn't change much

No.. Though a heads up for you - in #2498 it will change the Jottacloud login to require oauth.

**Comment by ncw** [comment]
> Done! #2734.
> 
> Thank you again for your time and the very detailed/helpful answers!

Thanks for making the issue and you are welcome!

BTW if you find stuff missing from rclone's interfaces to config things then do let me know.
