### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by victoriastuart** [ncw/rclone#2779]
I thought I saw an rclone update in my terminal, a day or so ago (Arch Linux package manager).  Since then my rclone backups to Dropbox (fine previously; negligible CPU use) now at times uses way more CPU resources --  up to 100% (all 8 cores, sustained), at times.  That is, in the first image below, CPU use will be 800%.

rclone v1.45
Arch Linux x86_64

rclone sync --ignore-size --tpslimit 10 --skip-links /mnt/Vancouver/ "dropbox:backups/vancouver" --filter-from /home/victoria/backups/rclone/rclone_filters-vancouver.txt

**Edit:** this is an additional concern, as my CPUs subsequently clock at 90-100 degC (sustained), ***and*** the rclone backups to Dropbox take ~12 hours to complete.

![selection_999 735](https://user-images.githubusercontent.com/2575920/49097869-9193ea00-f222-11e8-8efd-5ad237af24b0.png)

![selection_999 734](https://user-images.githubusercontent.com/2575920/49097650-06b2ef80-f222-11e8-98bc-97071f1533dc.png)

**Comment by ncw** [comment]
> However, I also remembered recently adding a LOT of lines to my filters file: files with names ending in { .css | .DS_store | ...}; ~500 lines, approximately -- files that Dropbox excludes from backups.

Ah!  rclone keeps the filters as a linear list and will scan through them for each file which probably explains the CPU usage.  Things will run much quicker if you can reduce the number of filter lines eg using

    *.{jpg,png,gif}

rather than having 3 separate lines

    *.jpg
    *.png
    *.gif

It would be possible for rclone to be a bit cleverer about the filters, but I have to say this is the first report of it causing a problem.
