### ISSUE TITLE
Revise Update()/Put() interface

### ISSUE THREAD

**Issue by klauspost** [ncw/rclone#282]
For the hash-update, I found it would be nice to have been able to put another parameter on a Put/Update requests. The current interface is quite resistant to change ;)

```Go
	Put(in io.Reader, remote string, modTime time.Time, size int64) (Object, error)
	Update(in io.Reader, modTime time.Time, size int64) error
```

I would propose wrapping up the common parameters in a struct, for instance:

```Go
type NewObject struct {
	in io.Reader
	modTime time.Time
	size int64
}

	Put(remote string, n NewObject) (Object, error)
	Update(n NewObject) error
```
In the concrete case, I would like to add the known hashes to NewObject. That would allow us to skip the temporary file copy in B2 for instance. If the interface looked like this, the change (and others that could come) would be unobtrusive.

`NewObject` was the best I could come up with, that wasn't too long for my taste.

**Comment by ncw** [comment]
Yes knowing the hash at the time of creation of the object would be very useful and could be used with swift, s3 and probably others to ensure a server side check of the hash - good idea.

I'd be inclined to say that adding a options struct to Put() and Update() is going a step too far though - whad do the function signatures look like with the set of known hashes?  Can you think of anything we might want to add in the near future?

**Comment by klauspost** [comment]
Adding one more parameter - here a `map[fs.HashType]string` wouldn't be the end of the world.  

But on the other hand, if we would like to pass another value on some point, we don't have to rework the interface again. Therefore wrapping the parameters would make it easier to manage in the future.

**Comment by klauspost** [comment]
Thinking about the implementation, another approach could be that the source `fs.Object` is sent along. That way we don't need a new type, and the transfer back and forth.

Is this crazy/impossible?

```Go
    Put(remote string, src *Object) (Object, error)
    Update(src *Object) error
``

**Comment by ncw** [comment]
> Adding one more parameter - here a map[fs.HashType]string wouldn't be the end of the world.

Especially if we were to give `map[fs.HashType]string` a type name, eg `fs.HashMap` or something like that.
 
> But on the other hand, if we would like to pass another value on some point, we don't have to rework the interface again. Therefore wrapping the parameters would make it easier to manage in the future.

It depends on whether the new stuff is optional or not.  If it is optional then you are right, but if not, then each use of the method needs to be examined and changing the signature is quite a good idea so it breaks stuff.

> Thinking about the implementation, another approach could be that the source fs.Object is sent along. That way we don't need a new type, and the transfer back and forth.
>
> Is this crazy/impossible?

I quite like the idea.

The Put() and Update() methods were designed to be usable without the framework of rclone so they work at a slightly lower level which is why they are they way they are. This lower level stuff is used in the tests mostly.

If we were to make the change you suggest then it would become useful to make a sort of in memory `fs.Object` for the tests, thought we could just re-work them to use a local object.

Looking at operations.go we would need to have an `io.Reader` parameter I think, so the src Object would just be used for reading any metadata.

```go
    Put(in io.Reader, remote string, src *Object) (Object, error)
    Update(in io.Reader, src *Object) error
```

Unless we were to re-work the accounting so it all happens in the Transport (which then wouldn't work for local -> local syncs).

**Comment by ncw** [comment]
I had some more thoughts about this

What might be best is for Put & Update to take a subset of the fs.Object interface, say fs.ObjectMetadata

So the interface could become

```go
Put(in io.Reader, src ObjectMetadata) (Object, error)
Update(in io.Reader, src ObjectMetadata) error
```

This interface would have the Size, Hash, ModTime, and Remote methods in it. That would cover everything that Put and Update needs I think, and be easy to update.

Having an interface is a good idea over an object because some of the methods (eg ModTime or Hash) can be expensive, so if Put or Update doesn't need it, then it doesn't need to be calculated.

It would be easy to make a struct which fulfilled the fs.ObjectMetadata interface for building things in tests, which would essentially be the equivalent of your original suggestion of a struct.

**Comment by klauspost** [comment]
Great solution! I like restricting access that way. That ensure that we don't get unintended side-effects.

**Comment by ncw** [comment]
This is complete now! Thanks Klaus.
