### ISSUE TITLE
bash completion: escape special characters

### ISSUE THREAD

**Issue by aureliendavid** [ncw/rclone#3047]
Hi, 

The bash completion seems to work but doesn't escape remote path containing spaces or special characters (like parenthesis). 

```
$ rclone lsd remote:/test/path<tab>
```

completes to

```
$ rclone lsd remote:/test/path with spaces  (instead of /test/path\ with\ spaces)
```

Also it doesn't complete if the remote path is quoted although rclone does seem to support quoted remote paths: 

```
$ rclone lsd remote:"/test/path<tab> # doesn't complete here
```

thanks

```
$ rclone --version
rclone v1.46-DEV
- os/arch: linux/amd64
- go version: go1.11.5
```

**Comment by sgtpep** [comment]
@ncw Hi, here's the patch for adding escaping for spaces: https://gist.github.com/sgtpep/614c9210f34a56396ae34f19cb7d6523. Regarding the autocompletion for quoted paths: it requires some research on how it's better to be done in bash-completion, because there're too many cases with quoting to process all of them manually (double quotes, single quotes, $'...', etc).

**Comment by aureliendavid** [comment]
the quoted paths thing is not that important if we can get proper escaping of special characters on unquoted paths

**Comment by sgtpep** [comment]
Updated a patch.

@aureliendavid It should escape any special character, not only spaces.

**Comment by aureliendavid** [comment]
thanks for the patch

It seems to work well on leaves, but doesn't autocompletes subsequent children if it's a node.

i.e.:

```shell
$ rclone ls remote:/test/path<tab> # completes to
$ rclone ls remote:/test/path\ with\ spaces/
$ rclone ls remote:/test/path\ with\ spaces/child<tab> # <-- doesn't complete here
```

**Comment by sgtpep** [comment]
@aureliendavid You're right. Thanks for spotting this! I've updated the patch. To solve this we need a way to unescape escaped strings like this ("foo\ bar") in bash. Turns out the only way to do that is to use `eval` but in a kinda safe way (here's an explanation: https://stackoverflow.com/a/50583873).

**Comment by aureliendavid** [comment]
works great, thanks!

**Comment by ncw** [comment]
Thanks for working on this @sgtpep .  Are you going to send a pull request eventually?

**Comment by sgtpep** [comment]
@ncw Done https://github.com/ncw/rclone/pull/3054. Sorry, I first made a pull request and then read contribution guidelines, not sure how to redo it quickly.

**Comment by ncw** [comment]
> Done #3054. Sorry, I first made a pull request and then read contribution guidelines, not sure how to redo it quickly.

Thank you for that @sgtpep it looks great!  I edited the commit message but otherwise was perfect :-)
