### ISSUE TITLE
Option to disable pre-allocate / ZFS

### ISSUE THREAD

**Issue by ellisonpatterson** [ncw/rclone#3066]
#### What is your current rclone version (output from `rclone version`)?
1.46

#### What problem are you are trying to solve?
It seems that ZFS only supports a specific combination of the fallocate flags, and rclone isn't meeting that criteria.
https://github.com/zfsonlinux/zfs/blob/09ec770c2cfdb105e1d4a6e7470f2456d37c65e0/module/zfs/zpl_file.c#L662
Due to this, when a file is written it spits out a message in debug:
```
2019/03/22 18:16:19 DEBUG : MangoJuice/12-13-22 Mango Dango.avi: Failed to pre-allocate: operation not supported
```

#### How do you think rclone should be changed to solve that?
Make an option to disable pre-allocation or if it's possible to adjust the pre-allocation method for ZFS and/or other filesystems that may have the same issue.

Thanks!

**Comment by ncw** [comment]
From the ZFS source you linked

> The only flag combination which matches the behavior of zfs_space() is FALLOC_FL_KEEP_SIZE | FALLOC_FL_PUNCH_HOLE.

Rclone only uses `FALLOC_FL_KEEP_SIZE`

Reading [the man page](http://man7.org/linux/man-pages/man2/fallocate.2.html) I think it would be safe to add `FALLOC_FL_PUNCH_HOLE` since rclone only ever preallocates space on a 0 sized file.

> The FALLOC_FL_PUNCH_HOLE flag was introduced in the 2.6.38 kernel.

The go runtime supports down to 2.6.23 so this would cut off a few versions.

However I think this (from the man page) is more of a barrier to adding that flag unconditionally.

>        Not all filesystems support FALLOC_FL_PUNCH_HOLE; if a filesystem
>        doesn't support the operation, an error is returned.  The operation
>        is supported on at least the following filesystems:
> 
>        *  XFS (since Linux 2.6.
>        *  ext4 (since Linux 3.0)
>        *  Btrfs (since Linux 3.7)
>        *  tmpfs(5) (since Linux 3.5)"

Pre allocate is a performance optimization only, it doesn't affect correctness.  I added to speed up Windows where it is very effective, the Linux support was an afterthought.

Perhaps the best solution might be for rclone to detect the "operation not supported" error (syscall.ENOTSUP) and turn off pre allocate?

Or I guess it could try `FALLOC_FL_KEEP_SIZE | FALLOC_FL_PUNCH_HOLE` and if that failed turn it off.

I had a go at that here - can you give it a go?  It should print some log messages which I'll remove once it is working.

https://beta.rclone.org/branch/v1.46.0-108-g88b893d1-fix-3066-preallocate-beta/ (uploaded in 15-30 mins)

**Comment by ellisonpatterson** [comment]
Oh I should have mentioned, I'm running rclone on a *nix box and performing the operations on the box, Windows is not involved in anyway.

**Comment by ncw** [comment]
> Oh I should have mentioned, I'm running rclone on a *nix box and performing the operations on the box, Windows is not involved in anyway.

Understood! Give the beta above a go and tell me what you think - thanks!

**Comment by ncw** [comment]
@ellisonpatterson did you have a go with the above beta?

**Comment by ellisonpatterson** [comment]
Apologize about the delay! It resolved the issue 👍

**Comment by ncw** [comment]
Thanks for testing! I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.48

**Comment by DaMatrix** [comment]
Having this option would still be useful. For instance, when preallocating a file on btrfs, data written to the preallocated space doesn't get compressed, which means I have to manually run a second pass to re-compress all the files after rclone finishes.

**Comment by ncw** [comment]
@DaMatrix 

You can disable preallocate with

#### --local-no-preallocate

Disable preallocation of disk space for transferred files.

Preallocation of disk space helps prevent filesystem fragmentation.
However, some virtual filesystem layers (such as Google Drive File
Stream) may incorrectly set the actual file size equal to the
preallocated space, causing checksum and file size checks to fail.
Use this flag to disable preallocation.

Properties:

- Config:      no_preallocate
- Env Var:     RCLONE_LOCAL_NO_PREALLOCATE
- Type:        bool
- Default:     false
