### ISSUE TITLE
`copy` hangs on FTP LIST command

### ISSUE THREAD

**Issue by jeffquinn-outvote** [ncw/rclone#3086]
#### What is the problem you are having with rclone?

Running a copy command from FTP to GS, the process hangs indefinitely. The thread dump of the hanging process (running for 16 hours, with essentially no network activity) seems to indicate it is waiting for the FTP list command to return:

```
goroutine 72 [IO wait, 2361 minutes]:
internal/poll.runtime_pollWait(0x7ff5de1a8e30, 0x72, 0xc0000cb780)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000344118, 0x72, 0xffffffffffffff00, 0x146c4e0, 0x1d58830)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000344118, 0xc000348000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000344100, 0xc000348000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000344100, 0xc000348000, 0x1000, 0x1000, 0xc000522a80, 0x300000002, 0xc000522a80)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000ec40, 0xc000348000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x68
bufio.(*Reader).fill(0xc000229800)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadSlice(0xc000229800, 0x4a7c0a, 0xc000345b00, 0x1, 0xc0000cb900, 0xc0000cb9a0, 0x4a9050)
	/usr/local/go/src/bufio/bufio.go:341 +0x36
bufio.(*Reader).ReadLine(0xc000229800, 0xc0000cba00, 0xc0000cb9e0, 0x43660c, 0xc000522a80, 0x300000002, 0xc000522a80)
	/usr/local/go/src/bufio/bufio.go:370 +0x34
net/textproto.(*Reader).readLineSlice(0xc000227e60, 0x4406dc, 0xc000345b28, 0xc0000cba01, 0x4405bb, 0xc000345b28)
	/usr/local/go/src/net/textproto/reader.go:55 +0x6f
net/textproto.(*Reader).ReadLine(0xc000227e60, 0x0, 0x0, 0xc0000cbab0, 0x4404d9)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2b
net/textproto.(*Reader).readCodeLine(0xc000227e60, 0xe2, 0x0, 0x0, 0xc0000cbb18, 0x511b3f, 0xc000345b00, 0x0)
	/usr/local/go/src/net/textproto/reader.go:177 +0x2f
net/textproto.(*Reader).ReadResponse(0xc000227e60, 0xe2, 0x0, 0xc0000cbbb8, 0x18, 0xc000522a80, 0x1325f68)
	/usr/local/go/src/net/textproto/reader.go:255 +0x4d
github.com/jlaffaye/ftp.(*Response).Close(0xc00054a900, 0x5, 0xc0000cbc70)
	/root/go/pkg/mod/github.com/jlaffaye/ftp@v0.0.0-20190126081051-8019e6774408/ftp.go:595 +0x89
github.com/jlaffaye/ftp.(*ServerConn).List(0xc000288a00, 0xc000504660, 0x19, 0xc00372c000, 0x12e7d, 0x17800, 0x0, 0x0)
	/root/go/pkg/mod/github.com/jlaffaye/ftp@v0.0.0-20190126081051-8019e6774408/ftp.go:394 +0x483
github.com/ncw/rclone/backend/ftp.(*Fs).List(0xc0002e91e0, 0x0, 0x0, 0x8, 0xc0002885c0, 0xc0007d4360, 0xc000951e10, 0xc000817fb0)
	/containers/deps/rclone/backend/ftp/ftp.go:333 +0x111
github.com/ncw/rclone/fs/list.DirSorted(0x1481300, 0xc0002e91e0, 0x0, 0x0, 0x0, 0x42cc72, 0xffffffff00000008, 0xc000288980, 0x0, 0xc000817f48)
	/containers/deps/rclone/fs/list/list.go:23 +0x63
github.com/ncw/rclone/fs/march.(*March).makeListDir.func1(0x0, 0x0, 0xc000546080, 0x0, 0xc0007d4360, 0x0, 0x1)
	/containers/deps/rclone/fs/march/march.go:73 +0x53
github.com/ncw/rclone/fs/march.(*March).processJob.func1(0xc000546080, 0xc000345780, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc00054a720, ...)
	/containers/deps/rclone/fs/march/march.go:347 +0x6c
created by github.com/ncw/rclone/fs/march.(*March).processJob
	/containers/deps/rclone/fs/march/march.go:345 +0x117d
```

Similar to #2912 I suspect we just need a timeout here (and maybe in other places too eventually).

#### What is your rclone version (output from `rclone version`)

`1.46`

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Alpine Linux, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Storage

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone copy --transfers 16 --use-mmap '--include=full_*.csv.gz' --max-depth 0 ftp:remote-ftp-folder gcp:mybucket/myprefix`

**Comment by ncw** [comment]
> Running a copy command from FTP to GS, the process hangs indefinitely. The thread dump of the hanging process (running for 16 hours, with essentially no network activity) seems to indicate it is waiting for the FTP list command to return:

What do you think the underlying cause of the FTP server not responding to LIST is? It is likely a bug in the ftp library.

I'd rather fix that that put a timeout in the rclone List command.

Which FTP server is it? Can you make an easy reproduction?

**Comment by jeffquinn-bluevoyant** [comment]
At our company we have a bunch of 3rd party vendors who prefer to send us data via FTP. So I have limited insight into what's going on on the other end unfortunately..

When you say bug in the FTP library do you mean the client library rclone is using or the remote server? I agree the remote server in this case is probably at fault, but that should be no reason not to try and be robust on our side. I think future data engineers who pick up rclone will be thankful :)

If there was a way to reset the timeout when data actually comes over the wire that would be ideal, because with the patch I have written here, theoretically we could be interrupting a successful command that is sending 1G of LIST results back over the wire, or something.

I'm going to try using `--fast-list` in the mean time, which I think should issue fewer LIST commands, and thus have a better chance of success maybe.

**Comment by ncw** [comment]
> At our company we have a bunch of 3rd party vendors who prefer to send us data via FTP. So I have limited insight into what's going on on the other end unfortunately..

Ah OK.  Could you take an wireshark dump?
 
> When you say bug in the FTP library do you mean the client library rclone is using or the remote server? I agree the remote server in this case is probably at fault, but that should be no reason not to try and be robust on our side. I think future data engineers who pick up rclone will be thankful :)

I think it is probably a bug in the [ftp client library rclone](https://github.com/jlaffaye/ftp) is using.
 
> If there was a way to reset the timeout when data actually comes over the wire that would be ideal, because with the patch I have written here, theoretically we could be interrupting a successful command that is sending 1G of LIST results back over the wire, or something.

Rclone implements exactly that for the http based remotes:

https://github.com/ncw/rclone/blob/1c301f9f7ab8bf00d04331acc26b5195820ed1cf/fs/fshttp/http.go#L48

So if we could figure out how to wedge it in to jlaffaye/ftp that would be a great improvement and it would mean the ftp backend would start obeying the `--timeout` flag like all the other backends.
 
> I'm going to try using `--fast-list` in the mean time, which I think should issue fewer LIST commands, and thus have a better chance of success maybe.

I think `--fast-list` won't help as FTP doesn't support it.  GS does though so it might make some difference.

**Comment by jeffquinn-bluevoyant** [comment]
About fast-list, I figured that flag meant it would do one top level recursive list and store the results in memory, instead of listing each directory as needed, but you're saying for FTP its a no-op?

Upon closer inspection of the trace, and after hitting this problem again last night, I see that the line `github.com/jlaffaye/ftp.(*Response).Close(0xc00054a900, 0x5, 0xc0000cbc70)` is present in the stacktrace, so it seems the library is trying to close the connection perhaps here: https://github.com/jlaffaye/ftp/blob/master/ftp.go#L469

This seems to point to the same Close timeout we hit before.

Are you using the latest version of `jlaffaye/ftp`? If so I'll go and try to patch this there, I don't think there's any other way since this `Close` is internal to that library.

**Comment by ncw** [comment]
> About fast-list, I figured that flag meant it would do one top level recursive list and store the results in memory, instead of listing each directory as needed, but you're saying for FTP its a no-op?

It is a no-op for FTP but not for GCS.

> Are you using the latest version of jlaffaye/ftp? If so I'll go and try to patch this there, I don't think there's any other way since this Close is internal to that library.

Rclone is using  github.com/jlaffaye/ftp@8019e6774408 which isn't quite the latest but is only 4 commits off the HEAD.

Setting a deadline on the list socket of 5 minutes from now every time something is read from the socket would probably fix the problem with a 5 minute delay...

If you send a patch upstream, can you link it here?

**Comment by jeffquinn-bluevoyant** [comment]
It seems like the author recently marked this issue as TODO:
https://github.com/jlaffaye/ftp/issues/117

I believe it will fix this issue the correct way it gets closed. I looked
briefly at what is required and it seemed a bit beyond what I'm comfortable
doing.

I tried putting a timeout on list but it ended up being too short, so that
makes me think it might be hard to come up with a reasonable timeout that
will not break people's flows.
