### ISSUE TITLE
Unable to login into mega

### ISSUE THREAD

**Issue by Anagastes** [ncw/rclone#3161]
I also have login problems

- rclone v1.47.0
- os/arch: linux/amd64 (debian)
- go version: go1.12.4

rclone lsd HOST: --mega-debug -vv
2019/05/02 17:23:52 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "lsd" "HOST:" "--mega-debug" "-vv"]
2019/05/02 17:23:52 DEBUG : Using config file from "/home/USER/.config/rclone/rclone.conf"
2019/05/02 17:23:52 DEBUG : go-mega: Retry API request 1/10: Try again
2019/05/02 17:23:52 DEBUG : go-mega: Retry API request 2/10: Try again
2019/05/02 17:23:52 DEBUG : go-mega: Retry API request 3/10: Try again
2019/05/02 17:23:52 DEBUG : go-mega: Retry API request 4/10: Try again
2019/05/02 17:23:52 DEBUG : go-mega: Retry API request 5/10: Try again
2019/05/02 17:23:52 DEBUG : go-mega: Retry API request 6/10: Try again
2019/05/02 17:23:53 DEBUG : go-mega: Retry API request 7/10: Try again
2019/05/02 17:23:53 DEBUG : go-mega: Retry API request 8/10: Try again
2019/05/02 17:23:55 DEBUG : go-mega: Retry API request 9/10: Try again
2019/05/02 17:23:57 DEBUG : go-mega: Retry API request 10/10: Try again
2019/05/02 17:24:02 Failed to create file system for "HOST:": couldn't login: Try again

Normal login via the client works fine. Also on the website.

Any idea?

**Comment by bingoxo** [comment]
do you have 2fa enabled ?

**Comment by Anagastes** [comment]
No, I didn't. :)

**Comment by caspertone2003** [comment]
There is some issue with rclone/mega logins.

Further information

https://forum.rclone.org/t/failed-to-create-file-system-for-remote-folder-couldnt-login-try-again/9501/3

No such issues with megatools nor megacmd nor web interface. (while megacmd has needed up to three minutes to connect to challenging remotes...).

I personally believe that sometimes a mega remote gets some non expected (by rclone) answer or that some kind of throthigling is done by mega.... I believe that rclone modus operandi makes too many login/logouts in small time, then probably triggers some pacing.

I have a remote that can list its contents, then I cannot get the full list of public links because it stops login... until a week later....

**Comment by caspertone2003** [comment]
Today my wild mega remote behaved... I did a pause of 3 seconds after each logoff... (so, after each rclone command).
I cannot promise it is just a random fact or that there is correlation of both facts...

@Anagastes :
Wait a week, then try to login...

CT

**Comment by Anagastes** [comment]
I've tested it again after a week. Now it seems to work as usual again.
I will open it again if it appears again. Thanks for the help! :)

**Comment by caspertone2003** [comment]
for reference
https://github.com/ncw/rclone/commit/cff85f0b9551881be535a4847b56742451e6b476
