### ISSUE TITLE
Memory leak when performing sync to Google clould storage with client-side encryption

### ISSUE THREAD

**Issue by swcen** [ncw/rclone#3196]
#### What is the problem you are having with rclone?

On Linux, when rclone performs sync to google cloud storage with client-side encryption, "top" shows that the memory usage for rclone keeps going up. Eventaully rclone encounters "fatal error: out of memory" and quits. rclone memory profiling confirms that problem, and points to "encoding/json.(*decodeState).literalStore" being the primary suspect. 

#### What is your rclone version (output from `rclone version`)

rclone v1.47.0-067-g9c6f3ae8-beta
- os/arch: linux/amd64
- go version: go1.12.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

CentOS 6.6, with Linux 2.6.32-504.3.3.el6.x86_64
with 16GB RAM

####  Which cloud storage system are you using? (eg Google Drive)

Google cloud storage, with client-side encryption

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone --transfers=2 --cache-chunk-no-memory sync /xxxx gcs-sa-enc:/xxxx --rc

Configuration file rclone.conf:

```
[gcs-sa]
type = google cloud storage
project_number = xxxx
service_account_file = xxxx
storage_class = COLDLINE
object_acl = private
bucket_acl = private
client_id = xxxx

[gcs-sa-enc]
type = crypt
remote = gcs-sa:xxxx/xxxx
filename_encryption = standard
directory_name_encryption = true
password = xxxx
password2 = xxxx
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
$ go tool pprof -text http://localhost:5572/debug/pprof/heap
Run above profiling command periodically, with following outputs

Time: May 13, 2019 at 11:21pm (PDT)
Showing nodes accounting for 549.92MB, 98.15% of 560.31MB total
Dropped 64 nodes (cum <= 2.80MB)
      flat  flat%   sum%        cum   cum%
  446.69MB 79.72% 79.72%   446.69MB 79.72%  encoding/json.(*decodeState).literalStore
   51.51MB  9.19% 88.92%    65.51MB 11.69%  github.com/ncw/rclone/backend/googlecloudstorage.(*Fs).newObjectWithInfo
      24MB  4.28% 93.20%       24MB  4.28%  github.com/ncw/rclone/vendor/google.golang.org/api/gensupport.NewMediaBuffer
      14MB  2.50% 95.70%       14MB  2.50%  encoding/hex.EncodeToString
    6.94MB  1.24% 96.94%    72.44MB 12.93%  github.com/ncw/rclone/backend/googlecloudstorage.(*Fs).listDir.func1
       4MB  0.71% 97.65%        4MB  0.71%  strings.(*Builder).grow
    2.28MB  0.41% 98.06%     3.28MB  0.59%  github.com/ncw/rclone/fs/sync.(*syncCopyMove).DstOnly
    0.50MB 0.089% 98.15%     4.48MB   0.8%  github.com/ncw/rclone/fs/march.(*March).processJob
         0     0% 98.15%   448.73MB 80.09%  encoding/json.(*Decoder).Decode

Time: May 13, 2019 at 11:28pm (PDT)
Showing nodes accounting for 996.43MB, 98.54% of 1011.23MB total
Dropped 78 nodes (cum <= 5.06MB)
      flat  flat%   sum%        cum   cum%
  817.85MB 80.88% 80.88%   817.85MB 80.88%  encoding/json.(*decodeState).literalStore
   90.51MB  8.95% 89.83%   118.51MB 11.72%  github.com/ncw/rclone/backend/googlecloudstorage.(*Fs).newObjectWithInfo
      32MB  3.16% 92.99%       32MB  3.16%  github.com/ncw/rclone/vendor/google.golang.org/api/gensupport.NewMediaBuffer
      28MB  2.77% 95.76%       28MB  2.77%  encoding/hex.EncodeToString
   13.55MB  1.34% 97.10%   132.07MB 13.06%  github.com/ncw/rclone/backend/googlecloudstorage.(*Fs).listDir.func1
    9.50MB  0.94% 98.04%     9.50MB  0.94%  strings.(*Builder).grow
    4.52MB  0.45% 98.49%    10.02MB  0.99%  github.com/ncw/rclone/fs/sync.(*syncCopyMove).DstOnly
    0.50MB  0.05% 98.54%    10.52MB  1.04%  github.com/ncw/rclone/fs/march.(*March).processJob
         0     0% 98.54%   821.58MB 81.25%  encoding/json.(*Decoder).Decode

	Time: May 14, 2019 at 12:07am (PDT)
Showing nodes accounting for 3253.22MB, 98.90% of 3289.37MB total
Dropped 109 nodes (cum <= 16.45MB)
      flat  flat%   sum%        cum   cum%
 2610.13MB 79.35% 79.35%  2610.13MB 79.35%  encoding/json.(*decodeState).literalStore
  299.53MB  9.11% 88.46%   375.53MB 11.42%  github.com/ncw/rclone/backend/googlecloudstorage.(*Fs).newObjectWithInfo
   91.50MB  2.78% 91.24%    91.50MB  2.78%  github.com/ncw/rclone/backend/crypt.(*Fs).newObject
      76MB  2.31% 93.55%       76MB  2.31%  encoding/hex.EncodeToString
   51.74MB  1.57% 95.12%   427.28MB 12.99%  github.com/ncw/rclone/backend/googlecloudstorage.(*Fs).listDir.func1
      30MB  0.91% 96.03%       30MB  0.91%  github.com/ncw/rclone/vendor/github.com/rfjakob/eme.tabulateL
   27.76MB  0.84% 96.88%    27.76MB  0.84%  github.com/ncw/rclone/lib/pool.New.func1
      27MB  0.82% 97.70%       27MB  0.82%  strings.(*Builder).grow
      18MB  0.55% 98.25%       48MB  1.46%  github.com/ncw/rclone/vendor/github.com/rfjakob/eme.Transform
   13.55MB  0.41% 98.66%    20.55MB  0.62%  github.com/ncw/rclone/fs/sync.(*syncCopyMove).DstOnly
    4.50MB  0.14% 98.79%       73MB  2.22%  github.com/ncw/rclone/backend/crypt.(*cipher).decryptSegment
    2.50MB 0.076% 98.87%    20.50MB  0.62%  github.com/ncw/rclone/backend/crypt.decodeFileName
    1.01MB 0.031% 98.90%    21.56MB  0.66%  github.com/ncw/rclone/fs/march.(*March).processJob
         0     0% 98.90%  2610.66MB 79.37%  encoding/json.(*Decoder).Decode
```
		 
Eventually rclone ran out of memory and crashed.

**Comment by ncw** [comment]
Excellent debugging - thank you :-)

These two lines

> 2610.13MB 79.35% 79.35% 2610.13MB 79.35% encoding/json.(*decodeState).literalStore
> 299.53MB 9.11% 88.46% 375.53MB 11.42% github.com/ncw/rclone/backend/googlecloudstorage.(*Fs).newObjectWithInfo

Are indicative that the memory usage is caused by lots of objects created by the gcs backend. So if there is a leak of anything it is objects from gcs.

This could be normal though if you have a directory with a very large number of objects in?

Can you tell me a bit about the sync?  How many files and what sizes are they?

**Comment by swcen** [comment]
Thank you for your quick response!

Yes the local directory indeed has many files: totally in the order of 500K files, 30K sub-directories, and 1TB data. Most are small files.

If there is no memory leak, but large number of files causes excessive memory usages in gcs backend, this would be a design that needs to be improved. What are the reasons all the objects need to be kept in memory at the same time?

**Comment by ncw** [comment]
> Yes the local directory indeed has many files: totally in the order of 500K files, 30K sub-directories, and 1TB data. Most are small files.

It is number of files in a single directory that is the problem case.  Lots of files in general isn't a problem unless they are all in one directory.

You can find the top number of files in a directory in a directory hierarchy like this

    du --inodes -S /path/to/dir | sort -rh | head

> If there is no memory leak

I'm not convinced there is or isn't a memory leak yet ;-)

> but large number of files causes excessive memory usages in gcs backend, this would be a design that needs to be improved. What are the reasons all the objects need to be kept in memory at the same time?

If you have 100k files in one directory (say) then rclone will read that directory in its entireity into memory so it can compare it with the local version.

It would be possible to read all files in a directory starting with A then B etc for gcs and sync those but rclone doesn't do that (and it would be difficult to support on non bucket based remotes).

**Comment by swcen** [comment]
"du --inodes" shows the largest directory has about 10K files.

The symptom looks like memory leak to me. The profiling tool shows that encoding/json.(*decodeState).literalStore steadily takes more and more memory, until rclone eventually crashes.

**Comment by ncw** [comment]
Memory leaks in the C sense of forgetting to free memory aren't possible in Go programs because it uses a garbage collector.  However what is quite common is goroutine leaks which leak memory, so can you post the result of `curl http://localhost:5572/debug/pprof/goroutine?debug=1` - that will show if goroutines are building up.

Can you do the graphical output `go tool pprof -web http://localhost:5572/debug/pprof/heap` and post the image?  That will show us the chain of memory allocations. I suspect that is going to be important!

**Comment by swcen** [comment]
Enclosed please 3 debug files after rclone has been running for a bout 1 hour: (1) screen capture of top showing rclone resource usage; (2) text file with output of the curl command; and (3) .gz file with output of the "go tool pprof -web" command. 

![image](https://user-images.githubusercontent.com/9450651/57964386-a441ce80-78e9-11e9-8138-e0e8f7cdf327.png)
[goroutine.004.txt](https://github.com/ncw/rclone/files/3193644/goroutine.004.txt)
[pprof.rclone.alloc_objects.alloc_space.inuse_objects.inuse_space.005.pb.gz](https://github.com/ncw/rclone/files/3193646/pprof.rclone.alloc_objects.alloc_space.inuse_objects.inuse_space.005.pb.gz)

**Comment by ncw** [comment]
Thank you for that - very useful.

From that I see that there are 7 directory listings in progress (which sounds right for default --checkers of 8).  There are 886 directories pending to be listed which is a lot, but these pending directory lists don't take up much memory (and they don't show in the profile) even though they do use go routines (which take 4-8K each so only 7MB).

The memory use is nearly all created by the directory listing routines `github.com/ncw/rclone/fs/march.(*March).processJob.func2` and in particular the JSON unmarshalling of the objects returned by GCS.

Looking carefully at the heap, there is 76.5MB generated by `hex.EncodeToString`.  These are all 32 byte strings so that gives us a way of estimating how many objects (which represent files) are in memory.  That comes up with 2.4 Million which is many times more objects than your 500k figure above which is puzzling.

Can you do `rclone size /xxxx` to see how many objects rclone thinks you have?

It would be helpful if I knew how your files were arranged.

Can you do `rclone lsf -R gcs-sa:xxxx/xxxx > listing.txt` and attach that to the issue?  That will be encrypted file names from your remote so shouldn't leak any confidential data.  If you are uncomfortable attaching that then you could email them to me nick@craig-wood.com - put a link to the issue in the email.

One thing which would be worth trying is seeing whether this is the go's garbage collector falling behind.

So can you try [setting GOGC](https://dave.cheney.net/tag/gogc) to a lower value, say `export GOGC=20` to make the garbage collector work harder.  I don't know whether this will make a difference but it might!

**Comment by swcen** [comment]
Thank you for adding this issue as a bug, and sorry for the delay in the response, as the tests took a lot of time.

"rclone size /xxxx" showed total objects about 405K, and total size about 880GB

"export GOGC=20" indeed helped a lot. "rclone sync" was able to run to completion. "top" showed memory usage capped around 6.3GB VIRT / 3.5GB RES.

The output of "rclone lsf -R gcs-sa:xxxx/xxxx" is huge. Let me know if you still need it for debugging.

**Comment by ncw** [comment]
> Thank you for adding this issue as a bug, and sorry for the delay in the response, as the tests took a lot of time.

No worries
 
> "rclone size /xxxx" showed total objects about 405K, and total size about 880GB

Interesting... That is less than the 2.4M we see in memory.  So I wonder if objects are being copied rather than referred to somewhere and generating a lot of garbage.

> "export GOGC=20" indeed helped a lot. "rclone sync" was able to run to completion. "top" showed memory usage capped around 6.3GB VIRT / 3.5GB RES.

This means that this is probably an interaction with the garbage collector then...  That is still far too much memory though about 8.5k per object.  I'd expect about 1/10th of that

> The output of "rclone lsf -R gcs-sa:xxxx/xxxx" is huge. Let me know if you still need it for debugging.

If you could gzip it and send it or attach it that would be really helpful.  I can try re-creating the hierarchy and see if I can replicate the problem.

**Comment by ncw** [comment]
Thanks for the listing.

I have analyzed it - it is a big file!

There are 5,414,582 files in the listing.  However there seem to be 2,717,205 files in this directory `gvbjrkg04ljd8tc5dp1qojs88s/jn3st2jljdisd10d1o3bu342f0/ok962nhve4afsv1qr5uo4rvp9o/re6gna1bg9tq3touf8d9oimf7o/dk6chbr17a39b3g1d14btc76ug/h67vieuf8ha29ughgh73gk59d0/78k1i9p4nrbmi7uctjb7ukj41g/o1acleo51me26d0fhnrk1cms3s/ejd155a9ao4q2o1a9f4jlmg9ds/v7t1ohd79u8fmgaqrebaqlqbmg/`

(If you want to discover what directory that is use `rclone cryptdecode`).

Rclone sync works on a directory by directory basis, so at some point rclone will have to load all 2.7M objects into memory in order to sync it.

This agrees approximately with your memory dump above which had ~2.4M objects in it. Given that there are likely 2.7M gcs objects and 2.7M local objects in memory, to sync that one directory, that probably explains the 7G memory usage.

I should probably change rclone to warn if a large directory is synced.

> "rclone size /xxxx" showed total objects about 405K, and total size about 880GB

I don't understand why there are 5.4M files in the bucket but you only have 405K on your local machine?

**Comment by swcen** [comment]
Thank you for the very interesting findings. I'd like to find out what's going on.

When I "rclone cryptdecode encryptedremote: gvbjrkg04ljd8tc5dp1qojs88s" as you suggested, it showed "Failed to cryptdecode: didn't find section in config file". Except for https://rclone.org/commands/rclone_cryptdecode/, I did not find other info on how to config for and use cryptdecode.

I've run "rclone sync" many times, and it crashed every single time. Could the failed executions be the cause of those extra items in the bucket? Guess I should know more when I got cryptdecode working property.

**Comment by swcen** [comment]
FYI - just figured out how to use "rclone cryptdecode". Will update when I have findings.

**Comment by ncw** [comment]
> I've run "rclone sync" many times, and it crashed every single time. Could the failed executions be the cause of those extra items in the bucket? Guess I should know more when I got cryptdecode working property.

I guess it is possible if you have lots of temporary files written to one directory which get deleted quickly.  Because rclone has never got to the delete phase of the sync there could be lots of files there.



> FYI - just figured out how to use "rclone cryptdecode". Will update when I have findings.

Great!

**Comment by swcen** [comment]
After many tries, I finally was able to delete all the objects in 
gvbjrkg04ljd8tc5dp1qojs88s/jn3st2jljdisd10d1o3bu342f0/ok962nhve4afsv1qr5uo4rvp9o/re6gna1bg9tq3touf8d9oimf7o/dk6chbr17a39b3g1d14btc76ug/h67vieuf8ha29ughgh73gk59d0/78k1i9p4nrbmi7uctjb7ukj41g/o1acleo51me26d0fhnrk1cms3s/ejd155a9ao4q2o1a9f4jlmg9ds/v7t1ohd79u8fmgaqrebaqlqbmg/

After that, "rclone sync" was able to run to completion without being out of memory. But with "-vv", the last 4 lines of debug output are as below. Apparently, "rclone sync" skip the delete phase, just as you mentioned.

ERROR : Encrypted drive 'XXXX:/XXXX': not deleting files as there were IO errors
ERROR : Encrypted drive 'XXXX:/XXXX': not deleting directories as there were IO errors
ERROR : Attempt 3/3 failed with 253 errors and: googleapi: Error 400: Invalid value for UnsignedLong: -42000, invalid
Failed to sync with 253 errors: last error was: googleapi: Error 400: Invalid value for UnsignedLong: -42000, invalid

Looks like all the 253 ERROR lines are in format "ERROR : <file-path>: googleapi: Error 400: Invalid value for UnsignedLong: -XXXX, invalid"

This error message is cryptic. What does it mean, and how can the errors be fixed?

**Comment by ncw** [comment]
Ah, this came up on the forum: https://forum.rclone.org/t/invalid-value-for-unsignedlong-file-missing-date-modified/3466

It is rclone attempting to set a date which is before the earliest date that gcs supports I think.

I think the epoch for gcs must be 1970-01-01 and you have files with that time, but I think the timezone is pushing them over the edge somehow...

What are the modified dates on those files?

Can you do a `stat` on one of them and post the result?

**Comment by swcen** [comment]
Those problem files indeed have date/time that is not right. Here is one of them:

stat test.sh
  File: 'test.sh'
  Size: 196       	Blocks: 25         IO Block: 512    regular file
Device: 17h/23d	Inode: 9424357     Links: 1
Access: (0644/-rw-r--r--) 
Context: system_u:object_r:ecryptfs_t:s0
Access: 2019-06-11 23:45:01.268512438 -0700
Modify: 1969-12-31 16:01:48.000000000 -0800
Change: 2018-09-10 17:56:43.586140210 -0700

One question is whether it's better to treat this type of issues as error that prevents rclone to delete files, or to treat it with a warning and allow rclone to delete.

It would also be helpful if the googleapi error message is more human-readable.

**Comment by ncw** [comment]
I had a look through the code and it turns out this is really easy to fix! Rclone  was attempting to set the "updated" time of the GCS object which is read only, so just removing that one line of code makes it work for me.

Can you try this?

https://beta.rclone.org/v1.47.0-121-g4d195d5a-beta/ (uploaded in 15-30 mins)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.48

**Comment by ncw** [comment]
I added also a FAQ entry about memory use

### Rclone is using too much memory or appears to have a memory leak

Rclone is written in Go which uses a garbage collector.  The default
settings for the garbage collector mean that it runs when the heap
size has doubled.

However it is possible to tune the garbage collector to use less
memory by [setting GOGC](https://dave.cheney.net/tag/gogc) to a lower
value, say `export GOGC=20`.  This will make the garbage collector
work harder, reducing memory size at the expense of CPU usage.

The most common cause of rclone using lots of memory is a single
directory with thousands or millions of files in.  Rclone has to load
this entirely into memory as rclone objects.  Each Rclone object takes
0.5k-1k of memory.

**Comment by swcen** [comment]
I got a chance to try this beta version:
rclone v1.47.0-123-g939b19c3-beta
- os/arch: linux/amd64
- go version: go1.12.6

Finally, "rclone sync" went through the delete phase. Though still reported some errors:

It reported 5 missing files in remote repository, with something like:

2019/06/13 17:00:53 ERROR : XXXX: Couldn't delete: googleapi: Error 404: No such object: gcs-coldline/XXXX, notFound

Then the last 3 ERROR lines as below:

2019/06/14 06:59:11 ERROR : Encrypted drive 'XXXX:/XXXX': not deleting directories as there were IO errors
2019/06/14 06:59:11 ERROR : Attempt 1/3 failed with 6 errors and: failed to delete 5 files
2019/06/14 07:56:28 ERROR : Attempt 2/3 succeeded

Wonder how rclone detect missing files in remote repository (instead of new files in local directory). Does the last ERROR line indicate that there is no more error?

**Comment by ncw** [comment]
> It reported 5 missing files in remote repository, with something like:
> 
> 2019/06/13 17:00:53 ERROR : XXXX: Couldn't delete: googleapi: Error 404: No such object: gcs-coldline/XXXX, notFound

Could something else have deleted these files?

Maybe another instance of rclone?

> Wonder how rclone detect missing files in remote repository (instead of new files in local directory).

Me too!

> Does the last ERROR line indicate that there is no more error?

Yes. A slightly confusing log message, but it needs to be at ERROR level so you definitely see it.

Rclone will exit with a 0 exit code also.

**Comment by swcen** [comment]
Thank you ncw for your help to root-cause this issue and get it fixed!
