### ISSUE TITLE
Ran Sync and then Check and it didn't Check

### ISSUE THREAD

**Issue by ChrisSLT** [ncw/rclone#32]
Hi - I ran a sync command and it completed with 0 errors, then I ran a check, and it showed that a PDF file had a different MD5 sum.  I re-ran the sync and then check several times with the same results.

I then ran sync with -v and saw that it said, for this one file, that it was the same size and modification.

The docs say rclone checks by modtime and then MD5.

Might this be a bug, or am I misinterpreting the docs?

Thanks

**Comment by ncw** [comment]
It might be that the docs are wrong!

rclone (like rsync) checks the size and modification time, and if these are identical assumes that the file is identical. That is a pretty good assumption normally, and it saves lots of disk and network IO.

rsync has a `-c` flag

        -c, --checksum              skip based on checksum, not mod-time & size

which checks checksums.  I should probably implement that for rclone at some point.

When you run `rclone check` it does show the difference, but `rclone sync` refuses to update it because the mod-time and size are identical - is that what you are seeing?

**Comment by ChrisSLT** [comment]
Makes complete sense.  Just thought I'd report it in case there was a bug.  
Yes, I think the docs say it checks by time and MD5, when I think you mean time and size?

**Comment by ncw** [comment]
Yes time and size.  The bug is in the docs which I'll fix shortly!

I'd like to implement the `-c` flag at some point too.
