### ISSUE TITLE
Higher units for ETA

### ISSUE THREAD

**Issue by turkeyphant** [ncw/rclone#3221]
Even with an ETA of several years, the ETA of a job is still displayed as e.g. 51721h18m55s

It would be trivial to introduce and potentially useful to automatically display at least days and year or have an option to do days, months and years.

**Comment by ncw** [comment]
We use `time.Duration` for ETA normally which only shows up to hours when stringified.

We could cast it to an `fs.Duration` for printing which has the higher units but it doesn't print out exactly the same, so it will go 23h59m59s to 1d, 1.5d, 1.8d, 6.9d, 1w

That would be a very easy change if someone wants to have a go.

PS Hope you don't get many jobs with an ETA of several years!

**Comment by turkeyphant** [comment]
I'm not familiar with Go but [this](https://github.com/hako/durafmt) seems to be a simple library that would do the job while keeping `time.Duration`.

**Comment by turkeyphant** [comment]
https://github.com/ncw/rclone/compare/test...turkeyphant:patch-1

**Comment by ncw** [comment]
durafmt looks interesting.  Rclone has a not as good version built in so you should find that using instead of `durafmt.Parse(d).String()` that `fs.Duration(d).String()` does approximately the right thing without taking on another dependency.

**Comment by AbelThar** [comment]
The implementation uses the same implementation `durafmt` uses for `String()`, made it less complex with just outputting suffixes.

I did not overwrite the current `fs.Duration.String()` implementation, but created a new function, `fs.Duration.ReadableString()`, and set `etaString()` in `fs/accounting/stats.go` to use this instead of `time.Duration.String()`

It was not overwritten as `String()` and `ParseString()` in `fs.Duration` have other references, which this implementation might conflict with.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.49

Thank you very much to our first time contributor @AbelThar - excellent job :-)

**Comment by turkeyphant** [comment]
Thank you both!
