### ISSUE TITLE
drive: google docs not showing when not in root

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#336]
```
$ rclone ls drive:GDocs
     5570 Drawings.svg
    27580 Slides.pptx
     4297 Docs.docx
     3516 Sheets.xlsx
```

vs

```
$ rclone ls drive: | grep GDocs
$
```

Factored from #49

Note this is a temporary work around: use the `--drive-full-list=false` flag

**Comment by ncw** [comment]
Here is a beta to try the fix for this: http://pub.rclone.org/v1.27-1-g5dd387f%CE%B2/

**Comment by robchallen** [comment]
Solves my issue described here 
[https://github.com/ncw/rclone/issues/49#issuecomment-180808036](url)
Seems to work on root directory without --drive-full-list flag.

**Comment by dolabriform** [comment]
Hi Nick

I've started seeing these pacer messages since using the new beta, I don't
remember seeing them before.. is this normal?

Regards

David

2016/02/12 22:30:01 drive: Saving new token in config file
2016/02/12 22:30:02 S3 bucket drive-backup: Modify window is 1ms
2016/02/12 22:30:02 S3 bucket drive-backup: Building file list
2016/02/12 22:30:03 pacer: Rate limited, increasing sleep to 20ms
2016/02/12 22:30:03 pacer: Rate limited, increasing sleep to 40ms
2016/02/12 22:30:03 pacer: Rate limited, increasing sleep to 80ms
2016/02/12 22:30:03 pacer: Rate limited, increasing sleep to 160ms
2016/02/12 22:30:03 pacer: Rate limited, increasing sleep to 320ms
2016/02/12 22:30:03 pacer: Rate limited, increasing sleep to 640ms
2016/02/12 22:30:03 pacer: Rate limited, increasing sleep to 1.28s
2016/02/12 22:30:04 pacer: Rate limited, increasing sleep to 2s
2016/02/12 22:30:07 Google drive root '': Finished reading


On 12 February 2016 at 21:58, Rob Challen <notifications@github.com> wrote:

> Solves my issue described here
> https://github.com/ncw/rclone/issues/49#issuecomment-180808036
> <http://url>
> Seems to work on root directory without --drive-full-list flag.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/336#issuecomment-183503259>.
>



-- 
--------------------
David White
07525 807295

**Comment by ncw** [comment]
I've merged this to master - you can find the fix in this beta

http://pub.rclone.org/v1.27-11-g1cd0d9a%CE%B2/

It will be in the next release

**Comment by ncw** [comment]
@dolabriform the pacer messages are normal - Drive does that when it is getting congested I think.
