### ISSUE TITLE
Allow read-only configuration for google drive?

### ISSUE THREAD

**Issue by mafm** [ncw/rclone#337]
Hi,

Thanks for the google drive export functionality - seems to work for me, and better than the alternatives I had been looking at.

The only thing that would make it better for me is having an option to configure read-only access to a google drive. Could not see how to do this in the docs or using the configure command.

**Comment by ncw** [comment]
This would be relatively simple to do at `rclone config` time - rclone could request a reduce set of permissions via oauth2 and then that remote would be read only.

I'l probably add another step in the config "Restrict rclone to read only? Y/N" or something like that.

Most of the other oauth based providers have this facility too I think

  * [Drive](https://developers.google.com/drive/v2/reference/permissions/list)
  * [Amazon Cloud Drive](https://developer.amazon.com/public/apis/experience/cloud-drive/content/getting-started)
  * [One drive](https://dev.onedrive.com/auth/msa_oauth.htm#authentication-scopes)
  * [Google cloud storage](https://cloud.google.com/storage/docs/authentication?hl=en#oauth-scopes)
  * Dropbox could allow access to app folder only, not so much read only

**Comment by mafm** [comment]
Thanks, that would be brilliant.

**Comment by ncw** [comment]
Found this snippet of code I was testing with - will be useful here!

```patch
diff --git a/drive/drive.go b/drive/drive.go
index fce2b69..12f711d 100644
--- a/drive/drive.go
+++ b/drive/drive.go
@@ -54,7 +54,8 @@ var (
        driveUploadCutoff = chunkSize
        // Description of how to auth for this app
        driveConfig = &oauth2.Config{
-               Scopes:       []string{"https://www.googleapis.com/auth/drive"},
+               Scopes: []string{"https://www.googleapis.com/auth/drive"},
+               //Scopes:       []string{"https://www.googleapis.com/auth/drive.readonly", "https://www.googleapis.com/auth/drive.metadata.readonly"},
                Endpoint:     google.Endpoint,
                ClientID:     rcloneClientID,
                ClientSecret: fs.Reveal(rcloneClientSecret),
```

**Comment by p-thurner** [comment]
I also would like this feature.

**Comment by ChoosenEye** [comment]
+1 for adding this feature?

**Comment by ncw** [comment]
I have made a beta for this feature here:

https://pub.rclone.org/v1.39-072-g158f26b8-drive-scope%CE%B2/

Note that you will have to make a new drive remote in order to make it work (or edit an old one and run through the oauth process again).

Here are the extra docs. I haven't put the new config flow in - hopefully that will be obvious what is happening.

Any feedback much appreciated!

### Scopes ###

Rclone allows you to select which scope you would like for rclone to use.  This changes what type of token is granted to rclone.  [The scopes are defined here](https://developers.google.com/drive/v2/web/about-auth).

The scope are

#### drive ####

This is the default scope and allows full access to all files, except for the Application Data Folder (see below).

Choose this one if you aren't sure.

#### drive.readonly ####

This allows read only access to all files.  Files may be listed and downloaded but not uploaded, renamed or deleted.

#### drive.file ####

With this scope rclone can read/view/modify only those files and folders it creates.

So if you uploaded files to drive via the web interface (or any other means) they will not be visible to rclone.

This can be useful if you are using rclone to backup data and you want to be sure confidential data on your drive is not visible to rclone.

Files created with this scope are visible in the web interface.

#### drive.appfolder ####

This gives rclone its own private area to store files.  Rclone will not be able to see any other files on your drive and you won't be able to see rclone's files from the web interface either.

#### drive.metadata.readonly ####

This allows read only access to file names only.  It does not allow rclone to download or upload data, or rename or delete files or directories.

### Root folder ID ###

You can set the `root_folder_id` for rclone.  This is the directory that rclone considers to be a the root of your drive.  Normally you will leave this blank and rclone will determine the correct root to use itself.

However you can set this to restrict rclone to a specific folder or to access the Backup and Sync "Computers" Folders/Files.  In order to do this you will have to find the Folder ID of the folder you wish rclone to display.  This will be the last segment of the URL when you open the folder.  So if the folder/computer backup you want to show looks like `https://drive.google.com/drive/folders/1XyfxxxxxxxxxxxxxxxxxxxxxxxxxKHCh` in the browser, then you use `1XyfxxxxxxxxxxxxxxxxxxxxxxxxxKHCh` as the `root_folder_id` in the config.

There doesn't appear to be an API to discover the folder IDs of the "Computers" tab - please contact us if you know otherwise!

**Comment by ncw** [comment]
I have merged this to master now :-)  Find the docs [here](https://github.com/ncw/rclone/blob/master/docs/content/drive.md#scopes).

https://beta.rclone.org/v1.39-088-ga4fe2455/ (uploaded in 15-30 mins)
