### ISSUE TITLE
b2: don't make temporary copy of files when uploading

### ISSUE THREAD

**Issue by nloui** [ncw/rclone#358]
Hi all, I'm getting a "no space left on device" when copying to /tmp error message.  Any thoughts on why? When I "df" the /tmp directory is only using 1% of its capacity.

**Comment by ncw** [comment]
What size files are you copying and which remote storage system. Also which OS?

**Comment by nloui** [comment]
Copying from a local drive mounted drive to Backblaze Storage via Linux

**Comment by ncw** [comment]
Currently rclone makes a temporary copy of the file it is copying before uploading to B2.  This is due to the way the b2 API works.  I'm hoping to turn that into reading the file twice, but that requires some re-architecting of rclone's internals.

There is a note about this on the b2 page: http://rclone.org/b2/

You can override which directory rclone uses to make temp file by setting the `TMPDIR` environment variable.

I'm going to turn this ticket into one to remind me to fix this properly!

**Comment by nloui** [comment]
Cool will try out the TMPDIR environment variable.  Not sure why it's having issues copying though when the directory has space available.

**Comment by klauspost** [comment]
Would be possible if #282 is implemented. I might give it a try.

**Comment by ncw** [comment]
@klauspost that would be fantastic!

**Comment by ncw** [comment]
The fix for this will be in the next release!

**Comment by ncw** [comment]
Here is a beta for you to try: http://pub.rclone.org/v1.27-23-ga3b4c8a%CE%B2/
