### ISSUE TITLE
Reading remote file list from Google Drive takes extremely long

### ISSUE THREAD

**Issue by gfxrelay** [ncw/rclone#381]
Hi, we seem to be running into an issue with rclone, when trying to sync with Google Drive. Whenever we try to sync, the initial remote reading of Google drive takes extremely long (2 hours or more) The data in Google drive is +- 120GB. The host OS is CentOS 7, rclone v 1.28 and the command is rclone /backup/ gdrive:backup

**Comment by ncw** [comment]
It is how many files that takes the time rather than the total number.  On my connection, I get about 10,000 files listed per minute.

Can you time just the file listing element of it with `rclone size gdrive:backup`?  That will also count the files.  Can you paste the output of it?

Can you also try the latest beta which is here also which you should find is much quicker with drive.

http://pub.rclone.org/v1.28-6-gfdd4b4e%CE%B2/

**Comment by gfxrelay** [comment]
Thanks for the reply. I tried the beta and it is a lot quicker, I have added -v and I seem to get rate limited a lot.

2016/03/08 06:34:23 pacer: Rate limited, increasing sleep to 2s
2016/03/08 06:34:23 pacer: low level retry 1/10
2016/03/08 06:34:53 pacer: low level retry 2/10
2016/03/08 06:34:57 pacer: Reducing sleep to 10ms

Is there anyway around this?

**Comment by ncw** [comment]
Great! The rate limit seems to be just the way Google drive works unfortunately. If you want never to be rate limited then you need to keep the request rate to below one per second and things take much much longer!

**Comment by ncw** [comment]
I'm going to close this issue - please re-open if you have more to add!

Thanks

Nick
