### ISSUE TITLE
A lot of errors - Backblaze B2

### ISSUE THREAD

**Issue by ti-font** [ncw/rclone#400]
Hi guys,

I was looking for a cheap option to backup the photos and videos I have on my Synology Diskstation DS212j. I discovered the Backblaze B2 + rclone option and I was really excited.

So I started uploading (copy) from my Synology to B2 using rclone (about 130.000 files).
The biggest heap was transferred without trouble, but there's also a large chunk of errors: over 17.000 on the first run.
The errors are not consistent, so I dont really know what's causing it. I hope you guys can help.

Errors I got:

- Failed to copy: error reading uploaded data (400 bad_request)
- Failed to copy: Post https://pod-000-1009-14.backblaze.com/b2api/v1/b2_upload_file/183d7a96738631cf5a360b18/c001_v0001009_t0023: dial tcp 162.244.60.223:443: getsockopt: connection refused
- Failed to copy: sha1 did not match data received (400 bad_request)
- Failed to copy: Failed to get upload URL: Post https://api001.backblaze.com/b2api/v1/b2_get_upload_url: remote error: unexpected message

I'm using rclone 1.28

**Comment by ti-font** [comment]
Got a new one:

- Failed to copy: more than one upload using auth token 3_20160322221519_34f3b417db203ad8e5309c22_cdba339648426736a592d2e9dccd04cf3fbb4730_001_upld (400 bad_request)

**Comment by ncw** [comment]
B2 normally works quite well for me.

None of the cloud storage providers are perfect - that is why rclone has the `--retries` option.  Hopefully rclone did retry the errors.  You can keep retrying the sync until it runs clean.

17,000 failures in 130,000 is a 13% failure rate which is certainly bigger than

Most of the errors you posted in your first comment I don't recognise - they look like b2 being overloaded or possibly your internet connection being throttled - I've seen this before on home ISP connections.

This error `Failed to copy: sha1 did not match data received (400 bad_request)` is a little worrying - that indicates something corrupted the data somewhere.

The last error `more than one upload using auth token` I do recognise - that should have been fixed in 6b6b43402b14a607695d9c05bff643c1837c81ea which was part of the v1.28 build.

Can you double check your rclone version with `rclone -V` please?  Did you see any other occurrences of that error?

Are you doing the upload from the synology itself?  Can you try from a different machine? Can you try with a different ISP (difficult I know!).

Thanks

Nick

**Comment by ti-font** [comment]
I'm currently running rclone for the 3rd time to get rid of the errors.. narrowed it down from 17,000 to 700 at the moment, so that's going well.

The `more than one upload using auth token` is pretty much the only error I'm getting right now (turned the amount of transfers down.. this seems to solve most errors)

DiskStation> rclone -V
rclone v1.28

**Comment by ncw** [comment]
How many transfers were you using?  I just uploaded 1000 files with `--transfers` set to 64 and 256 with no problems.  In fact b2 seems to work really well with `--transfers` set high.

I haven't been able to reproduce the `more than one upload using auth token` problem :-(

I've uploaded a beta of the latest code here - can you have a go and see if it makes a difference?

http://pub.rclone.org/v1.28-22-g93c60c3%CE%B2/

Note that you might want to use `--size-only` as the latest code supports modification time syncing (after a backblaze API change) so is likely to want to upload all your files again (unfortunately the backblaze API doesn't let you set the modification time without uploading the file again).

**Comment by ncw** [comment]
How have you been getting on with the beta?

**Comment by mejje** [comment]
I get 2016/06/18 09:33:11 2013-08-10/001.JPG: Failed to copy: Sha1 did not match data received (400 bad_request) on a lot of requests as well, can I help troubleshooting?

**Comment by ncw** [comment]
@mejje if you can reproduce that, then can you open a new issue please and put a log with `-v` in please.  Or even better with `-v` and `--dump-headers`.

Note that I'm about to release v1.30 so you should probably test with that.

**Comment by ncw** [comment]
We've fixed the sha1 problems in #533 so I'll close this one.  Please make a new ticket if you have any more specific issues.  Thanks, Nick
