### ISSUE TITLE
Swift: Cannot copy/sync file larger than 5GB

### ISSUE THREAD

**Issue by kudjo** [ncw/rclone#46]
Swift maximum file size is 5GB and if you want to upload bigger files to this storage, it has to be segmented (more info: http://docs.openstack.org/developer/swift/overview_large_objects.html). 

Unfortunately it looks like rclone does not support segmenting and if I try to upload 6GB file, it fails with:
large_file.img: Failed to copy: Too Large Object

Otherwise, great tool!!!

**Comment by ncw** [comment]
Yes you are correct.  rclone doesn't fragment files for swift so is limited to the 5 GB file size.

Some thought would need to be given to where to store the chunks and how to avoid seeing them in listings etc (in another container would probably be best).  There are some problems with the MD5SUMs of segmented files too, but it is all possible.

**Comment by swill** [comment]
I am guessing the limitation is actually in this implementation (https://github.com/ncw/swift) and it is showing up in this library because it uses that project.  Right?

As you mentioned, supporting chunking for Swift is not totally trivial.

**Comment by ncw** [comment]
@swill The limitation is in the swift object store.  It has a really clunky way of having files bigger than 5 GB - you have to upload the chunks as separate files then upload an index of them.

The problem is where to store the separate chunks - in a separate container would be ideal so the chunks don't appear in a normal directory listing.

Perhaps the thing to do would be to use the convention used by the swift tool and upload into a separate container called `..._segments`.  See [the openstack large objects doc](http://docs.openstack.org/developer/swift/overview_large_objects.html) for more info.

The [swift library you linked above](https://github.com/ncw/swift) supports all that just fine but rclone would have to do the heavy listing of making the `_segments` container, uploading the chunks etc.

I wasn't aware of the swift tool convention before - that makes the prospect of doing this a lot more appetizing!

**Comment by ctennis** [comment]
Just adding a +1 to this.  Amazon S3 suffers from the same thing, you have to chunk up >5GB objects, but the client library handles the nuance for you.  This is definitely a plus to have.

**Comment by ncw** [comment]
@ctennis I'm now using the official Amazon S3 library and also using the chunking support so it should be good for files up to the s3 maximum file size of 5TB.

**Comment by ctennis** [comment]
@ncw yup, got it, so the final blocker to this is just getting a similar type of interface into your swift go bindings, then rclone would be able to use that for larger objects like it does for S3?

**Comment by ncw** [comment]
@ctennis no patch to the swift module needed, just some code in rclone. It is a non trivial amount of code though :-(

**Comment by Tolsi** [comment]
+1

**Comment by ncw** [comment]
This feature will be released with rclone 1.22
