### ISSUE TITLE
lsl on ACD is sometimes incomplete

### ISSUE THREAD

**Issue by jkrinke** [ncw/rclone#475]
I run a cronjob that lists all files on ACD every twenty minutes to observe any changes (I have some problems with different tools in the past as I am using rclone, syncovery, and arq).

However, every few hours, the output of lsl is incomplete and leaves out files, usually a subset of one directory. During the next run, they are listed again.

When running with -v, nothing suspicious occurs.

I am unable to judge if it is a problem in clone or a problem with ACD.

When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)

1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 14.04

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone --stats 0 lsl AmazonCloud:/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by ncw** [comment]
I'm working on reporting errors in directory listings better at the moment.

Here is a test compiled from the new branch which should report errors in directory listings properly, exiting with an error if there were any.

http://pub.rclone.org/rclone-listdir-v1.29-23-gdbfa703.zip

That is what I suspect you are going to see.  The alternative is no errors, in which case I'd be pretty sure it is an Amazon problem.  Amazon do seem to be a bit flakey with their directory listings...

**Comment by jkrinke** [comment]
The issue still occurs. I have captured a huge log with the dumped bodies - would that help to diagnose the problem? I cannot see any error message from ACD and in one of the logs, some files don't occur despite being on ACD.

**Comment by ncw** [comment]
Send the log and I'll see what I can make of it! nick@craig-wood.com or share it on acd.

**Comment by ncw** [comment]
Thank you for those logs.

So the 17:00 and 17:40 seem to be OK but there are files missing in the 17:20 log.

The only errors in all the logs are these

lsl-160508-1720.log:2016/05/08 17:20:08 HTTP/1.1 429 Too Many Requests
lsl-160508-1720.log:2016/05/08 17:20:13 HTTP/1.1 429 Too Many Requests
lsl-160508-1720.log:2016/05/08 17:20:23 HTTP/1.1 500 Internal Server Error

This is almost certainly the cause of the problem...

Drilling into the first error, this is a directory listing broken into 3 chunks.

However in the 17:20 log one of the chunks is missing.

What it looks like is that when rclone retried the directory listing using the token for chunk 2 amazon actually supplied chunk 3.

This indicates that it isn't safe to retry a directory listing with a token.  

I've reported a bug to amazon here: https://forums.developer.amazon.com/forums/thread.jspa?threadID=13107

I'm testing out a fix - I'll post a binary for you to try in a bit

**Comment by ncw** [comment]
I managed to reproduce the problem and I managed to make a fix for it.

Here is a binary for you to try: http://pub.rclone.org/rclone-v1.29-24-g2db35f0-listdir.zip

I don't recommend you use that binary for anything other than listing directories at the moment, but I'm pretty sure it will fix your problem. I need to integrate quite a few changes and do a proper merge, but that binary should be good for a test!

**Comment by jkrinke** [comment]
Thanks! I will test the new version with my script.

**Comment by ncw** [comment]
Here is a better tested beta which should perform all the normal functions of rclone and have the fix: http://pub.rclone.org/v1.29-28-g36700d3%CE%B2/

**Comment by ncw** [comment]
Please re-open this if it doesn't work!

**Comment by jkrinke** [comment]
So far, the 1.29-24 version worked well over the past couple of days. I'll try the new beta now

**Comment by jkrinke** [comment]
The new version is better, but the problem has not been removed completely. Files are still sometimes not listed with lsl. 

I'll watch it more closely and will capture logs is necessary.

**Comment by ncw** [comment]
@jkrinke if you can capture a log that would be super helpful - thanks.

**Comment by ncw** [comment]
BTW I tested this by listing a directory with two subdirectories, each with 10,000 files,  I then ran 250 simultaneous lists to stress the system a bit.  In that test with the latest beta above, rclone either returned all 20,000 files or returned an error, it never returned less than 20,000 files without an error.

Can you check if rclone is returning an error in your tests too?

**Comment by jkrinke** [comment]
I will capture logs. rclone is not returning an error (if rclone returns an error, I throw the listing away),

**Comment by ppuskari** [comment]
Not sure if this is related but it appears that after a deep directory listing that the token expires and then rclone just sits there with this latest build.  I get the errors in the -v logging.  In order to sync files it looks like I have to start with shallow listings on the ACD side or fresh folders entirely then normal copying commences.  So basically if a token expires in the directory listing process forget it actually working it seems.  Iv'e tried with the latest beta above.

2016/05/24 08:55:42 pacer: low level retry 1/1
2016/05/24 08:55:42 Amazon cloud drive root 't0/t0/Unsorted': Directory listing error for "From Humyo/OSX Files/Extensions/AppleHIDMouse.kext/Contents/PlugIns/AppleUSBHIDMouse.kext/Contents/MacOS/": HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
 - low level retry 1/10
2016/05/24 08:55:42 pacer: low level retry 1/1
2016/05/24 08:55:42 Amazon cloud drive root 't0/t0/Unsorted': Directory listing error for "Raspberrypi/kernel/arch/blackfin/lib/": HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
 - low level retry 2/10
2016/05/24 08:55:42 Amazon cloud drive root 't0/t0/Unsorted': Finished reading "128mb usb pen HP/html/"
2016/05/24 08:55:42 Amazon cloud drive root 't0/t0/Unsorted': Reading "Transferfromxeon/Album Artwork/Cloud Purchases/749285D267218C8F/05/"
2016/05/24 08:55:42 pacer: Rate limited, sleeping for 2m38.113578338s (9 consecutive low level retries)
2016/05/24 08:55:42 pacer: low level retry 1/1
2016/05/24 08:55:42 Amazon cloud drive root 't0/t0/Unsorted': Directory listing error for "Raspberrypi/kernel/arch/m68k/configs/": HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
 - low level retry 2/10
2016/05/24 08:56:00 pacer: Resetting sleep to minimum 20ms on success
2016/05/24 08:56:38
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      5m2.7s

**Comment by ncw** [comment]
I think that is a different problem - see #493 for background.

I made a beta with a potential fix for that here (it has the changes in the version above too)

http://pub.rclone.org/v1.29-30-g53ead43%CE%B2/

That should specifically fix the token expired 401 problems.

**Comment by ncw** [comment]
Here is a second attempt to fix the 401 errors - I think this one will work properly (cross fingers!)

http://pub.rclone.org/v1.29-30-g33611be%CE%B2/

**Comment by ppuskari** [comment]
So far so good!  I have seen it timeout prematurely and then the code requests a refresh.  So far 10 low-level-retries seems to be holding fine now.  Will advise if any of this changes as I'm now doing a massively deep volume set compare at present.  Should take about 20 mins just to do the cataloging.

**Comment by ppuskari** [comment]
Bummer - Spoke too soon. -- Worked for medium sized folder sets... But this one not so much and after about 25 minutes I get this.....

2016/05/27 02:53:22 pacer: Rate limited, sleeping for 1m47.970226631s (8 consecutive low level retries)
2016/05/27 02:53:22 Amazon cloud drive root 't0': Directory listing error for "t0/Unsorted/Transferfromxeon/Album Artwork/Cache/749285D267218C8F/13/02/": HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
 - low level retry 1/15
2016/05/27 02:53:22 pacer: low level retry 1/1
2016/05/27 02:53:22 pacer: Rate limited, sleeping for 2m46.075832456s (9 consecutive low level retries)
2016/05/27 02:53:22 pacer: low level retry 1/1
2016/05/27 02:53:22 Amazon cloud drive root 't0': Directory listing error for "t0/Unsorted/OSX1058 Support/FileZilla.app/Contents/SharedSupport/resources/cyril/16x16/": HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
 - low level retry 1/15
2016/05/27 02:53:22 Amazon cloud drive root 't0': Directory listing error for "t0/Unsorted/128mb usb pen HP/html/": HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
 - low level retry 1/15
2016/05/27 02:53:22 pacer: Rate limited, sleeping for 1m41.163567271s (9 consecutive low level retries)
2016/05/27 02:53:22 pacer: low level retry 1/1
2016/05/27 02:53:22 Amazon cloud drive root 't0': Directory listing error for "t0/rescue/PamelaDenPC/Documents/iTunes/iTunes Music/Michael W. Smith/": HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
 - low level retry 1/15
2016/05/27 02:53:22 pacer: Rate limited, sleeping for 2m59.472365252s (9 consecutive low level retries)
2016/05/27 02:53:22 pacer: low level retry 1/1
2016/05/27 02:53:22 Amazon cloud drive root 't0': Directory listing error for "t0/rescue/win7/21Gig_Boot/Google Bookmarks/Extensions/blpcfgokakmgnkcojhhkbfbldkacnbeo/4.2.5_0/_locales/th/": HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
 - low level retry 1/15
2016/05/27 02:53:22 pacer: Resetting sleep to minimum 20ms on success
2016/05/27 02:53:22 Amazon cloud drive root 't0': Error reading : HTTP code 403: "403 Forbidden", reponse body: {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Bearer"}
2016/05/27 02:53:22 Amazon cloud drive root 't0': Reading "t0/Unsorted/OSX1058 Support/Extensions/webdav_fs.kext/Contents/Resources/"
2016/05/27 02:53:22 Amazon cloud drive root 't0': Error building file list: HTTP code 403: "403 Forbidden", reponse body: {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Bearer"}
2016/05/27 02:53:22 Attempt 3/3 failed with 0 errors and: HTTP code 403: "403 Forbidden", reponse body: {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Bearer"}
2016/05/27 02:53:22 Failed to sync: HTTP code 403: "403 Forbidden", reponse body: {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Bearer"}

**Comment by ncw** [comment]
Glad to see the 401 retry is working.

The message `HTTP code 403: "403 Forbidden", reponse body: {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Bearer"}` is straight from S3 (ie the underlying storage of ACD) by the look of it.  ACD doesn't uses `SignedHeaders`.  So that is probably an Amazon bug.

I've made a thread about this on the developer forum: https://forums.developer.amazon.com/questions/28183/403-forbidden-reponse-body-messageauthorization-he.html

If you could get me the error response with `--dump-headers` Amazon will need that to trace through their logs.
