### ISSUE TITLE
Question: how does the sync option work for b2?

### ISSUE THREAD

**Issue by shuhaowu** [ncw/rclone#507]
This is not a bug report, just a question. Not sure where else is a good place to ask.

How does the B2 sync work? Does it compute a local sha and then get the remote sha from the file metadata? If it does not match it will upload the file? How does the modification time comes into play with this (if sha is the same but modification time is different, or if modification time is the same and sha is different)?

From the B2 page:

>Modified times are used in syncing and are fully supported except in the case of updating a modification time on an existing object. In this case the object will be uploaded again as B2 doesn’t have an API method to set the modification time independent of doing an upload.

> The SHA1 checksums of the files are checked on upload and download and will be used in the syncing process. 

I don't quite understand how this works. Can someone clarify?

**Comment by ncw** [comment]
rclone (like rsync) checks the modification date and the size first and if those differ does the upload.

If the size is the same, then rclone checks the sha1 and if that is identical then it updates the modification time.  For b2 you can't change the modification time of an object, so that means uploading it again.

If you'd rather use the size and sha1 checksum first then you want the `--checksum` option which causes rclone to upload if the size or sha1 checksum is different.

As for this part

> The SHA1 checksums of the files are checked on upload and download and will be used in the syncing process.

rclone checks the sha1 sums of objects it uploads to make sure they got uploaded properly, and downloads to make sure the data wansn't corrupted.

Hope that helps!

Nick

**Comment by shuhaowu** [comment]
> If you'd rather use the size and sha1 checksum first then you want the --checksum option which causes rclone to upload if the size or sha1 checksum is different.

Does it check modification date after? I would like to avoid downloading again if possible because it would be very expensive.

Other than that thanks for the fast clarification! :)

**Comment by ncw** [comment]
No `--checksum` only checks the size and the checksum.

**Comment by shuhaowu** [comment]
Thanks for letting me know!
