### ISSUE TITLE
Optionally sync/copy/move directory at a time

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#517]
Make `--dir-at-a-time` option. I don't like this name, but nothing else comes to mind at the moment!

This would make copy/sync/move do each directory at a time, not attempting to get an entire list of the remote in advance.

This would be useful to reduce memory usage and to reduce scanning. It would decrease efficiency in the general case.

This would help with these tickets
- #498
- #439 
- #236
- #8

**Comment by lucasecomm** [comment]
I've waited for something like this.

I think this is a good thing. Thanks

**Comment by gregfr** [comment]
Some software use the "prune" name for similar options

**Comment by diamondsw** [comment]
I've got some truly mammoth directory structures that would benefit hugely from this. For now, using copy with --no-traverse, but at some point I'll need to sync and delete old cruft.

It might be worth examining how much this impacts the general case; if the impact is relatively small perhaps this should be the default and scanning everything in one go becomes the special case with a flag (--scan-all?).

**Comment by diamondsw** [comment]
Idea for naming: "--depth-first", since presumably rclone would need to use a depth-first recursive search of the directory structure to minimize the memory/scanning footprint. I'd still say it's worth checking the real-world impact in a variety of scenarios and seeing if it's worth just making rclone use single directory scanning by default.

**Comment by DurvalMenezes** [comment]
diamondsw commented on Nov 19, 2016: 
> It might be worth examining how much this impacts the general case; if the impact is relatively small perhaps this should be the default and scanning everything in one go becomes the special case with a flag (--scan-all?) 

That would be exactly my suggestion. I think this should be the default at least for the "rclone sync --no-traverse" case, and the "--scan-all" flag would revert to the old behavior. 

Cheers,
Durval.

**Comment by ncw** [comment]
@diamondsw @DurvalMenezes I think rsync uses a similar idea

```
       -r, --recursive
              This  tells  rsync  to  copy  directories recursively.  See also
              --dirs (-d).

              Beginning with rsync 3.0.0, the recursive algorithm used is  now
              an  incremental  scan that uses much less memory than before and
              begins the transfer after the scanning of the first few directo‐
              ries  have  been  completed.  This incremental scan only affects
              our recursion algorithm, and does  not  change  a  non-recursive
              transfer.  It is also only possible when both ends of the trans‐
              fer are at least version 3.0.0.

              Some options require rsync to know the full file list, so  these
              options  disable the incremental recursion mode.  These include:
              --delete-before,   --delete-after,    --prune-empty-dirs,    and
              --delay-updates.   Because of this, the default delete mode when
              you specify --delete is now --delete-during when  both  ends  of
              the  connection are at least 3.0.0 (use --del or --delete-during
              to request this improved deletion mode  explicitly).   See  also
              the  --delete-delay  option  that  is a better choice than using
              --delete-after.

              Incremental recursion can be disabled using the  --no-inc-recur‐
              sive option or its shorter --no-i-r alias.
```

It would probably be worth studying exactly how it works.

On some remotes this will be a lot slower and on some it may make no difference...

I'm having second thoughts about the implementation though - doing one directory at a time doesn't fit in well with the rclone architecture.

Thinking about this some more, probably the best way if implementing this would be to make the directory listings optionally produce a sorted output.  This would mean that they couldn't list different directories in parallel, but it would make the syncing algorithm much easier as you would know exactly what you needed to copy or delete and you wouldn't need to store either the source of the destination listing at all.

Will ponder some more...

**Comment by ncw** [comment]
I'm approaching the time when I'm going to need some beta testers for the new sync algorithm.

It passes all the unit tests and my own usage - now it needs some testing from other people...

Any volunteers?

**Comment by qnorsten** [comment]
I can probably test it on drive if you want.

**Comment by ncw** [comment]
Here is a beta for this feature.  There is a temporary flag `--old-sync-method` to select the old sync method.

It should work identically to current rclone, except using a lot less memory.

http://pub.rclone.org/v1.35-50-g9d88ce3-low-mem-sync%CE%B2/

It is a major re-work of the syncing internals.  All the unit tests pass, and the code is well covered.  My own smoke tests pass too.

Test with care - use --dry-run first!

I'm particularly interested in 
  * any bugs
  * memory usage differences before vs after - especially on big syncs
  * speed differences before vs after

You can run this little ditty in another window to see rclone memory usage

    while [ true ]; do ps -eo rss,args --sort rss | grep [r]clone ; sleep 0.5 ; done

**Comment by qnorsten** [comment]
Thanks @ncw will try and perform some tests in a few days and report back:)

**Comment by ncw** [comment]
I have merged this to master now - see here for a beta:

http://beta.rclone.org/v1.35-74-g48cdedc/

Any feedback much appreciated

**Comment by diamondsw** [comment]
I'll see if I can toss this at some of my mammoth directories and get some results for you. 👍

**Comment by DurvalMenezes** [comment]
Hello @ncw, 

> I have merged this to master now - see here for a beta:
> http://beta.rclone.org/v1.35-74-g48cdedc/
> Any feedback much appreciated

I have it running here for the last ~8h:
`rclone --dry-run --bwlimit 4700K --low-level-retries=100 --checkers=12 --transfers=12 -v --log-file=./20170205Z040712_rclone_sync_REDACTED_egd --backup-dir=egd:REDACTED_-_backup-dir_-_20170205Z040712 sync /REDACTED egd:REDACTED`

I'm also capturing the memory usage for the process as you requested, just using a 60-second interval instead of a 0.5 -second (the half-sec output was kind of annoying me).

It has already processed 1505702 ("Checks") + 79107 ("Transferred") of ~8M files total for /REDACTED, so the dry run should be over in another 1.5 days or so. 

Regarding memory usage (from the output of the above one-liner): After an initial, strong and monotonic increase from ~60MB up to ~300MB, I saw a sawteeth-like up curve (ie, mostly up, but with some downs) from them on, going up to ~500MB so far. 

See here for a graph: ![rclone_beta_new_sync_code_test](https://cloud.githubusercontent.com/assets/5405638/22626158/b2ecdb54-eb8e-11e6-9df4-c01008e8907d.jpg)

This IMHO compares very favorably with the "old" (ie, previous algorithm): by now, rclone would have already eaten through all of my 8GB RAM and plus 25GB of swap I was able to make available to it then, before giving up on sync (see [here](https://forum.rclone.org/t/no-traverse-does-not-work-with-sync-possible-improvement/816) for the whole story). 

Please let me know if you need/want anything else.

Alas, what should I watch for in the log file, before running it without the "--dry-run" switch? 

Cheers, 
-- 
   Durval.

**Comment by ncw** [comment]
@DurvalMenezes Thanks for testing - very good data.

> OTOH, if directories are processed one by one, why is the RSS always increasing? Shouldn't it just "reset" to a lower-bound memory usage after each directory? Or is there possibly memory leak somewhere?

I'm not 100% sure... It might be the directory cache which caches directory names to IDs

It will also be keeping a note of files to delete as the default setting is --delete-after which requires them to be stored.  You can use --delete-during if you want to use less memory.

And there is memory fragmentation which is always a problem.  I would expect that to plateau though.

> Also, what should I watch for in the log file, before running it without the "--dry-run" switch?

Make sure it is copying the files you expect and deleting the files you expect.

> Please let me know if you need/want anything else.

What you are doing is brilliant - thanks.

**Comment by DurvalMenezes** [comment]
Hello @ncw, 

> I'm not 100% sure... It might be the directory cache which caches directory names to IDs
> 
> It will also be keeping a note of files to delete as the default setting is --delete-after which requires > them to be stored. You can use --delete-during if you want to use less memory.
> 
> And there is memory fragmentation which is always a problem. I would expect that to plateau though.

When I do the real run (without the "--dry-run"), I will run it with "--delete-during" and then report back on the memory aspect.

> Make sure it is copying the files you expect and deleting the files you expect.
OK, but it's literally millions of files, so I will do some sample checking for a few of the the "deleting" and "copying" messages in the log before running it for real (plus of course my de rigueur "find ... | md5sum" on top of an rclone mount, after all is said and done).

> What you are doing is brilliant - thanks.
Thank you for your kind words, Nick. It's my pleasure to be able to collaborate, however humbly, with such a great project as rclone. 

Cheers, 
   Durval.

**Comment by DurvalMenezes** [comment]
Humrmrmrmr... something unexpected is happening here: the "rclone --dry-run sync" I started yesterday is still running, but the counters are now *way* over the number of files that should exist both in the remote and in the local file system:

```
2017/02/06 13:21:36 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:          10876250
Transferred:      2357111
Elapsed time:   35h5m2.3s
```

The local file system has exactly 7904717 files (counted with "find ... -type f | wc -l" and the remote should have way less than that (around 5M files at my last count), so where are those 10.8+2.4= 13.2M files coming from? 

@ncw, can you shine a light on this? 

Cheers, 
   Durval.

**Comment by ncw** [comment]
> OK, but it's literally millions of files, so I will do some sample checking for a few of the the "deleting" and "copying" messages in the log before running it for real (plus of course my de rigueur "find ... | md5sum" on top of an rclone mount, after all is said and done).

Sanity check is fine.  Your md5sum check will be the best check.

> Humrmrmrmr... something unexpected is happening here: the "rclone --dry-run sync" I started yesterday is still running, but the counters are now way over the number of files that should exist both in the remote and in the local file system:

Probably something went wrong and rclone is doing a retry.  Grep the logs for that.

**Comment by DurvalMenezes** [comment]
Hello @ncw, 

Thanks for the prompt response. More below: 
> Probably something went wrong and rclone is doing a retry. Grep the logs for that.

Just did: 
`grep -i retry\|error ./20170205Z040712_rclone_sync_REDACTED_REDACTED
`
But it showed absolutely nothing. 

Any hints on what I should be grepping for?

Thanks, 
   Durval.

**Comment by ncw** [comment]
@DurvalMenezes 

> Just did:
> grep -i retry\|error ./20170205Z040712_rclone_sync_REDACTED_REDACTED
> But it showed absolutely nothing.
> 
> Any hints on what I should be grepping for?

You should get a message `Attempt %d/%d failed with %d errors`

> And, are retries really accounted for on "Checks" and "Transferred"? I was under the impression that these two numbers only reflected final files checked and transferred, independent of any retries.

I had a look in the source and the only thing that gets reset around retries are errors - the transfers and checks will continue to count up.

**Comment by DurvalMenezes** [comment]
Hello @ncw,

> You should get a message Attempt %d/%d failed with %d errors

My previous grep was wrong, should have used 'egrep' instead due to the "|". Anyway, redid it with 'egrep', and got a TON of false positives... seems 'error' and/or 'retries' are very popular substrings in filenames... :-/

Anyway, just ran another grep searching for exactly the message you indicated above:

```
fgrep 'failed with'  ./20170205Z040712_rclone_sync_REDACTED_REDACTED
2017/02/06 05:51:03 Attempt 1/3 failed with 0 errors and: error reading source directory "REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED_+�_REDACTED+�REDACTED": directory not found
2017/02/06 14:18:51 Attempt 2/3 failed with 0 errors and: error reading source directory "REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED_+�_REDACTED+�REDACTED": directory not found
2017/02/06 22:35:55 Attempt 3/3 failed with 0 errors and: error reading source directory "REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED_+�_REDACTED+�REDACTED": directory not found
```

Some notes:
1) It was the same path/file being mentioned in the three lines. 
2) The "tofu" (?) character `�` was also shown twice, in exact the same position.
3) There were no other messages but the 3 above (for the same file). 

A tentative conclusion: I don't think these 3 retries (referring all to the same 1 error on 1 file) explain the large amount of extra files being shown by sync (ie, more than 13M when it should have been less than 8M).

@ncw, any more ideas on stuff to check? 

Cheers, 
   Durval.

**Comment by ncw** [comment]
> It was the same path/file being mentioned in the three lines.

Hmm, can you see that path in the web interface? What about your local disk?

> The "tofu" (?) character � was also shown twice, in exact the same position.

That is indicative of a non UTF-8 character, ie some latin1 encoding.

That might mean you need to run `convmv` tool ok your locak disk to make the file name encodings UTF-8 rather than latin1.

> A tentative conclusion: I don't think these 3 retries (referring all to the same 1 error on 1 file) explain the large amount of extra files being shown by sync (ie, more than 13M when it should have been less than 8M).

The retries will have caused a complete rescan of the files.  So at a guess it found this error after scanning 4ish M files, then repeated it twice more to give 13M in total.

**Comment by DurvalMenezes** [comment]
Hello @ncw,

OK, so I'm doing another run of that, this time for real (no "--dry-run"):
`rclone --bwlimit 4700K --low-level-retries 100 --checkers 12 --transfers 12 -v --log-file=./20170218Z234350_rclone_sync_REDACTED_REDACTED --backup-dir=REDACTED:REDACTED_-_backup-dir_-_20170218Z234350 sync /REDACTED REDACTED:REDACTED
`

This is with the latest beta (v1.35-99-g6fc114dβ) and so far things seem OK:
```
Transferred:   14.307 GBytes (199.541 kBytes/s)
Errors:                 0
Checks:           2469893
Transferred:       202182
Elapsed time:  20h53m1.1s
```

This looks like *great* performance for me: the last time I did a copy on the above source and destination, at 20h it had only `Checks:            249388` and `Transferred:            0`, so the current behavior seems to win hands-down (at least if it's possible to directly compare sync and copy numbers). 

I did not do the "convmv" thing you suggested (actually I forgot about it until now) but it seems the copy is progressing nonetheless. Just checked the log for said "REDACTED" file and saw this:

`2017/02/18 23:20:47 NOTICE: Local file system at /REDACTED: Replacing invalid UTF-8 characters in "REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED"`

Way to go, @ncw! Much better replacing the char than redoing the entire thing just to abort at the end, as happened with the previous version above.

If it continues with the speed it has been showing so far, I expect it will finish in just a few more days. I will report back then, sooner if anything else happens in the meantime. 

Cheers, 
   Durval.

**Comment by ncw** [comment]
@DurvalMenezes thanks for the update - looking good for 1.36 :-)

**Comment by DurvalMenezes** [comment]
Hello @ncw, 

So, my above `rclone sync` started 'looping' (going over all the same files all over again) after ~4 days... I went in to check and saw that it was doing that because it got errors very similar to the above the first time, but with a twist: 

`2017/02/24 19:09:57 NOTICE: Local file system at /REDACTED: Can't store file with control characters: "REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/\x1b"`

So there are some invalid characters (like the ESC above) that rclone doesn't try to replace... my question is, shouldn't it try to replace them too, by the same rationale that justifies replacing invalid UTF-8 characters? 

Anyway, As it wasn't an absurd amount of files (just a few dozen), I fixed them manually (by renaming it in the local filesystem and replacing said invalid chars with '#') and am now running the same "rclone sync" command again. Hope all goes well this time around. Again, will keep you posted.

Cheers, 
   Durval.

**Comment by ncw** [comment]
> shouldn't it try to replace them too, by the same rationale that justifies replacing invalid UTF-8 characters?

I am planning to do this as part of the next release.  It is quite a big change but my hope is to make it so that all file names can be copied anywere, with a bit of escaping - different escaping needed on windows or drive or acd for instance.
