### ISSUE TITLE
Sha1 did not match data received

### ISSUE THREAD

**Issue by mejje** [ncw/rclone#533]
Receiving a lot of these, 2016/06/18 09:33:11 2013-08-10/001.JPG: Failed to copy: Sha1 did not match data received (400 bad_request).

> What is your rclone version (eg output from `rclone -V`)

rclone v1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian Etch x86_64 (ReadyNAS Ultra 4)

> Which cloud storage system are you using? (eg Google Drive)

B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync /c/pictures b2:mejje-pictures -v --dump-headers

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

With headers (excluding Authorization)
https://gist.github.com/mejje/c608f2bfba0b6aff1fe913927d6a1434

And it looks like this with regular logging
```
2016/06/18 21:20:12 2015-05-05/IMG_0361.JPG: Received error: c001_v0001030_t0037 is too busy (503 service_unavailable) - low level retry 1/10
2016/06/18 21:20:16 2009-06-27/DSC_0040.JPG: Received error: c001_v0001030_t0021 is too busy (503 service_unavailable) - low level retry 1/10
2016/06/18 21:20:23 2015-05-05/IMG_0361.JPG: Failed to copy: Sha1 did not match data received (400 bad_request)
2016/06/18 21:20:26 2009-06-27/DSC_0040.JPG: Failed to copy: Sha1 did not match data received (400 bad_request)
2016/06/18 21:20:40 2009-06-27/DSC_0088.JPG: Received error: c001_v0001030_t0037 is too busy (503 service_unavailable) - low level retry 1/10
2016/06/18 21:20:49 2009-06-27/DSC_0088.JPG: Failed to copy: Sha1 did not match data received (400 bad_request)
```

**Comment by mejje** [comment]
Will try 1.30 with a new bucket

**Comment by mejje** [comment]
Same issue with 1.30, log with headers:
https://gist.github.com/mejje/87c1629ac270d26aa859fc2e938d7cb6

file is IMG_9129.JPG

**Comment by ncw** [comment]
Excellent bug report - thanks :-)

Thanks for those logs - I can see that there is a problem with the retries...  The sha1 changes for the second retry which is very strange since assuming you are reading from the local filesystem then it should be cached in the object at that point.

I tried to simulate the problem by forcing a retry but I didn't manage to so there must be something else going on.

```
2016/06/18 23:41:23 POST /b2api/v1/b2_upload_file/c8995750732968595c560516/c001_v0001030_t0001 HTTP/1.1
Host: pod-000-1030-08.backblaze.com
User-Agent: rclone/v1.30
Content-Length: 3459189
Authorization: removed
Content-Type: image/jpeg
X-Bz-Content-Sha1: 0d6507aa7623230e21691a79c03a329975fab584
X-Bz-File-Name: 2009-07-27/IMG_9129.JPG
x-bz-info-src_last_modified_millis: 1286992637666
Accept-Encoding: gzip
```

And on the first retry it looks like this

```
2016/06/18 23:41:24 POST /b2api/v1/b2_upload_file/c8995750732968595c560516/c001_v0001030_t0001 HTTP/1.1
Host: pod-000-1030-08.backblaze.com
User-Agent: rclone/v1.30
Content-Length: 3459189
Authorization: removed
Content-Type: image/jpeg
X-Bz-Content-Sha1: 597831486f9228ad26ff522058d275512f6bb8f9
X-Bz-File-Name: 2009-07-27/IMG_9129.JPG
x-bz-info-src_last_modified_millis: 1286992637666
Accept-Encoding: gzip
```

Can you check the sha1 of that file for me both with sha1sum and rclone?

```
sha1sum /c/pictures/2009-07-27/IMG_9129.JPG
rclone sha1sum /c/pictures/2009-07-27/IMG_9129.JPG
```

Could you run those commands several times and make sure they give the same answer each time!

Some other questions for you
  * Is it always that file which is a problem?
  * What type of file system is `/c/pictures`

**Comment by mejje** [comment]
```
mejjeNAS:~# sha1sum /c/pictures/2009-07-27/IMG_9129.JPG
0d6507aa7623230e21691a79c03a329975fab584  /c/pictures/2009-07-27/IMG_9129.JPG
mejjeNAS:~# rclone sha1sum /c/pictures/2009-07-27/IMG_9129.JPG
0d6507aa7623230e21691a79c03a329975fab584  IMG_9129.JPG
```

Ran them several times, no diff.
The file was uploaded without issue in the next rclone run.

`/dev/c/c on /c type ext4 (rw,noatime,nodiratime,acl,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv1)`

**Comment by klauspost** [comment]
Bam, found it!

If the file is closed without having the entire body consumed, the [hash is updated](https://github.com/ncw/rclone/blob/master/local/local.go#L570) to the partial value. We need to keep track of the consumed bytes in the reader above, and only update hashes if the consumed size matches the expected size.

**Comment by ncw** [comment]
Well spotted @klauspost - excellent sleuthing!

I'm just trying to think through the sequence of events
  * local.Object.Open() is called in fs.Copy()
  * b2.Fs.Update() is called
  * This then calls local.Object.Hash(fs.HashSHA1)
  * This calculates the sha1 and sets it in the object
  * We try the PUT but it is rejected.
  * b2 must reject it without reading the whole stream as we aren't using `Expect: 100-continue`
  * local.Object.Close() is called by fs.Copy() and overwrites the correct hash it with a corrupt hash

So that indicates that your patch is doing the right thing :-)

It also indicates that we should probably not overwrite the hash in the local.Object.Close if it is already set.  Actually re-reading your patch I see you've done exactly that :-)

**Comment by ncw** [comment]
@mejje here is a beta for you to try with @klauspost fix.

Please re-open the ticket if it doesn't work!

Thanks

http://pub.rclone.org/v1.30-2-ge0aa4bb%CE%B2/

**Comment by mejje** [comment]
It works fine now! Thanks for the speedy fix :).

Curiously, the files that were retried (with the b2_hide_file 400 response) are still hidden in the b2 web UI. They are present in rclone ls though so I guess it's an issue on their end.

**Comment by ncw** [comment]
Thanks for testing! 

It is probably a caching thing on the website - that would be my guess.

**Comment by DavidCWGA** [comment]
This issue is closed but I'm seeing this exact problem with v1.33 backing up to b2. "Failed to copy: Sha1 did not match data received" over and over again, and no file ever gets successfully uploaded.

**Comment by bittylicious** [comment]
@DavidCWGA I'm also seeing this when backing up to b2. I'm not sure this is entirely fixed.

**Comment by ncw** [comment]
@DavidCWGA @bittylicious I conjecture you are using crypt with b2 and this is 
#644 - here is a beta which should fix the problem:

http://pub.rclone.org/v1.33-6-g2eaac80%CE%B2/

If not can you open a new issue please with full info and a log with -v please?

**Comment by bittylicious** [comment]
The sha1 issue seems to be resolved but nothing is copied when using the crypted destination. See #686 for the new issue report.
