### ISSUE TITLE
[gcs] backend errors

### ISSUE THREAD

**Issue by atweiden** [ncw/rclone#550]
> What is your rclone version (eg output from `rclone -V`)

1.30

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Arch Linux 64 bit

> Which cloud storage system are you using? (eg Google Drive)

Google Cloud Storage

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone copy ~/.backup remote:backup`

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

```
2016/06/28 12:45:39 E9E/B0F1C92F67C452B8AB0A0F1B5E537: Failed to copy: googleapi: Error 500: Backend Error, backendError
```

(also have seen Error 503)

**Comment by atweiden** [comment]
I didn't know about the `--retries` flag. I should try that next time.

I have to sync thousands of 32K files from [cryfs](https://github.com/cryfs/cryfs).

**Comment by ncw** [comment]
You get 3 retries by default.

Can you answer these questions for me?
  * Do these errors happen every now and again, or very often?
  * Do they always affect the same files?
  * What size are they?

Thanks

**Comment by atweiden** [comment]
The backend errors aren't occurring anymore.

File size is 32 kilobytes.

Previously, errors were raised on random files.

**Comment by atweiden** [comment]
I just ran rclone with `--retries 25`. I'm still getting "Failed to copy: googleapi: Error 503: Backend Error, backendError".

I'll find out soon enough whether rclone works past these errors despite the fact that I've seen no "retry" output from rclone.

**Comment by atweiden** [comment]
rclone works successfully even with gcs backend errors.

**Comment by ncw** [comment]
503 Errors are most likely caused by the service being overloaded.  It is just possible that rclone is sending something which is upsetting GCS but it should really be returning a 4xx error code in that case.  It doesn't sound like there is a common thread between your files though.

I made myself an issue to address this in the future.  #556 

In the mean time using a higher value for `--retries` will work just fine, though a little less eficiently.
