### ISSUE TITLE
Implement cleanup for other remotes

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#575]
Implement cleanup for remotes
- [x] amazonclouddrive - not possible
- [x] b2 - done in #462
- [x] box - not possible easily (see below)
- [x] drive
- [x] dropbox - not possible
- [x] googlecloudstorage - not possible
- [x] hubic - not possible
- [x] local - not possible
- [x] onedrive - not possible
- [x] s3 - not possible
- [x] swift  - not possible
- [x] yandex

**Comment by cederberg** [comment]
Trying v1.34 of rclone, I can't seem to get `rclone cleanup` to work properly against B2. The files remain listed (hidden) in the Backblaze file browser tool (web site).

Strangely, the hidden files do not show up when running `rclone cleanup -v ...`. A guess might be that this is the root cause. Also tried with the `--b2-versions` flag, but to no avail.

**Comment by ncw** [comment]
@cederberg `rclone cleanup` should work properly with b2 now.  Can you open a new issue with a log file and some instructions on how to reproduce please?  I thought this might be related to #604 but I fixed that apparently!

**Comment by cederberg** [comment]
Hmm. Tried to reproduce, but now it works. Weird. The B2 web UI is sometimes slow, but shouldn't take several minutes to update... Hmm...

Ignore this for now. I'll file a proper bug if I see this again (and can repro the issue). Thanks for the quick support!

**Comment by ncw** [comment]
@cederberg might be caching I suppose... File a bug if you can reproduce it!  Thanks, Nick

**Comment by eharris** [comment]
I haven't had a chance to dig into the code yet, but I'm wondering if cleanup is smart enough to only "cleanup" the files that rclone deleted, or if it does a whole-storage empty/purge?  If the latter, I'm not sure I'd be comfortable with that without a pretty clear confirmation or `--yes-really` kind of option.

**Comment by ncw** [comment]
@eharris cleanup will do its stuff on all files, regardless of whether rclone deleted them.  It should only remove already deleted files.

> If the latter, I'm not sure I'd be comfortable with that without a pretty clear confirmation or --yes-really kind of option.

Lots of rclone commands can cause data loss if used incorrectly.  The `--dry-run` option is for those cases!

**Comment by timwhite** [comment]
Moving comments from #1489 to here:
It would be great to support Google Drive "Cleanup", or at least the ability to empty the Trash. Both V2 and V3 of the API support it https://developers.google.com/drive/v3/reference/files/emptyTrash

**Comment by juanluisbaptiste** [comment]
Any ETA on google drive ?

**Comment by ishuah** [comment]
@ncw I've been looking into cleanup for amazonclouddrive, box, dropbox and onedrive.

**amazonclouddrive**: There doesn't seem to be any documentation on permanently deleting trashed items with the Amazon Cloud Drive API. [Docs](https://developer.amazon.com/public/apis/experience/cloud-drive/content/restful-api-getting-started)

**box**: The Box API provides an endpoint for [listing trashed items](https://developer.box.com/reference#get-the-items-in-the-trash) and [permanently deleting trashed items](https://developer.box.com/reference#permanently-delete-a-trashed-file). However, there's no endpoint for permanently deleting trashed items and the Box API does not support batch API calls. Cleanup is not feasible since it involves listing all trashed items and making a delete request for each item. [Docs](https://developer.box.com/reference)

**dropbox**: There doesn't seem to be any documentation on permanently deleting trashed items with the Dropbox API. From my understanding, it is not yet supported. [Docs](https://www.dropbox.com/developers)

**onedrive**: Same as dropbox and amazonclouddrive, the OneDrive API does not expose a way to permanently delete trashed items. [Docs](https://dev.onedrive.com/README.htm)

**Comment by ncw** [comment]
@ishuah - thanks for working on this ticket and the informative info above.

I make this ticket all done now - do you agree?

**Comment by ishuah** [comment]
@ncw I agree, this ticket is done.

**Comment by ncw** [comment]
Excellent - thank you very much @ishuah

**Comment by juanluisbaptiste** [comment]
I'm getting this error with google drive:
```
clone cleanup gdrive-backups-3:
2018/11/20 22:27:51 Attempt 1/3 failed with 0 errors and: Google drive root '' doesn't support cleanup
2018/11/20 22:27:51 Attempt 2/3 failed with 0 errors and: Google drive root '' doesn't support cleanup
2018/11/20 22:27:51 Attempt 3/3 failed with 0 errors and: Google drive root '' doesn't support cleanup
2018/11/20 22:27:51 Failed to cleanup: Google drive root '' doesn't support cleanup
```
Any ideas ?

**Comment by hexxxx** [comment]
rclone cleanup remote:path not working for a google drive remote. Command returns without errors, but running rclone about remote: still shows terabytes in the trash. Any thoughts?

**Comment by ncw** [comment]
> rclone cleanup remote:path not working for a google drive remote. Command returns without errors, but running rclone about remote: still shows terabytes in the trash. Any thoughts?

I think it can take some time for the cleanup to take effect.

**Comment by hexxxx** [comment]
> > rclone cleanup remote:path not working for a google drive remote. Command returns without errors, but running rclone about remote: still shows terabytes in the trash. Any thoughts?
> 
> I think it can take some time for the cleanup to take effect.

Well, you may be right. It's gone down about 50GB in the past 6 hours. Maybe it'll just take a while to empty. Thanks!
