### ISSUE TITLE
large file upload doesn't work

### ISSUE THREAD

**Issue by hajes** [ncw/rclone#587]
rclone v1.3-1.32

Mac OS X 10.11.5

B2

rclone copy -vuc

[log.txt.zip](https://github.com/ncw/rclone/files/367224/log.txt.zip)

===============================

sometimes it shows funny speed numbers

there seems to be no apparent error. I see upload speed 1.2MB/s but it takes ages.

from screenshots...you can see 0kB/s then 15MBs (my official shared upload speed is 10Mbps/1.2MBs but sometimes goes to 2MBs). With such a speed, it would be already done in few hours.

Size of folder is 77GB...that's 1-2days max...it runs since last weekend and it is not done

![screenshot 2016-07-16 09 57 11](https://cloud.githubusercontent.com/assets/18664079/16894385/1c1b39d4-4b55-11e6-9505-485bf7b6b4f7.png)

![screenshot 2016-07-16 12 56 48](https://cloud.githubusercontent.com/assets/18664079/16894386/1c69376a-4b55-11e6-8d7a-34556ba01bd9.png)

![screenshot 2016-07-16 13 00 41](https://cloud.githubusercontent.com/assets/18664079/16894414/c339c050-4b55-11e6-935d-5bd710cee00f.png)

**Comment by hajes** [comment]
follow up of issue https://github.com/ncw/rclone/issues/456

**Comment by ncw** [comment]
If you look at the `Transferred:` line in your screenshots, you can see it is quite consistently at about 1 MByte/s which is the limit of your connection.

I can see why the transfer speeds for the individual files look odd though.  For B2 we buffer 96 MByte chunks into memory and send them, retrying if necessary.  This means that we read the file very quickly (hence the very high transfer speeds at the start) and by the end of the file we've read everything so the transfer speed indicator drops to 0.

This display problem we've noticed before but I can't find an issue for it.

If you look at the log you sent for the file `_Mondsee_cloudlapse/MVI_6037.MOV` you can see it sends a 96MB chunk about every 6 minutes from 10:34 to 12:54 which is a transfer rate of about 2.4 MBit/s.  this is almost exactly 1/4 of your 10 Mbit/s upload which is what I'd expect as rclone uploads 4 files at once by default.

What is wasting bandwidth is when rclone has to cancel an upload - there were two of these in the log you sent me

```
2016/07/16 10:49:27 (2016-06-13)_Mondsee_storm/MVI_0142.MP4: Cancelling large file upload due to error: Error reading uploaded data: Read timed out (400 bad_request)
```

And 

```
2016/07/16 11:39:11 (2016-07-05)_Mondsee_cloudlapse/MVI_6036.MOV: Cancelling large file upload due to error: Post https://pod-000-1029-08.backblaze.com/b2api/v1/b2_upload_part/4_z2c4731fb0384db29583e081c_f201f4c3a5ded21cd_d20160716_m083443_c001_v0001029_t0018/0007: dial tcp: lookup pod-000-1029-08.backblaze.com on 192.168.1.1:53: no such host
```

The first looks like some kind of internal backblaze error, or maybe rclone didn't supply the data quick enough due to network congestion. A 400 error indicates the request was incorrect somehow and you don't want to retry these.

The second looks like a local problem on your network - your router `192.168.1.1:53` failed to look up the name  `pod-000-1029-08.backblaze.com`.  This might be due to network congestion also.

You might find if you limit the speed to slightly slower than your connection it works better - it might help with those errors. You could try `--bwlimit 900k`

I've realised this is the same issue as #553

**Comment by hajes** [comment]
it doesn't matter to me how it works.

I create and need backup ;-)

It worked and now it doesn't work despite I didn't changed anything. I wonder why and what can I do on my side???

**Comment by hajes** [comment]
B2 error, rclone error...who knows?


2016/07/16 12:54:30 (2016-07-12)_Mondsee_storm/MVI_6048.MOV: Sending chunk 25 length 1429902
2016/07/16 12:54:32 B2 bucket eHajes path _ARCHIV/Video Projects/: Setting sleep to 1s after error: c001_v0001029_t0018 is too busy (503 service_unavailable)
2016/07/16 12:54:32 (2016-07-12)_Mondsee_storm/MVI_6048.MOV: Clearing part upload URL because of error: c001_v0001029_t0018 is too busy (503 service_unavailable)
2016/07/16 12:54:32 pacer: Rate limited, increasing sleep to 1s
2016/07/16 12:54:32 pacer: low level retry 1/10 (error c001_v0001029_t0018 is too busy (503 service_unavailable))
2016/07/16 12:54:32 (2016-07-12)_Mondsee_storm/MVI_6048.MOV: Sending chunk 25 length 1429902
2016/07/16 12:54:44 pacer: Reducing sleep to 500ms
2016/07/16 12:54:44 (2016-07-12)_Mondsee_storm/MVI_6048.MOV: Done sending chunk 25
2016/07/16 12:54:44 (2016-07-12)_Mondsee_storm/MVI_6048.MOV: Finishing large file upload
2016/07/16 12:54:44 (2016-07-05)_Mondsee_cloudlapse/MVI_6038.MOV: Sending chunk 18 length 100663296
2016/07/16 12:54:49 pacer: Reducing sleep to 250ms
2016/07/16 12:54:49 (2016-07-12)_Mondsee_storm/MVI_6048.MOV: Copied (new)
2016/07/16 12:54:49 (2016-06-13)_Mondsee_storm/MVI_0146.MP4: Destination mod time is within 1s of source and sizes identical, skipping
2016/07/16 12:55:13 pacer: Reducing sleep to 125ms
2016/07/16 12:55:13 (2016-07-05)_Mondsee_cloudlapse/MVI_6040.MOV: Starting upload of large file in 43 chunks (id "4_z2c4731fb0384db29583e081c_f200a97ced313a99a_d20160716_m105512_c001_v0001001_t0020")

**Comment by ncw** [comment]
That looks all to be working fine - it shows rclone getting an error and retrying.

Why don't you try my `--bwlimit 900k` suggestion?

**Comment by hajes** [comment]
how does bandwidth limit help?

I've got 0kBs upload ;-)

it looks like B2 error. They force to use b2-large-file-upload API call I guess

If you have thousand people with thousand chunks/open connections...it is deadly for server

**Comment by ncw** [comment]
You have lots of upload - I explained above that the 0kbs reading isn't real. Limiting the bandwidth will help with the errors you are getting.

**Comment by hajes** [comment]
first error I made is I forgot / after directory so all was uploaded to root dir of B2

what I noticed is that rclone created 70GB of data from 13GB folder - creating at least five versions of one file. Basically, it repeatedly uploaded files and created new versions or B2 misunderstood commands and created versions...who knows

**Comment by isaiah36** [comment]
I am also getting a failure of upload to Amazon cloud.

> Received error: HTTP code 400: "400 Bad Request", reponse body: {"message":"Cannot complete upload"}

Rclone retries the transfer and fails again.  The failure occurs at either 39% or 40% mark of a 10.5 Gb file.  It has completed a 22 Gb file recently, so I don't believe it is a size limit.

**Comment by ncw** [comment]
@isaiah36 That is probably an amazon problem, but I can't see anyone talking about it on the developers forum.  If it continues to happen can you make a new ticket with a log using the `-v` flag of it happening please?

**Comment by isaiah36** [comment]
Sure thing.  I upgraded to v1.32 and I am now attempting the transfer with the --bwlimit 900k flag.  If it fails again I will start a new thread.

**Comment by isaiah36** [comment]
I managed to get the upload done using the Amazon desktop app on a Windows 7 x64 system.  It failed the first time trying to read the file from the network location.  I had to copy and paste it into the local drive, and then it uploaded successfully.

**Comment by isaiah36** [comment]
I have a clue.  There were 2 consecutive dots in the file name!  I only just noticed it.  I still don't understand why it would reach 39-40% done every time before tripping up.

**Comment by ncw** [comment]
The upload statistics are now fixed for b2 (along with quite a few other things in) v1.33.
