### ISSUE TITLE
Uploading duplicate of files as if they were different case

### ISSUE THREAD

**Issue by TheTrueTom** [ncw/rclone#608]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
1.32

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
OS X Le Capitan 10.11.6

> Which cloud storage system are you using? (eg Google Drive)
HubiC

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync ~/Pictures hubic:RClone-Tom_Pictures

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
2016/08/08 07:30:39 Photothèque.photoslibrary/resources/modelresources/120/112/xptvKjhxTxaOMCtxIlClpw/IMG_0257.jpg: Warning: File found with same name but different case on Swift container RClone-Tom_Pictures

When starting my backup after upgrading to the latest version of RClone (not sure if this was right after or not), I started getting thousands of message like "File found with same name but different case".

Facts: 
- none of those files/folder changed between backups
- the case seem to be the same or at least I can't see a difference
- looking at the remote folder with Swift Explorer now reveals thousands of duplicates
- looking in Swift Explorer at two 'duplicate' folders, only the modification date differs

Possible:
- Only seems to happen on file located at path that include an accented character also I'm not 100% positive about that

I'm not sure if this comes from here or from hubic, I haven't had any news on their side. I will update if I do. In the meantime I'd be happy to provide supplementary information as needed.

Thanks for the hard work!

**Comment by ncw** [comment]
I suspect this has been caused by #451 and 7c01bbddf8a7ccde05554633b0165f3711d9fdc4.

This means that it will only affect accented characters as you suspect.

What you will find is that when you look very carefully at the filenames they are different but they appear the same.  Fixing that was the point of #451.  How they got there is to do with OS X file systems - for some reason they store unnormalised UTF-8 in them - rclone used to upload them without normalizing them (which was bad).

So I think what rclone did was correct, however that leaves you with a whole pile of duplicate files.

I would have hoped that if you let the sync continue to the end it will delete the unnormalized file names - does it?

If it doesn't then I can extend `rclone dedupe` to do it quite easily - I don't think it will do the right thing at the moment though.

**Comment by TheTrueTom** [comment]
Thank you for your answer !

I don't know yet if it deletes files in the end as the backup I have started is quite large (a few hundreds of GB) and probably won't be finished for a while. 

I'll update as soon as it is finished.

**Comment by ncw** [comment]
Did it finish OK?

**Comment by TheTrueTom** [comment]
I'm still away for the moment so it hasn't been able to run for the moment. I will know more in early september and will report as soon as I know.

**Comment by TheTrueTom** [comment]
The backup was finally able to finish. 

Everything was removed as expected except for the top-level folders.
I have two folders with accented characters in their name, both are empty but still there.

No errors were signaled by rclone. I restarted the sync, everything went without errors but the empty folders are still here.

**Comment by ncw** [comment]
Great glad it finished.  rclone doesn't remove empty folders yet (see #100) so that is a success I think!
