### ISSUE TITLE
Have to manually refresh ACD token

### ISSUE THREAD

**Issue by ghost** [ncw/rclone#650]
> What is your rclone version (eg output from `rclone -V`)
> `rclone v1.33`
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> `Ubuntu 16.04 LTS 64 bit`
> 
> Which cloud storage system are you using? (eg Google Drive)
> `Amazon Cloud Drive`
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> `rclone copy acd_us:/ acd_de:/ --stats=2s --transfers=15`

---

I'm trying to migrate my data from ACD US to ACD DE, but after a while (an hour, three hours, etc) the following shows up:

`2016/08/26 13:39:09 Failed to create file system for "acd_de:/": failed to get endpoints: Get https://drive.amazonaws.com/drive/v1/account/endpoint: oauth2: cannot fetch token: 400 Bad Request
Response: {"error_description":"Not authorized for requested operation","error":"unauthorized_client"}`

And the log is filled with this (file names obfuscated):

`2016/08/26 14:44:53 foldername/foldername/filename: Failed to copy: Get https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=parents%3A%2PMQTEKSnp_DQ%22+AND+name%3A%22pxDAFIbH%22: oauth2: cannot fetch token: 400 Bad Request
Response: {"error_description":"Not authorized for requested operation","error":"unauthorized_client"}`

Looks like rclone doesn't grab a new token when it expires, and I have to do it manually for it to work for about an hour or so.

**Comment by ncw** [comment]
Rclone definitely grabs new tokens. Check the time on your computer is set correctly - that can throw it off.

**Comment by annetson** [comment]
The time on the server was set correctly.

The solution was apparently to remove the client_id and client_secret entries on the acd_us remote (my security profile is whitelisted). It's now been going for 21 hours without any issues.

While I'm glad I got it working, because I have so much data to migrate, I'm also wondering if this is possibly something you want me to test further.. Would it be of use to you if I put the client_id/client_secret entries back in and see if this is reproducible?

**Comment by ncw** [comment]
Glad you've found the problem. You shouldn't need to set client_id and client_secret in normal operation unless you've registered your own Amazon Drive app with Amazon. If you leave them unset rclone will substitute it's own. 

Have you got your own client_id and client_secret ? If not what did you put in? I'm amazed it worked at all if you didn't put a valid client_id  id in, though it would explain some bug reports.  Either way I'd like to get to the bottom of what is happening. 

Can you explain further what you mean by this

> when I refreshed the token manually (my ACD US security profile is whitelisted).

How did you manually refresh the token and what does it mean to have your security profile whitelisted - do you mean as part of the Amazon app registration process? It is a while since I did it for rclone and the details are hazy! 

Thanks 

Nick

**Comment by annetson** [comment]
> Have you got your own client_id and client_secret ?

I do, yes. I created a security profile in the Amazon developer console a while back, and applied to get whitelisted (before they got really difficult about it). Mainly because I'm also using acd_cli and it seemed like it might have less limits with a development account. Admittedly I'm mostly just flailing around most of the time with zero knowledge, but I figured since I have a Client ID and Client Secret I should put them into rclone.

>Can you explain further what you mean by this

>>when I refreshed the token manually (my ACD US security profile is whitelisted).

Sure! I ran `rclone config`, edited my ACD (US) remote and when I got to the `Already have a token - refresh?` part I said 'yes' and went through the procedure for a headless server.

> and what does it mean to have your security profile whitelisted - do you mean as part of the Amazon app registration process?

Yep, like I explained above :) In the Amazon Developer Console I went to _Apps & Services_, then _Security Profiles_ and created a Security Profile, as per the information [in this part of the acd_cli documentation](http://acd-cli.readthedocs.io/en/latest/authorization.html) (under _Advanced Users (Security Profile)_).

**Comment by ncw** [comment]
Ah OK I understand now - thanks for explaining!

> While I'm glad I got it working, because I have so much data to migrate, I'm also wondering if this is possibly something you want me to test further.. Would it be of use to you if I put the client_id/client_secret entries back in and see if this is reliably reproducible?

As far as I know you are the first person to try this.  I think it should work, but it obviously doesn't so it would be interesting to get to the bottom of it :-)
