### ISSUE TITLE
Remove control characters from file names found in OS X

### ISSUE THREAD

**Issue by marrie** [ncw/rclone#689]
I was instructed to send you guys a bug report by the backblaze b2 team.

I do a sync  with rclone to b2 and get some api errors, and some IO errors as if backblaze pods cannot be read. I can't quite reproduce the issue often as after about 10 retries it works. Here is my log attached. I know this is not much help but i'm using the current version of rclone on mac os el capitan  64 bit.

[outputbooks.log.zip](https://github.com/ncw/rclone/files/457711/outputbooks.log.zip)

**Comment by ncw** [comment]
Your files seem to have a carriage return on the end of them which is really odd!

All the failing files are called `Icon^M`.  Here is an explanation of what those are: http://superuser.com/questions/298785/icon-file-on-os-x-desktop/298798

Backblaze (nor any other cloud provider) don't let you store a file with a control character in which is why they don't upload and why so many errors.

I think if it wasn't for those files then your sync would be working quite well.  There are always a few errors with cloud storage systems, but rclone will retry the sync and get there in the end.

So I think what I should do is substitute control characters (0x00-0x1F and 0x7F) in local.go `cleanRemote` (perhaps to %XX) this will make the sync complete properly.  Note that it won't back up the contents of the Icon files though as these are stored in the resource fork and rclone only copies the data fork.

I'll post a beta for you to try in due course here.

**Comment by marrie** [comment]
Thanks. I know I didn't put any ctrl chars in my files. How odd. The icon files I'm not worried about, I don't think it will hurt my books and crud (tech term)  if the icon files are not there. 

Thanks.

**Comment by ncw** [comment]
...in the mean time you could add `--exclude 'Icon?'` to your command line to not sync those files.

**Comment by ncw** [comment]
I've fixed that in: http://beta.rclone.org/v1.33-71-ga02edb9/ (uploaded in 15 mins)

I decided to ignore the files with control characters in which seems perfect for this use case.

**Comment by marrie** [comment]
Thanks. I and hopefully others will test it now. The files with control chars like the ones that are braking won't hurt anything if they are gone from a back up will they? I'm thinking no.

I'll post results here.

**Comment by marrie** [comment]
Sorry to comment so quickly. I'm getting a file not found error in safari when I try and dl. My wget yields this.

--2016-10-18 09:41:13--  http://beta.rclone.org/v1.33-71-ga02edb9/
Resolving beta.rclone.org... 77.73.5.145
Connecting to beta.rclone.org|77.73.5.145|:80... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2016-10-18 09:41:13 ERROR 404: NOT FOUND.


Thanks.

**Comment by ncw** [comment]
It has appeared now. Sometimes Travis takes a bit longer her than 15 minutes.

**Comment by ncw** [comment]
The files with control chars weren't being backed up before. Those Icon files are the only examples I've found.
