### ISSUE TITLE
i/o error on Amazon Cloud Drive

### ISSUE THREAD

**Issue by seppi91** [ncw/rclone#734]
Hi I'm currently trying to migrate my Amazon US Cloud Drive Account to my German ACD Account, in order to avoid abusing their TOS. I came across rclone which seems the perfect application to get this migration done. 
I've mounted my acd_US drive via acd_cli fuse on my filesystem (/mnt/.acd-remote-enc/). But when I try to upload one of my folders to amazon_Germany via rclone I'm getting timeouts all the time. Some files get uploaded succesfully; but most of the time they're not.
Rclone also doesn't respect the default retry count of 3 and uses all of my available traffic quota, while trying to upload the same file all the time.

Is there anything wrong with my setup? What's the cause of these i/o errors?

---

> What is your rclone version (eg output from `rclone -V`)
> rclone v1.33-19-g83ba597β
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> Ubuntu 14.04.5 LTS
> 
> Which cloud storage system are you using? (eg Google Drive)
> Amazon Cloud Drive
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> starting with parameters ["rclone" "copy" "--transfers" "1" "/mnt/.acd-remote-enc/2Zz6FYsKOAhq,fy2oF0X-HRy/ushfoOGcP-HqQA8k4O1hO35CqlzBxxlYNbtamE,Hk7rXBrI,YljoShxs00YrMltZ5pA/" "acd:/2Zz6FYsKOAhq,fy2oF0X-HRy/ushfoOGcP-HqQA8k4O1hO35CqlzBxxlYNbtamE,Hk7rXBrI,YljoShxs00YrMltZ5pA/" "--ignore-existing" "--acd-upload-wait-time" "50m0s" "--log-file" "/home/seppi/rclone.log" "-v"]
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
> http://pastebin.com/BRPMZk9r

**Comment by pkIAIK** [comment]
Hi, 

I experienced the exact same issue with east-europe ACD accounts.
The default timeout of 5min is just to low. Since it is just a "convenience" timeout, I changed mine to 24h.

I noticed that during the entire upload the i/o channel did not respond. Maybe an european thing.
So just use the `--timeout` option with a value equal to the maximum upload time of your files. I set mine to 24h, since I have some huge files. Not a single connection abort since. (still uploading after 341GB with a single rclone launch :) )

Additionally if your provider keeps disconnecting your connection every 8 hours (like mine does), you probably also wan't to change `--contimeout` to 2-3 minutes.

Works like a charm for me now. :)

**Comment by felixbuenemann** [comment]
@seppi91 How did you manage to create a German cloud drive account? When I tried to sign up using my German AWS account, it accepted the login, then redirected me to the US login form and I entered the same credentials from my US AWS account and now my drive seems to live in the US.

Btw. is there a way to limit the number of threads? I'm uploading with a 5 Mbps uplink and 4 threads is total overkill for that…

**Comment by 15siegela** [comment]
@felixbuenemann
I'm on the same exact situation, I believe my data also lives in ACD servers in the US, but I'm living in Germany. Were you able to determine if your data was is actually in the US or Germany? I'm not sure how I would figure that out.

**Comment by felixbuenemann** [comment]
@15siegela I did a traceroute to the ec2 servers it is uploading to and they are in the AWS us-east-1 region. I also tried changing the email address on my amazon.de account, but it also changed it for logging into amazon.com, so there only seems to be a single account. It might be because I create the cloud drive a long time ago (I noticed there was a video from a few years ago inside it), so that might be the reason…

**Comment by felixbuenemann** [comment]
@ncw Btw. why does rclone skip the files on an i/o timeout instead of simply retrying the last chunk?

**Comment by zeshanb** [comment]
Hi,

Maybe best to have --checkers option also be 1. Also --bwlimit option with
11M may be smoother.

Docs mention a --retries option for Amazon storage users..

Regards,
Zeshan

**Comment by seppi91** [comment]
@felixbuenemann Ive used another amazon account. With a different E-Mail adress, so there is no mapping between my US amazon cloud and the german counterpart

**Comment by ncw** [comment]
Are you happy with the transfer now?  Do you still need this issue open?
