### ISSUE TITLE
Rclone sync command and deletion

### ISSUE THREAD

**Issue by waqark3389** [ncw/rclone#735]
> What is your rclone version (eg output from `rclone -V`) - **1.33**
> Which OS you are using and how many bits (eg Windows 7, 64 bit) **Linux 64 bit**
> Which cloud storage system are you using? (eg Google Drive) **AWS S3**
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`) **rclone sync /home/dir RemoteCrypt:path**

Firstly I want to say thank you so much for this brilliant piece of software. Well done. 

I tried to search through the current issues and couldnt find any info for my question so apologies if I missed it. 
I am trying to sync a local dir to S3 bucket with crypt. All that is working fine but it doesnt seem to "sync" as I thought it would. It ignores files already inside my S3 bucket path. Should it not delete these if they dont exist locally? 

E.g. my local structure is : 
/home/dir/file1

Remote:
bucket/dir/file1.bin (renames it as .bin for crypt I believe)
bucket/dir/file2

It doesnt delete file2 which is only in remote. 

Is there any way to achieve a complete sync, similar to rsync --delete param? 

Thanks!

**Comment by ncw** [comment]
I see what you mean.
 * You have an existing bucket with some existing files in.
 * You've setup a crypt remote to point to that bucket.
 * rclone sync isn't deleting the existing files

The problem is that the crypt filesystem doesn't see files that aren't crypted - they don't exist as far as it is concerned!

You'll see if you do `rclone ls RemoteCrypt:path` you won't see any of the existing files.

That explains why `rclone sync` doesn't delete them as for the `RemoteCrypt:` they don't exist.

As for how you fix this....

Assuming your underlying remote for S3 is called `remote:` and you have file name encryption off

  rclone ls --exclude "*.bin" remote:bucket

This should show you all the non encrypted files - check them carefully then do

  rclone delete --exclude "*.bin" remote:bucket

Of if you just want to move them out the way

  rclone move --exclude "*.bin" remote:bucket remote:newbucket
