### ISSUE TITLE
 User rate limit exceeded, userRateLimitExceeded

### ISSUE THREAD

**Issue by alonebfg** [ncw/rclone#76]
For some reason this has started happening to me  Received error: Upload failed - retry: googleapi: Error 403: User rate limit exceeded, userRateLimitExceeded - retrying 2/10
I have set my own key and secret so  dont use all your call as i work in schools and have found this to be real good. at time of running quota 
Free quota 10,000,000 requests/day 
Remaining 9,998,919 requests/day
99.99% of total
Per-user limit 250 requests/second/user

**Comment by dbareiro** [comment]
Hi, alonebfg.

This has to do with the rate limitation for file transfer that Google handles. Please check nick's comments on the issue #66.

Best regards,
Daniel

**Comment by ncw** [comment]
I've recently added some docs on this issue. Check the limitations section in http://rclone.org/drive/

You should find that rclone retries the copy and it works fine. If you get some errors at the end of the sync then just retry the rclone command.

**Comment by chug84** [comment]
Hello Nick. First I want to say I love rclone, been using it for a couple of weeks. However I seem to have encountered this problem here on my end also. My folder I'm trying to backup is approx 2.3TB in size. Yesterday I tried backing it up and noticed I was getting 403 errors after about 900GB had been backed up. I followed your guide linked above with my own client ID and it worked for a bit, allowing about another 700GB of data to be uploaded. 

Google Drive API     
Queries per day | Global |   | 5,241 / 1,000,000,000
Queries per 100 seconds | Global |   | — / 10,000
Queries per 100 seconds per user | Global |   | — / 1,000

![upload](https://user-images.githubusercontent.com/30219773/29244136-cf83a926-7f7e-11e7-80be-d15668406ea6.png)

Is there anything I could be doing wrong on my end?

**Comment by sjurtf** [comment]
There are open issues on this, and it is also discussed in the rclone forums. 
It is caused by a new limitation added by Google which is not yet documented, nor recognised by the Google support team.

**Comment by rlittman16** [comment]
Hello, I was getting this error, and then went and sent my client_id through google API as shown above. I still get this error when I try and upload data.

2018/10/12 20:53:12 ERROR : Attempt 2/3 failed with 1 errors and: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded
2018/10/12 20:53:53 ERROR : test.txt: Failed to copy: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded
2018/10/12 20:53:53 ERROR : Attempt 3/3 failed with 1 errors and: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded
2018/10/12 20:53:53 Failed to copy: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded

Thanks in advanced

**Comment by ncw** [comment]
> Hello, I was getting this error, and then went and sent my client_id through google API as shown above. I still get this error when I try and upload data.

The best thing to do is ask on the [the rclone forum](https://forum.rclone.org/) where there are lots of heavy data users who can help...  However it seems likely you've got some kind of ban which will lift in 24 hours or so.
