### ISSUE TITLE
acd: acd-templink-threshold option ignored

### ISSUE THREAD

**Issue by felixbuenemann** [ncw/rclone#770]
The `--acd-templink-threshold` option is ignored during `rclone copy remote:path /local/path`.

If I copy a file > 9GB I can see in `iftop` that the file is downloaded directly from s3, but if I try to force using the templink for smaller files, eg. `--acd-templink-threshold 0|1|100M|1G` the value is always ignored and the file is transferred via ec2 instead. (I tested with a 7 GB file.)

> What is your rclone version (eg output from `rclone -V`)

rclone v1.33-41-g90aee8c-fix-timeoutβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04 amd64

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy remote:somebigfile /tmp --acd-templink-threshold 1

**Comment by ncw** [comment]
After a bit of investigation I can see that the rclone code is working as expected, what is unexpected is that the templinks look different for big and small files.

For a 1GB file I get a templink like this

    https://content-eu.drive.amazonaws.com/cdproxy/templink/IuJ...

Wheras for a 10GB file I get a templink like this

    https://cd-eu-prod-content.s3-eu-west-1.amazonaws.com/DJE...

Interestingly the 1GB file downloaded at 25 MBytes/s wheras the 10 GB file downloaded at 44 MByte/s which is why I guess you were experimenting with that value.

PS thanks for pointing out `iftop` to me - not seen that tool before!

**Comment by felixbuenemann** [comment]
Yes, I'm using an S3 VPC Endpoint which allows very fast access to S3 when in the same region.

Seems like this is not an rclone problem, so I'm closing this issue.
