### ISSUE TITLE
Manual trigger of cache flush

### ISSUE THREAD

**Issue by talisto** [ncw/rclone#803]
The updates to fix issue #680 are a huge help to refresh the cache without having to unmount/remount, so thanks for that!

However, it would be very useful to also be able to manually trigger a refresh of the cache in instances where we already know the cache is stale.

Issue #771 discusses having an rclone process you can send commands to; perhaps a refresh/flush command could be implemented if/when that functionality is added?

**Comment by ncw** [comment]
rclone could listen on a signal to do this quite easily so you would `killall -SIGHUP rclone` maybe.

**Comment by talisto** [comment]
that sounds good!

**Comment by calisro** [comment]
Yes! I currently have to set my interval very low (like 1 minute) and add a sleep command to my batch processing of a 1minute to allow the cache to expire to continue my batch function.  Since I know my data, I could then increase this to 24 hours or NEVER expire the cache and issue a SIGHUP when I know the data has changed.  Pretty Please! :)

**Comment by seuffert** [comment]
any update on this? It would be really helpful to be able to signal rclone-mount to update the dir cache

**Comment by ncw** [comment]
I've put it on the list for 1.37

**Comment by chmercesmoreira** [comment]
I have another suggestion:
Why not activate the function to refresh the cache every time rclone makes a change on the remote?
For example, these rclone functions could trigger a function to refresh the cache because they are all "write" actions:
rclone copy - Copy files from source to dest, skipping already copied
rclone move - Move files from source to dest.
rclone delete - Remove the contents of path.
rclone purge - Remove the path and all of its contents.
rclone mkdir - Make the path if it doesn’t already exist.
rclone rmdir - Remove the path.
rclone rmdirs - Remove any empty directoryies under the path.
rclone cleanup - Clean up the remote if possible
rclone dedupe - Interactively find duplicate files delete/rename them.
rclone copyto - Copy files from source to dest, skipping already copied
rclone moveto - Move file or directory from source to dest.

**Comment by ncw** [comment]
@chmercesmoreira nice idea, but not straight forward to implement as it is two different instance of rclone running so one would have to find the other which is non-trivial...

**Comment by breunigs** [comment]
I took a stab at implementing a more sophisticated version of this – where you can invalidate specific paths instead of the "all or nothing" approach suggested here. That would be a perquisite to hook into the GDrive changes API, for instance.

I am not sure how to solve this in a memory leak free way, though. [bazil/fuse/fs](https://github.com/bazil/fuse/blob/master/fs/serve.go) holds the reference to all nodes (and thus rclone's `Dir`s) in a private map `nodeRefs`. Since I cannot access that map, I cannot simply iterate over its keys until I find a node with a matching path and discard that `Dir`'s `items`.

Idea 1: Create a lookup `map[string]*Dir`. That might keep `Dir`s around that get removed from the `nodeRefs`, e.g. by `dropNode`. Seems like a very fragile approach to catch all cases to ensure it also gets dropped from rclone's lookup.

Idea 2: Collect list of invalidated directories and remove it again when the matching directory is re-read. Of course, old entries from that list can be discarded once they are older than `dirCacheTime`. Still, if the idea is to set the dir caching time to essentially ∞, invalidation requests for non-existing dirs would hang around forever.

Idea 3: Idea 2, but immediately re-read the directory. This would not be flushing, but rather refreshing, but at least it should not leak. 

Both 2+3 suffer from not working recursively, I think. E.g. if I have `dir1/dir2/file` and invalidate `dir1`, only `dir1` contents will be re-read. `dir2` will not be affected. If that is desired/needed, then it would have to recurse once it is invalidated. Combined with `Dir.rename`, which sets `d.items = nil`, this seems to have a high potential for hard to debug race conditions.

Idea 4: fork the fuse library and make `nodeRefs` accessible, so that we can iterate. 

None of the ideas sound really appealing to me, though. If someone has some insight (or spies a mistake in my reasoning), I'd be happy to hear it.

**Comment by ncw** [comment]
@breunigs it seems to me the best approach might be to send a PR to bazil/fuse/fs with the extra functionality rclone needs.  Perhaps a flush this path method and return nodes flushed?

**Comment by calisro** [comment]
How can I test this?  Is there a small doc/comment on how to use it?  I'm happy to test it.

**Comment by calisro** [comment]
btw, you have a mis-spelling  "+Assuming only one **rlcone** instance is running"

**Comment by ncw** [comment]
Have fixed the typo thanks

**Comment by ajkis** [comment]
Would sending `kill -SIGHUP $(pidof rclone)` to all pids do any thing to rclone sync/copy/movies

**Comment by ajkis** [comment]
Added to my manual refresh of plex folders clearing cache:
`kill -SIGHUP $(pgrep -f "rclone mount acdcrypt:")`

p.s. I changed to mount script so it starts with `rclone mount acdcrypt:` and flags after

**Comment by calisro** [comment]
Reading above, it looks like we can do partial flushes of specific paths?  How would we invoke that or is that part not complete?
