### ISSUE TITLE
Slow scanning files in Subsonic/Madsonic using mounted ACD

### ISSUE THREAD

**Issue by lurkr** [ncw/rclone#805]
I've tested this on 64bit Ubuntu using both rclone 1.33 and v1.33-69-gd8d1102β. I'm using ACD as cloud storage. Playing files once they are added works OK (seems like it might be a little slow tho), but adding files takes ages.

I'm not sure how Subsonic or Madsonic scans the files when they are being added, but at times it's getting stuck on a file for up to a minute, then it does 10 files in a second.

Let me know what I should do to diagnose this further, I'd love to be able to keep my Subsonic library on ACD.

**Comment by talisto** [comment]
I've been playing around with Subsonic with an ACD mount as well, both with rclone and acdcli, and I've pretty much given up on the idea.. the slowness isn't limited to rclone.

Subsonic reads every directory one-by-one before it starts the scanning process.  It also seems to open and read the files multiple times when scanning, and it doesn't appear to be using its own local thumbnail/artwork cache afterwards, so when a list of tracks is viewed in Subsonic it goes back to the original files to look for cover art for each track.  Likewise when a track is played, it seems to be seeking through the entire file to read the metadata/artwork before playing the file.  This all hits Amazon's rate-limiting pretty quickly.

You can get a better idea of what it's doing by using verbose mode (`-v`) with your rclone mount.  I can't figure out exactly why it's re-reading the metadata so often, but I've concluded that it's an issue that needs to be fixed with Subsonic, and not rclone.

**Comment by lurkr** [comment]
Ah, that's good to know, even tho it sucks. Thanks for the information!

**Comment by Jack187n2** [comment]
I've made the same experience with my ACD (mounted through acd_cli)... at the moment to slow to host my files there, because adding takes to long.
Maybe some developer can give a hint or have a look... Thanks a lot!

**Comment by ncw** [comment]
I'm going to close this issue now as we've got to the bottom of it!
