### ISSUE TITLE
drive: authError when uploading big files

### ISSUE THREAD

**Issue by mkipness** [ncw/rclone#81]
Hello,

I noticed #33 has been closed with a fix posted in version 1.12. However I'm using 1.16 and getting the same error on large files as of today:

2015/06/16 03:52:27 TRANSFERS/C$/Users/*****/Documents/Outlook Files/Archive.pst: Failed to copy: googleapi: Error 401: Invalid Credentials, authError

The file in question is 15GB in size.

Any other suggestions to resolve this would be appreciated!

Thanks,
Max

**Comment by ncw** [comment]
Can you re-run with `-v` and send me the log please?  You can use the `--log-file` option to save the log to a file, eg `rclone -v --log-file=C:\rclone.log copy/sync ...`

Thanks

Nick

**Comment by deajan** [comment]
This can happen if the API token expires (when the file takes too much time to upload).
See https://code.google.com/p/google-api-python-client/issues/detail?id=231

**Comment by ncw** [comment]
@deajan Thanks very much for that link. According to later on in that thread it looks like the specific bug referred to was fixed by google in December 2014 though...

This might also be to do with the library not renewing the token quick enough which should be fixed in #102 when it is released (shortly with v1.20)

**Comment by ncw** [comment]
I'm going to assume that the fixes in #102 fixed this since no-one has reported this recently.
