### ISSUE TITLE
Sync Local Disks Not Working

### ISSUE THREAD

**Issue by eygraber** [ncw/rclone#895]
> What is your rclone version (eg output from `rclone -V`) 1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit) Windows 10 64 bit

> Which cloud storage system are you using? (eg Google Drive) none

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`) rclone f:\ nounc g:\

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`) the command just waits for more input

**Comment by ncw** [comment]
There doesn't seem to be a verb in the command line you posted, eg `copy`?

So you probably want `rclone copy f:\path\subpath\ g:\path\subpath\`

Is that the problem?  If not then cut and past the actual command an error message please.

Thanks

**Comment by eygraber** [comment]
@ncw woops that was a typo. It's rclone sync  f:\ nounc g:\

**Comment by ncw** [comment]
@eygraber Can you cut and paste (or screenshot) the actual command and the output please with the `-v` flag - thanks!

**Comment by eygraber** [comment]
@ncw figured out the issue. On Windows you need to prepend `\\` to use other drives. So the command was `rclone sync \\f:\ \\g:\`.

**Comment by eygraber** [comment]
Actually scratch that. That just created a directory called `:h_` at the root of the drive I was on. What would the correct command be to copy or sync between 2 local drives?

**Comment by ncw** [comment]
This is mentioned in the docs: https://rclone.org/docs/#windows

The correct syntax should be:

rclone sync f:\ g:\

**Comment by DragonFury24** [comment]
I'm having the same issue where I can't sync 2 drives if I do rclone sync L:\ M:\ -v . However, if I make a Storage folder in M: and do rclone sync L:\ M:\Storage -v then it works. The first command gives the error Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect. Is there something wrong with my syntax?

**Comment by hotleadsingerguy** [comment]
ncw, that is not the issue. The issue is that in Windows 10 rclone doesn't seem to have the ability to mkdir into a base drive. I use rclone to backup my 2 main drives to external drives of the same type and if I don't put it all in a directory on the external it fails, because it can't create the directories. Example:

`rclone sync T:\ X:\ -v`

This fails, because if any of the directories on my T drive don't already exist on the X, it fails with the following error:

`Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.`

If I change the syntax to `rclone sync T:\ X:\Backup -v` it works perfectly fine.

**Comment by ncw** [comment]
@hotleadsingerguy I think that is #1754 which in turn depends on a bug in go being fixed
