### ISSUE TITLE
File found with same name but different case

### ISSUE THREAD

**Issue by nagualcode** [ncw/rclone#914]
When syncing rclone finds some "File found with same name but different case". 
How can I force rsync to delete those files qnd download from source, so I get clear of these msgs?

**Comment by ncw** [comment]
That is only a warning - where are you syncing to?

**Comment by fredericofs** [comment]
Syncing from dreamobjects ceph to local debian machine, sync with --delete.
So rclone in deletes the "sames files with different case" from local and download from source? I swear I could see the warnings again and again, until I manually deleted those files from local.
Will test again, thank you!

**Comment by putty182** [comment]
Hey @fredericofs, did you have any success forcing the destination files to be the same case?

I'd be in favour of a `--force-case` flag that moves or renames file names and paths on the destination side of the transfer, including creating intermediary paths in case of a folder rename.

Or maybe the `--delete-before` flag could be extended to delete the conflicting file names from the destination, and then transfer the source files with the new case?

**Comment by fredericofs** [comment]
So far this issue did not changed for me (using ceph). And I do agree with your suggestions.

**Comment by putty182** [comment]
Did some testing, turns out I had `rclone move`'d the same file but with a slightly different case over to a crypt remote (ie, case-sentitive).  There's nothing rclone can do in this scenario - I had to remove unwanted files manually.  The warning is just being polite!

The warning also appears when `rclone sync`'ing, but the files on the remote it warns about should be deleted shortly after the updated ones with the same case as the source are copied across successfully (ie, `--delete-during`).  The warning shouldn't appear on a second run.

If you're doing a sync to the remote that isn't case-sensitive however (ie: amazon drive) you might run into 403 CONFLICT errors,  since rclone can't copy over the file with the updated case.  `rclone sync --delete-before` handles this scenario.

**Comment by joeytwiddle** [comment]
I am getting a lot of these warnings while syncing to b2 backblaze.  When I do `rclone ls` to check, the case of the file listed on b2 matches that on local, and there is no other matching file with a different case.

(Occasionally I will see two files on the remote, as the warnings suggests I should. So it *can* happen, but a lot of the time there is no duplicate file!)

It's happening with various different files, often in groups, but I can't see any pattern of similarity between these files.

I have been performing a big sync, progressively, by running rclone sync and interrupting it part way through. The warnings seems to happen more at the beginning of the sync than in the middle. I have not reached the end of the sync yet, but one day I will!

**Comment by ncw** [comment]
@joeytwiddle can you paste some logs?

**Comment by joeytwiddle** [comment]
Ah I think there might be a simple explanation. In the cases where I cannot find the different-case duplicate, I can find same-case duplicates in other folders. So perhaps what rclone is really trying to tell me is that:

> There is a copy of the file on the bucket with exactly the same name, but at a different path

Or alternatively it might be trying to tell me:

> There is a copy of the file on the bucket with exactly the same name, but at a different path, and there are also files with that name but different content.

I mention the last scenario because so far the only cases I found of this involved multiple copies of the file, some with identical content and some not (all with the identical name but different paths). It is entirely possible that it might also happen when there are only identical copies, but I just haven't found that case yet in my corpus.

(version 1.35 here)

**Comment by ncw** [comment]
This issue is old now, and the case detection code has been through a major revision, so I'm going to close this issue - if you are still having problems, please test with [the latest beta](https://beta.rclone.org) and make a [new issue on github](https://github.com/ncw/rclone/issues/new).
