### ISSUE TITLE
Unable to access files in a Google Drive mount

### ISSUE THREAD

**Issue by jerblack** [ncw/rclone#947]
My Amazon account got locked today, so now I'm trying to use Google Drive instead.  I tried to to just swap rclone for acd_cli and keep encfs and my mount paths the same so Plex could see the files in the same place without rescanning. (I have my data mirrored across both services with the same paths). Plex is showing all of my media as unavailable though. After troubleshooting I found that I can't copy any files out of my rclone mount, even with enc_fs disabled (just copying the encrypted blob directly so rclone should just see a regular encrypted file). I am unable to `cp` or `rysnc -av` any files from my rclone mount that is pointed at Google Drive.

```
rclone v1.34-62-gec0916cβ 
Ubuntu Server 16.04
service Google Drive

```
This is my mount setup
```
~/acd_enc   # acd_cli mounted /backup originally, now using rclone to mount gdc:backup/ to this path
~/acd_dec   # encfs mounted a decrypted view of my files at ~/acd_enc/ to ~/acd_dec
```
This is what I see when I try to copy a file from the terminal
```
cp e58X5Lg2mjXyMtnjTs3BTwC4PXpA-SQbn5qOecUcu3tOOXc9xFrFlgSRjrDxk,0zQX7 ~/
2016/12/13 06:37:02 LnLqMfkN9Xwd,A5XFCSsSihU/xJ5-M5njhmsMAjSO7ygDbnqj/e58X5Lg2mjXyMtnjTs3BTwC4PXpA-SQbn5qOecUcu3tOOXc9xFrFlgSRjrDxk,0zQX7: Dir.Lookup
2016/12/13 06:37:02 LnLqMfkN9Xwd,A5XFCSsSihU/xJ5-M5njhmsMAjSO7ygDbnqj/e58X5Lg2mjXyMtnjTs3BTwC4PXpA-SQbn5qOecUcu3tOOXc9xFrFlgSRjrDxk,0zQX7: Dir.Lookup OK
2016/12/13 06:37:02 LnLqMfkN9Xwd,A5XFCSsSihU/xJ5-M5njhmsMAjSO7ygDbnqj/e58X5Lg2mjXyMtnjTs3BTwC4PXpA-SQbn5qOecUcu3tOOXc9xFrFlgSRjrDxk,0zQX7: File.Attr
2016/12/13 06:37:02 LnLqMfkN9Xwd,A5XFCSsSihU/xJ5-M5njhmsMAjSO7ygDbnqj/e58X5Lg2mjXyMtnjTs3BTwC4PXpA-SQbn5qOecUcu3tOOXc9xFrFlgSRjrDxk,0zQX7: File.Open
cp: cannot open 'e58X5Lg2mjXyMtnjTs3BTwC4PXpA-SQbn5qOecUcu3tOOXc9xFrFlgSRjrDxk,0zQX7' for reading: Input/output error

rsync -av e58X5Lg2mjXyMtnjTs3BTwC4PXpA-SQbn5qOecUcu3tOOXc9xFrFlgSRjrDxk,0zQX7 ~/
sending incremental file list
2016/12/13 06:38:00 LnLqMfkN9Xwd,A5XFCSsSihU/xJ5-M5njhmsMAjSO7ygDbnqj/e58X5Lg2mjXyMtnjTs3BTwC4PXpA-SQbn5qOecUcu3tOOXc9xFrFlgSRjrDxk,0zQX7: File.Open
rsync: send_files failed to open "/home/jeremy/acd_enc/LnLqMfkN9Xwd,A5XFCSsSihU/xJ5-M5njhmsMAjSO7ygDbnqj/e58X5Lg2mjXyMtnjTs3BTwC4PXpA-SQbn5qOecUcu3tOOXc9xFrFlgSRjrDxk,0zQX7": Input/output error (5)

sent 140 bytes  received 35 bytes  350.00 bytes/sec
total size is 4,909,415,695  speedup is 28,053,803.97
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
```
and this is the script I use to create the mount, which shows the mount options I am using.
```
#!/bin/bash

fusermount -u /home/jeremy/acd_dec
fusermount -u /home/jeremy/acd_enc


rclone mount -v --allow-other --gid 1000 --uid 1000 --max-read-ahead 4096k --no-modtime gdc:backup /home/jeremy/acd_enc &
export ENCFS6_CONFIG="/home/jeremy/.config/enc/.encfs6.xml"
export ENCFS6_PWFILE="/home/jeremy/.config/enc/k"
encfs /home/jeremy/acd_enc /home/jeremy/acd_dec --extpass=$ENCFS6_PWFILE -o allow_other

```
Any ideas what I am missing?

**Comment by tjeh** [comment]
Try downloading a file manually via the webinterface. My guess is you will recieve a "quota exceeded"...

**Comment by jpat0000** [comment]
Your files will only be inaccessible for 24 hours.

Related:

https://github.com/ncw/rclone/issues/897

If you want to use Google Drive & Plex with rclone, you need to significantly reduce folder seeking.

Here's some advice:

Don't sync, just upload your files. If you have a local folder, let's say "Movies", and a folder on Google Drive "Movies", and you simply want to upload or move your files to Google Drive, use rclone to upload them, with the added command "--no traverse". Example usage:

`rclone --no-check-certificate --no-traverse --drive-chunk-size=64M --transfers=6 move /home/myuser/Movies google:Data/Movies --exclude .@**`

Go into Plex > Settings> Server > Scheduled Tasks > Uncheck:

Remove old cache files every week (possibly)
Refresh local metadata every three days
Update all libraries during maintenance
Upgrade media analysis during maintenance
Refresh metadata periodically
Perform extensive media analysis during maintenance

Do not use --no-modtime when mounting Google Drive, Plex will need to re-analyze your files at every remount because it will believe your files have been in some way modified. General advice: try not to interrupt a library refresh, ever.

Move all of your movie files into a single directory, instead of allowing your Movies to have their own folder. It should be Movies/file.2016.mp4 instead of Movies/file.2016/file.2016.mp4

Do not excessively refresh your Plex library.

Do all of the above and you are unlikely to run into this problem again.

**Comment by jerblack** [comment]
This was a quota exceeded problem. I will wait to see if that error stops happening and test again.

**Comment by jpat0000** [comment]
@jerblack 

Each time you access a folder using rclone, rclone asks Google for the contents of your Google Drive, doing this too many times will result in exceeding one of their only seemingly realistically exceedable quotas. So when you run into this issue again you may want to do some stuff like I outlined which reduces the total times folders are accessed in a given day.

**Comment by jerblack** [comment]
Google started letting me download files again today, which made my rclone/encfs mount start working as expected. 

@jpat0000 I did follow the Plex configuration part of your advice, but I can't allow rclone to change the folder structure of my files since encfs expects a particular folder structure for encrypted content, so rearranging the encrypted files would break the decryption (at least that's my understanding of how it works). Regardless, I don't use rclone for uploads. I was having issues with rclone creating duplicate files and folders during upload so I had to stop using it, and I now use gdrive for uploads instead. I'm only using rclone for the mount with Google Drive.

**Comment by jpat0000** [comment]
@jerblack In my experience, I have been able to move around encfs encrypted files without breaking anything. You may want to look into crypt as an alternative if you're not too invested in encfs.

rclone should error out if you're uploading a duplicate file. Perhaps something about encfs slightly modifies the file making rclone believe it is different? If that were the case, you could probably solve the problem by adding "--ignore-existing".
