### ISSUE TITLE
[Feature Request] Amazon Drive folder timestamp matched to last modified file 

### ISSUE THREAD

**Issue by flixajki** [ncw/rclone#950]
At the moment Amazon Drive folder time stamp is matched with mount time and that is causing problems with apps like Plex which detect folder timestamp changes (on remount / server restarts ) and start unneeded rescan/media analyzation process. 

The change would be for folder time stamp to match latest modified file time stamp. 

p.s. When it comes to Plex the remounting eg restarting can be quite huge issue as the minimal video analyzation scan can take from 3 to 5 second per video and with big libraries that means 10 to 14h of scanning.

**Comment by ncw** [comment]
I've made a small modification which makes rclone report the actual modification times of directories as read from the remote.  Since ACD has a concept of directory and these have times then this should fix the problem for you.  Don't use `--no-mod-time` though (it doesn't buy you anything with ACD) and will confuse plex.

http://beta.rclone.org/v1.34-64-g13b705e/ (uploaded in 15-30 mins)

**Comment by flixajki** [comment]
Great, testing it now, time to refresh whole plex database with new times :)

**Comment by ncw** [comment]
@flixajki so does that help having stable directory times?

**Comment by flixajki** [comment]
@ncw yes Plex is not spastic about it anymore.

**Comment by ncw** [comment]
Great - I'll mark this one as closed then.
