### ISSUE TITLE
mount: Implement renaming directories

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#954]
version: rclone v1.34-67-g4428615β
OS: ubuntu 16.04 

To be honest never tried it until today, so far I always had the need to rename some files but never folders.
Today was the first time I tried and its not possible, error: already exist.

**Comment by deliverer33** [comment]
I have the same issue.  +1  Same version.

**Comment by ncw** [comment]
In the TODO section of the mount docs you'll see this is noted there: http://rclone.org/commands/rclone_mount/#todo

I'll re-purpose this issue into adding it as an enhancement.

**Comment by flixajki** [comment]
This is one of the top notch issues for quite few, which are downloading stuff directly on drive then renaming it after. 
I know that https://strmr.tv/ is sticking with acd_cli mainly because it have that support and as well all those which rent cheap VPS without much hdd eg no copy/move but strictly write on mount.

**Comment by ncw** [comment]
Note to self: Make the DirMove interface take a parameter so we get from, to?

**Comment by ncw** [comment]
I've finally managed to complete this - it took a lot longer than I expected due to various caching issues :-(

http://beta.rclone.org/v1.35-107-gef604f6/ (uploaded in 15-30 mins)
