### ISSUE TITLE
OneDrive Authentication

### ISSUE THREAD

**Issue by veritas2884** [ncw/rclone#955]
> What is your rclone version (eg output from `rclone -V`)
Rclone 1.34
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64bit
> Which cloud storage system are you using? (eg Google Drive)
One Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone authorize "onedrive"
>Issue

I am running my primary rclone on Ubuntu Server 16.04.1 LTS with ACD and it works perfectly.

I am trying to upload some files to my onedrive account and I went through the rclone config process.

Once I got to the Y/N headless option, I choose N, and it told me to run rclone authorize "onedrive" on a desktop machine (I had done this for ACD as well)

When I run this command, it took me in to authorize rclone through OneDrive, which I did.

This is where the problem comes in:

After authorizing I get:

This site can’t be reached
localhost.rclone.org’s server DNS address could not be found.
Search Google for localhost rclone org 53682
ERR_NAME_NOT_RESOLVED

And the CMD window never gets it input for me to paste into my SSH session.

Any help would be amazing!

**Comment by ncw** [comment]
localhost.rclone.org should resolve to 127.0.0.1 which it does when I try it.  Not sure why it wouldn't.

What happens if you open a shell/cmd window and type `ping localhost.rclone.org`?

You could try replacing `localhost.rclone.org` with `127.0.0.1` in the browser URL bar.

If all else fails you can copy the config file as detailed here: http://rclone.org/remote_setup/#configuring-by-copying-the-config-file

**Comment by veritas2884** [comment]
@ncw Thank you. I replaced the  localhost.rclone.org with 127.0.0.1 and it worked!

**Comment by ncw** [comment]
Excellent.  Not sure why that was necessary - some DNS strangeness!  Will close now :-)
